/* ═══════════════════════════════════════════════════════════
   Logic Simulator — Verilog HDL Export
   Generates synthesizable Verilog from circuit graph.
   Two modes:
     1. Structural — maps each component to Verilog primitives
     2. Behavioral — uses truth table + minimized expressions
   ═══════════════════════════════════════════════════════════ */
(function (L) {
  'use strict';

  const { Value, FALSE, TRUE } = L;

  class VerilogExporter {
    constructor(circuit) {
      this.circuit = circuit;
    }

    /* ── Structural Verilog (gate-level netlist) ── */
    exportStructural(moduleName) {
      moduleName = moduleName || 'circuit';
      const c = this.circuit;
      const lines = [];
      const inputs = [];
      const outputs = [];
      const wires = [];
      const assigns = [];
      const always = [];

      // Map component IDs to wire names
      const wireMap = {};  // compId_portIdx → wire name
      var wireCount = 0;

      // Collect inputs and outputs
      for (const comp of c.components.values()) {
        if (comp.type === 'INPUT') {
          var name = sanitize(comp.attrs.label || 'in_' + comp.id);
          inputs.push(name);
          wireMap[comp.id + '_0'] = name;
        } else if (comp.type === 'OUTPUT') {
          var name = sanitize(comp.attrs.label || 'out_' + comp.id);
          outputs.push(name);
          wireMap[comp.id + '_0'] = name;
        } else if (comp.type === 'CLOCK') {
          var name = 'clk_' + comp.id;
          inputs.push(name);
          wireMap[comp.id + '_0'] = name;
        }
      }

      // Create internal wires for all non-IO component ports
      for (const comp of c.components.values()) {
        if (comp.type === 'INPUT' || comp.type === 'OUTPUT' || comp.type === 'CLOCK') continue;
        for (var i = 0; i < comp.ports.length; i++) {
          var key = comp.id + '_' + i;
          if (!wireMap[key] && comp.ports[i].dir === 'out') {
            wireMap[key] = 'w' + (wireCount++);
          }
        }
      }

      // Trace wires to propagate names through connections
      for (const w of c.wires.values()) {
        var fromKey = w.fromCompId + '_' + w.fromPortIdx;
        var toKey = w.toCompId + '_' + w.toPortIdx;
        if (wireMap[fromKey] && !wireMap[toKey]) {
          wireMap[toKey] = wireMap[fromKey];
        } else if (wireMap[toKey] && !wireMap[fromKey]) {
          wireMap[fromKey] = wireMap[toKey];
        } else if (!wireMap[fromKey] && !wireMap[toKey]) {
          var wireName = 'w' + (wireCount++);
          wireMap[fromKey] = wireName;
          wireMap[toKey] = wireName;
        }
      }

      // Collect unique internal wire names
      var internalWires = {};
      Object.keys(wireMap).forEach(function(key) {
        var name = wireMap[key];
        if (inputs.indexOf(name) === -1 && outputs.indexOf(name) === -1) {
          internalWires[name] = true;
        }
      });

      // Generate component instantiations
      for (const comp of c.components.values()) {
        var type = comp.type;
        if (type === 'INPUT' || type === 'OUTPUT' || type === 'CLOCK') continue;
        if (type === 'PROBE' || type === 'TEXT_LABEL') continue;

        var inst = componentToVerilog(comp, wireMap);
        if (inst) {
          if (inst.type === 'assign') assigns.push(inst.code);
          else if (inst.type === 'always') always.push(inst.code);
        }
      }

      // Build module
      lines.push('// Generated by 8gwifi.org Logic Gate Simulator');
      lines.push('// ' + new Date().toISOString());
      lines.push('');
      lines.push('module ' + moduleName + ' (');
      var ports = [];
      inputs.forEach(function(n) { ports.push('  input  ' + n); });
      outputs.forEach(function(n) { ports.push('  output ' + n); });
      lines.push(ports.join(',\n'));
      lines.push(');');
      lines.push('');

      // Wire declarations
      var wireNames = Object.keys(internalWires).sort();
      if (wireNames.length > 0) {
        lines.push('  wire ' + wireNames.join(', ') + ';');
        lines.push('');
      }

      // Assign statements (combinational)
      assigns.forEach(function(a) { lines.push('  ' + a); });
      if (assigns.length > 0) lines.push('');

      // Always blocks (sequential)
      always.forEach(function(a) {
        a.split('\n').forEach(function(l) { lines.push('  ' + l); });
        lines.push('');
      });

      lines.push('endmodule');
      return lines.join('\n');
    }

    /* ── Behavioral Verilog (from truth table) ── */
    exportBehavioral(moduleName) {
      moduleName = moduleName || 'circuit';
      var analyzer = new L.Analyzer(this.circuit);
      var tt = analyzer.generateTruthTable();
      if (!tt || tt.error) return '// Error: ' + (tt ? tt.error : 'could not generate truth table');

      var lines = [];
      lines.push('// Generated by 8gwifi.org Logic Gate Simulator (behavioral)');
      lines.push('// ' + new Date().toISOString());
      lines.push('');
      lines.push('module ' + moduleName + ' (');

      var ports = [];
      tt.inputNames.forEach(function(n) { ports.push('  input  ' + sanitize(n)); });
      tt.outputNames.forEach(function(n) { ports.push('  output ' + sanitize(n)); });
      lines.push(ports.join(',\n'));
      lines.push(');');
      lines.push('');

      // Generate minimized expression for each output
      for (var oi = 0; oi < tt.outputNames.length; oi++) {
        var result = analyzer.minimize(tt, oi);
        var expr = result.expr;
        // Convert math notation to Verilog
        expr = expr.replace(/\u00AC(\w)/g, '~$1');  // ¬A → ~A
        expr = expr.replace(/\u00B7/g, ' & ');        // · → &
        expr = expr.replace(/ \+ /g, ' | ');          // + → |
        lines.push('  assign ' + sanitize(tt.outputNames[oi]) + ' = ' + expr + ';');
      }

      lines.push('');
      lines.push('endmodule');
      return lines.join('\n');
    }
  }

  /* ── Component → Verilog mapping ── */
  function componentToVerilog(comp, wireMap) {
    var type = comp.type;

    function portWire(idx) {
      return wireMap[comp.id + '_' + idx] || "'bx";
    }

    // Gates → assign with operators
    var gateOps = {
      'AND': '&', 'OR': '|', 'XOR': '^',
      'NAND': '~&', 'NOR': '~|', 'XNOR': '~^'
    };

    if (gateOps[type]) {
      var numIn = (comp.attrs.inputs || 2);
      var outIdx = numIn;  // output is last port
      var inParts = [];
      for (var i = 0; i < numIn; i++) inParts.push(portWire(i));

      var op = gateOps[type];
      var expr;
      if (op.charAt(0) === '~') {
        // NAND/NOR/XNOR: negate the result
        expr = '~(' + inParts.join(' ' + op.charAt(1) + ' ') + ')';
      } else {
        expr = inParts.join(' ' + op + ' ');
      }
      return { type: 'assign', code: 'assign ' + portWire(outIdx) + ' = ' + expr + ';' };
    }

    if (type === 'NOT') {
      return { type: 'assign', code: 'assign ' + portWire(1) + ' = ~' + portWire(0) + ';' };
    }

    if (type === 'BUFFER') {
      return { type: 'assign', code: 'assign ' + portWire(1) + ' = ' + portWire(0) + ';' };
    }

    if (type === 'CONSTANT') {
      var val = comp.attrs.value ? "1'b1" : "1'b0";
      return { type: 'assign', code: 'assign ' + portWire(0) + ' = ' + val + ';' };
    }

    if (type === 'PULL_RESISTOR') {
      var val = comp.attrs.pullTo ? "1'b1" : "1'b0";
      return { type: 'assign', code: 'assign ' + portWire(0) + ' = ' + val + '; // pull resistor' };
    }

    // MUX: Y = SEL ? D1 : D0
    if (type === 'MUX') {
      return { type: 'assign', code: 'assign ' + portWire(3) + ' = ' + portWire(2) + ' ? ' + portWire(1) + ' : ' + portWire(0) + ';' };
    }

    // Flip-flops → always block
    if (type === 'D_FF') {
      // ports: [D=0, CLK=1, CLR=2, Q=3, Q'=4]
      var q = portWire(3);
      var qn = portWire(4);
      return { type: 'always', code:
        'reg ' + q + '_reg = 0;\n' +
        'assign ' + q + ' = ' + q + '_reg;\n' +
        'assign ' + qn + ' = ~' + q + '_reg;\n' +
        'always @(posedge ' + portWire(1) + ' or posedge ' + portWire(2) + ')\n' +
        '  if (' + portWire(2) + ') ' + q + '_reg <= 0;\n' +
        '  else ' + q + '_reg <= ' + portWire(0) + ';'
      };
    }

    if (type === 'T_FF') {
      var q = portWire(2);
      return { type: 'always', code:
        'reg ' + q + '_reg = 0;\n' +
        'assign ' + q + ' = ' + q + '_reg;\n' +
        'assign ' + portWire(3) + ' = ~' + q + '_reg;\n' +
        'always @(posedge ' + portWire(1) + ')\n' +
        '  if (' + portWire(0) + ') ' + q + '_reg <= ~' + q + '_reg;'
      };
    }

    if (type === 'SR_FF') {
      var q = portWire(3);
      return { type: 'always', code:
        'reg ' + q + '_reg = 0;\n' +
        'assign ' + q + ' = ' + q + '_reg;\n' +
        'assign ' + portWire(4) + ' = ~' + q + '_reg;\n' +
        'always @(posedge ' + portWire(1) + ')\n' +
        '  if (' + portWire(0) + ') ' + q + '_reg <= 1;\n' +
        '  else if (' + portWire(2) + ') ' + q + '_reg <= 0;'
      };
    }

    if (type === 'JK_FF') {
      var q = portWire(3);
      return { type: 'always', code:
        'reg ' + q + '_reg = 0;\n' +
        'assign ' + q + ' = ' + q + '_reg;\n' +
        'assign ' + portWire(4) + ' = ~' + q + '_reg;\n' +
        'always @(posedge ' + portWire(1) + ')\n' +
        '  case ({' + portWire(0) + ', ' + portWire(2) + '})\n' +
        "    2'b01: " + q + '_reg <= 0;\n' +
        "    2'b10: " + q + '_reg <= 1;\n' +
        "    2'b11: " + q + '_reg <= ~' + q + '_reg;\n' +
        '  endcase'
      };
    }

    // ADDER: {Cout, S} = A + B + Cin
    if (type === 'ADDER') {
      return { type: 'assign', code: 'assign {' + portWire(4) + ', ' + portWire(3) + '} = ' + portWire(0) + ' + ' + portWire(1) + ' + ' + portWire(2) + ';' };
    }

    if (type === 'SUBTRACTOR') {
      return { type: 'assign', code: 'assign {' + portWire(4) + ', ' + portWire(3) + '} = ' + portWire(0) + ' - ' + portWire(1) + ' - ' + portWire(2) + ';' };
    }

    // LED, SPLITTER, TUNNEL — pass-through or no-op
    if (type === 'LED' || type === 'SEVEN_SEG' || type === 'HEX_DISPLAY') {
      return null; // display-only, no Verilog equivalent
    }

    if (type === 'SPLITTER') {
      // Fan-out: all outputs = input
      var numOut = (comp.attrs.fanout || 2);
      var code = '';
      for (var i = 1; i <= numOut; i++) {
        code += 'assign ' + portWire(i) + ' = ' + portWire(0) + ';\n';
      }
      return { type: 'assign', code: code.trim() };
    }

    // Unknown — comment
    return { type: 'assign', code: '// TODO: ' + type + ' (component ' + comp.id + ')' };
  }

  function sanitize(name) {
    // Verilog identifier: start with letter/underscore, then alphanumeric/underscore
    var s = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (/^[0-9]/.test(s)) s = '_' + s;
    return s || '_unnamed';
  }

  // ── Public API ──
  L.VerilogExporter = VerilogExporter;

})(window.LogicSim);
