package z.y.x.cube.cube555;

/**
 * Verifies the 5×5 EO encoder ({@link Cube555Edges#encodeEOOuter} and
 * {@link Cube555Edges#highlowEdges}) byte-equivalent to Python's
 * {@code highlow_edges_state()} on three deterministic 15-move scrambles.
 *
 * <p>The expected values were captured directly from Python via
 * {@code rubikscubennnsolver.RubiksCube555}.
 */
public final class Cube555EdgesTest {

    private static int passed = 0;
    private static int failed = 0;

    private static long lcg(long x) { return ((x * 1664525L) + 1013904223L) & 0xFFFFFFFFL; }

    private static String scramble(long seed, int n) {
        StringBuilder mv = new StringBuilder();
        long x = seed;
        for (int i = 0; i < n; i++) {
            x = lcg(x);
            int idx = (int) (x % Cube555Moves.ALL_MOVES.size());
            if (mv.length() > 0) mv.append(' ');
            mv.append(Cube555Moves.ALL_MOVES.get(idx));
        }
        return mv.toString();
    }

    private static void check(String name, String expected, String actual) {
        if (expected.equals(actual)) {
            passed++;
            System.out.println("PASS: " + name);
        } else {
            failed++;
            System.err.println("FAIL: " + name);
            System.err.println("  expected: " + expected);
            System.err.println("  actual:   " + actual);
            int n = Math.min(expected.length(), actual.length());
            for (int i = 0; i < n; i++) {
                if (expected.charAt(i) != actual.charAt(i)) {
                    System.err.println("  first diff @ " + i + ": expected '"
                        + expected.charAt(i) + "', got '" + actual.charAt(i) + "'");
                    break;
                }
            }
        }
    }

    public static void main(String[] args) {
        // Resource-load test: highlow table parsed cleanly.
        int n = HighLowEdges555.loadedEntryCount();
        System.out.println("Loaded " + n + " highlow entries");
        if (n != 1728) {
            failed++;
            System.err.println("FAIL: expected 1728 highlow entries, got " + n);
        } else {
            passed++;
        }

        // Sanity: outer + inner orbit indices partition [0, 72).
        boolean[] seen = new boolean[Cube555Edges.ORIENT_PAIR_COUNT];
        for (int i : Cube555Edges.OUTER_ORBIT_INDICES) seen[i] = true;
        for (int i : Cube555Edges.INNER_ORBIT_INDICES) {
            if (seen[i]) {
                failed++;
                System.err.println("FAIL: orbit indices overlap at " + i);
                break;
            }
            seen[i] = true;
        }
        boolean allCovered = true;
        for (boolean s : seen) if (!s) { allCovered = false; break; }
        if (allCovered) { passed++; System.out.println("PASS: outer+inner orbits partition [0, 72)"); }
        else { failed++; System.err.println("FAIL: orbit indices don't cover [0, 72)"); }

        // SOLVED state highlow encoding — every wing is in its native
        // position so highlow should be all-U (or some predictable value).
        // We don't hardcode SOLVED's expected encoding; instead, verify
        // it has no '.' (meaning every pair was in the table).
        String solvedHL = Cube555Edges.highlowEdges(Cube555.SOLVED);
        if (solvedHL.length() == 72 && solvedHL.indexOf('.') < 0) {
            passed++;
            System.out.println("PASS: SOLVED highlow has 72 chars, no missing entries");
        } else {
            failed++;
            System.err.println("FAIL: SOLVED highlow malformed: " + solvedHL);
        }

        // ── Byte-equivalence with Python ground truth ──────────────
        // Generated by:  python3 .../RubiksCube555 highlow_edges_state()
        // applied to LCG-driven 15-move scrambles (seeds 1, 7, 42).

        String state1 = Cube555Moves.applyMoves(Cube555.SOLVED, scramble(1, 15));
        check("seed=1 highlow72",
            "DUDDDDUDDUUUDDDUDUDUUUDUUUUDDDUUUUUUDUDDUUUUDDDUDUDUUUUDUDUDUUUUDDDUUDUD",
            Cube555Edges.highlowEdges(state1));
        check("seed=1 EO outer48",
            "DDDDDDUUDDUDUUUUUUDDUUUUDDDUUDDUDDUUDUDDUUUDUUDD",
            Cube555Edges.encodeEOOuter(state1));

        String state7 = Cube555Moves.applyMoves(Cube555.SOLVED, scramble(7, 15));
        check("seed=7 highlow72",
            "UDUDUUUDDUUDDUDUDDDDUDDDUUDDDDUUDUUDDUUDUUUDUDUUUDUUUUDUDUUUUUDDDDUDUUUU",
            Cube555Edges.highlowEdges(state7));
        check("seed=7 EO outer48",
            "UUDUDDUDDDUDDUDDUDDDUDUDDUDUDUDUUUUUUDUUUDDDDUUU",
            Cube555Edges.encodeEOOuter(state7));

        String state42 = Cube555Moves.applyMoves(Cube555.SOLVED, scramble(42, 15));
        check("seed=42 highlow72",
            "DUDDDUDDUUUDDUDUDUUUDUUUUUDDUUDDUDUUUDDUDDDUDDDUDUDDUDUDUUUUDUUUDUDUUUUU",
            Cube555Edges.highlowEdges(state42));
        check("seed=42 EO outer48",
            "DDDDDUUDDDUDUDUUUDDUDUDUUDUDUDDUDDDUDUUUDUUDUUUU",
            Cube555Edges.encodeEOOuter(state42));

        // ── Inner orbit (midges) ──────────────────────────────────
        check("seed=1 EO inner24",  "UDUUDUDDUDUUUUUDUUUUUDDU", Cube555Edges.encodeEOInner(state1));
        check("seed=7 EO inner24",  "DUUUUDDDUDUUUUUUDUDUUDUU", Cube555Edges.encodeEOInner(state7));
        check("seed=42 EO inner24", "UUDUUUUUUUDUDDDDUDUUUUDU", Cube555Edges.encodeEOInner(state42));

        System.out.println();
        System.out.println(passed + " passed, " + failed + " failed");
        System.exit(failed == 0 ? 0 : 1);
    }

    private Cube555EdgesTest() {}
}
