<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="true" %>
<% String v = String.valueOf(System.currentTimeMillis()); %>
<!DOCTYPE html>
<html lang="en">
<head>
    <%--
        Olympiad Stepwise Practice — untimed practice page.
        Data: /math/olympiad/data/{q,s,dgm,meta.json} generated by split_olympiad.py.
        Engine: /math/olympiad/js/practice-engine.js (vanilla; no build).
    --%>
    <jsp:include page="../../modern/components/seo-tool-page.jsp">
        <jsp:param name="toolName" value="Math Olympiad Practice Problems with Solutions — Free, Stepwise, Online" />
        <jsp:param name="toolCategory" value="Math Tools" />
        <jsp:param name="toolDescription" value="Free math olympiad practice with step-by-step solutions. Real past problems for IMO, USAMO, AIME, RMO, INMO, Putnam. Untimed practice, type-and-check answers, print-ready walkthroughs. No signup." />
        <jsp:param name="toolUrl" value="math/olympiad/" />
        <jsp:param name="breadcrumbCategoryUrl" value="math/" />
        <jsp:param name="toolKeywords" value="math olympiad problems with solutions, free olympiad math practice, math olympiad practice test online, stepwise math solutions, IMO practice problems, USAMO prep, AIME practice problems, RMO problems with solutions, INMO problems with solutions, Pre-RMO practice, Putnam problems with solutions, math olympiad questions and answers, math olympiad worksheet, olympiad math grade 9 10 11 12, high school math olympiad, math olympiad sample papers, olympiad algebra problems, olympiad geometry problems, olympiad number theory problems, olympiad combinatorics problems, math olympiad printable, math olympiad PDF alternative, AoPS olympiad problems, competition math practice" />
        <jsp:param name="toolImage" value="olympiad-practice-og.png" />
        <jsp:param name="toolFeatures" value="Real past math olympiad problems with stepwise solutions,Untimed practice — go as slow or fast as you want,Type-and-check answers (smart matching for fractions and radicals),Peek at expected answer without revealing the full walkthrough,Reveal full numbered walkthrough on demand,Print problem + solution for offline study (8gwifi.org branded),Session stats — attempted / correct / streak / accuracy / best (saved in browser),KaTeX math rendering and pre-rendered Asymptote diagrams" />
        <jsp:param name="hasSteps" value="true" />
        <jsp:param name="teaches" value="Math olympiad problem solving across algebra, geometry, number theory, combinatorics; AIME, USAMO, RMO, INMO, IMO, Putnam problem patterns; technique recognition; stepwise decomposition" />
        <jsp:param name="educationalLevel" value="High School, Undergraduate" />
        <jsp:param name="howToSteps" value="Pick a problem|Click Start or Next problem. A fresh random olympiad problem loads with KaTeX-rendered math and any required diagrams.,Try it yourself first|If the problem has a closed-form answer type it and hit Check. Smart matching accepts casual forms like 1/2 or sqrt(5). Click Peek to compare with the official answer without revealing the walkthrough.,Read the stepwise solution|Click Reveal stepwise solution for the full numbered walkthrough — key insight first then steps 1 2 3 with all the LaTeX rendered.,Print for offline study|Click Print to get a clean PDF with the problem and solution plus the 8gwifi.org source line at top and bottom.,Track your progress|Session stats (attempted / correct / streak / accuracy / best streak) save in your browser. Reset any time." />
        <jsp:param name="faq1q" value="What level are these problems?" />
        <jsp:param name="faq1a" value="Olympiad and pre-olympiad difficulty — AIME, USAMO, IMO-style training problems plus RMO / INMO / Pre-RMO and Putnam material. The pool draws from real past competitions across algebra, geometry, number theory, and combinatorics, with detailed numbered solutions written for instructional clarity." />
        <jsp:param name="faq2q" value="How is this different from the AMC and AIME mock tests?" />
        <jsp:param name="faq2a" value="The AMC and AIME pages are timed competition emulators with scoring. This page is untimed practice — one problem at a time, full stepwise solutions on demand, no clock pressure. Useful for learning new techniques and reviewing worked examples." />
        <jsp:param name="faq3q" value="Can I check my answer if the answer is a fraction or expression?" />
        <jsp:param name="faq3a" value="Yes. The Check button uses smart matching — fractions can be typed as 1/2 (matches \\frac{1}{2}), radicals as sqrt(5) (matches \\sqrt{5}), and decimals automatically compare against fractions. For matrix or vector answers, click Peek to see the expected answer rendered in math and compare on paper." />
        <jsp:param name="faq4q" value="Can I print a problem with its solution?" />
        <jsp:param name="faq4a" value="Yes. Click Print on any problem. The print view includes the question and full stepwise walkthrough at print-friendly typography with an 8gwifi.org/math/olympiad source line — useful as offline worksheets or PDFs." />
        <jsp:param name="faq5q" value="Are my stats saved across sessions?" />
        <jsp:param name="faq5a" value="Yes — attempted / correct / streak / best-streak save in your browser's localStorage. Nothing is sent to a server. Click Reset on the stat bar to clear them any time." />
        <jsp:param name="faq6q" value="Does this cover the Indian Math Olympiad path (RMO / INMO)?" />
        <jsp:param name="faq6a" value="Yes — the pool includes RMO, INMO, Pre-RMO, and IMO-shortlist style problems alongside US olympiad material. Difficulty mix is random so you'll see a range; use Next problem until something at the level you want shows up." />
        <jsp:param name="faq7q" value="Where do the problems come from?" />
        <jsp:param name="faq7a" value="Built from a public stepwise-solution olympiad dataset (open archives, AoPS-style worked examples). Every problem has a key insight paragraph followed by numbered steps with rendered LaTeX and any required diagrams." />
    </jsp:include>

    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "Free Olympiad Math Practice",
      "url": "https://8gwifi.org/math/olympiad/",
      "applicationCategory": "EducationalApplication",
      "operatingSystem": "Any (browser)",
      "offers": { "@type": "Offer", "price": "0.00", "priceCurrency": "USD" },
      "isAccessibleForFree": true
    }
    </script>

    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/design-system.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/navigation.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/dark-mode.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/footer.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/ads.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/css/math-studio.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/amc/css/exam.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/olympiad/css/practice.css?v=<%=v%>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">

    <%@ include file="../../modern/ads/ad-init.jsp" %>
</head>
<body class="ms-body">

<jsp:include page="../../modern/components/nav-header.jsp" />
<jsp:include page="/math/partials/matter-bg.jsp" />

<div class="ms-hero">
    <%@ include file="../../modern/ads/ad-hero-banner.jsp" %>
</div>

<main class="ms-main">

    <button type="button" id="msSidebarToggle" class="ms-sidebar-toggle" aria-label="Open math tools menu">
        &#9776; Math tools
    </button>

    <% request.setAttribute("activeService", "olympiad-practice"); %>
    <jsp:include page="/math/partials/sidebar.jsp" />

    <section class="ms-workspace">

        <header class="ms-title">
            <nav class="ms-crumbs">
                <a href="<%=request.getContextPath()%>/index.jsp">Home</a>
                <span>/</span>
                <a href="<%=request.getContextPath()%>/math/">Math</a>
                <span>/</span>
                <span aria-current="page">Olympiad Practice</span>
            </nav>
            <h1>Free Olympiad Math Practice &mdash; Untimed, with Stepwise Solutions</h1>
            <p class="xm-hero-sub">
                Olympiad-level practice with detailed stepwise walkthroughs. Type
                your answer to check, or reveal the full numbered solution on
                demand. <strong>Untimed · single problem at a time · no signup.</strong>
            </p>
        </header>

        <div id="op-root"></div>

        <div class="ms-inline-ad">
            <%@ include file="../../modern/ads/ad-in-content-mid.jsp" %>
        </div>

        <%-- ─────────────────────────── SEO body ─────────────────────────── --%>

        <nav class="xm-toc" aria-label="On this page">
            <span class="xm-toc-label">On this page:</span>
            <a href="#about">What is this</a>
            <a href="#pathways">Olympiad pathways</a>
            <a href="#how">How to use it</a>
            <a href="#topics">Topics</a>
            <a href="#related">AMC &amp; AIME</a>
            <a href="#faq">FAQ</a>
        </nav>

        <section class="xm-seo-section" id="about">
            <h2>Free math olympiad practice problems with stepwise solutions</h2>
            <p>
                If you're prepping for <strong>AMC, AIME, USAMO, IMO, RMO,
                INMO, Pre-RMO,</strong> or <strong>Putnam</strong>, the single
                highest-leverage activity isn't watching lectures — it's
                solving real past problems and then carefully reading the
                worked solutions written by strong solvers. This page gives
                you that, free, untimed, in your browser.
            </p>
            <p>
                Each session loads a fresh random problem with the math
                rendered in KaTeX and any geometry diagrams pre-built. Type
                your answer (with smart matching for fractions, radicals,
                decimals) or click <strong>Peek</strong> to compare with the
                official answer. When you're ready, expand the
                <em>stepwise walkthrough</em> — every solution starts with a
                key-insight paragraph explaining the technique, then numbered
                steps with all the algebra shown. Use the <strong>Print</strong>
                button to save problems as offline worksheets or PDFs.
            </p>
        </section>

        <section class="xm-seo-section" id="pathways">
            <h2>Math olympiad pathways covered</h2>
            <p>
                The pool spans the major competition tracks. Use Next
                problem until you land on something from the path you're
                targeting:
            </p>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/">
                    <div class="xm-related-card-title">AMC 10 / 12 path</div>
                    <div class="xm-related-card-desc">US entry contest — 25 MCQ, 75 minutes. Try the timed mock.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/aime.jsp">
                    <div class="xm-related-card-title">AIME path</div>
                    <div class="xm-related-card-desc">Integer answers 0–999, 3-hour invitational. Timed mock available.</div>
                </a>
                <a class="xm-related-card" href="#about">
                    <div class="xm-related-card-title">USAMO / USAJMO</div>
                    <div class="xm-related-card-desc">Proof-style problems. AIME-qualifiers' next step.</div>
                </a>
                <a class="xm-related-card" href="#about">
                    <div class="xm-related-card-title">IMO &amp; IMO shortlist</div>
                    <div class="xm-related-card-desc">International Math Olympiad — the top of the global pyramid.</div>
                </a>
                <a class="xm-related-card" href="#about">
                    <div class="xm-related-card-title">RMO / INMO (India)</div>
                    <div class="xm-related-card-desc">Pre-RMO → Regional → Indian National → IMOTC selection.</div>
                </a>
                <a class="xm-related-card" href="#about">
                    <div class="xm-related-card-title">Putnam</div>
                    <div class="xm-related-card-desc">Undergraduate-level US competition — harder algebra and analysis.</div>
                </a>
            </div>
        </section>

        <section class="xm-seo-section" id="how">
            <h2>How to use it</h2>
            <ol class="xm-info-list xm-info-list-ol">
                <li><strong>Try the problem cold first.</strong> If it has a single boxed answer (about 56% do), type your guess and hit Check. Wrong is fine — that's how technique sticks.</li>
                <li><strong>Reveal the walkthrough.</strong> Click <em>Reveal stepwise solution</em> to expand the full numbered solution. Read the key-insight line first; it usually names the technique.</li>
                <li><strong>Trace your own attempt against the steps.</strong> Where did you diverge from the solution? That divergence is where the learning is.</li>
                <li><strong>Click Next problem.</strong> Fresh random problem every time. Your session stats (attempted / correct / streak) save in your browser.</li>
                <li><strong>Don't optimize for the streak.</strong> Stats are there to nudge consistency; revealing isn't failure. The point is learning, not raw accuracy.</li>
            </ol>
        </section>

        <section class="xm-seo-section" id="topics">
            <h2>Topics in the pool</h2>
            <p>
                The pool mixes the four major olympiad strands. Build the
                foundational toolkit with these free helpers:
            </p>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/matrix-calculator.jsp">
                    <div class="xm-related-card-title">Algebra &amp; linear algebra</div>
                    <div class="xm-related-card-desc">Polynomial identities, matrix work, vector tricks.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/trigonometric-identity-calculator.jsp">
                    <div class="xm-related-card-title">Geometry &amp; trig</div>
                    <div class="xm-related-card-desc">Power of a point, mass-point, identities, coord-bashing.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/probability-calculator.jsp">
                    <div class="xm-related-card-title">Combinatorics</div>
                    <div class="xm-related-card-desc">Counting, pigeonhole, casework, generating functions.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/system-equations-solver.jsp">
                    <div class="xm-related-card-title">Number theory</div>
                    <div class="xm-related-card-desc">Modular arithmetic, Diophantine equations, parity tricks.</div>
                </a>
            </div>
        </section>

        <section class="xm-seo-section" id="related">
            <h2>Looking for a timed mock test?</h2>
            <p>
                This page is untimed. If you want a live-clock contest emulator
                with official scoring, try one of these:
            </p>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/">
                    <div class="xm-related-card-title">AMC 10 / 12 Mock Test</div>
                    <div class="xm-related-card-desc">25 MCQ problems · 75-min timer · official +6 / +1.5 / 0 scoring.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/aime.jsp">
                    <div class="xm-related-card-title">AIME Mock Test</div>
                    <div class="xm-related-card-desc">15 free-response problems · 3-hour timer · integer answers 0–999.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/worksheet.jsp">
                    <div class="xm-related-card-title">Practice worksheets</div>
                    <div class="xm-related-card-desc">Printable worksheets across algebra, geometry, calculus.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/">
                    <div class="xm-related-card-title">All math tools</div>
                    <div class="xm-related-card-desc">Browse 48+ free calculators and solvers.</div>
                </a>
            </div>
        </section>

        <section class="xm-seo-section" id="faq">
            <h2>Frequently asked questions</h2>
            <details class="xm-faq-item" open>
                <summary>What level are these problems?</summary>
                <p>Olympiad and pre-olympiad difficulty — AIME, USAMO, IMO-style training problems plus RMO / INMO / Pre-RMO and Putnam material. The pool draws from real past competitions across algebra, geometry, number theory, and combinatorics, with detailed numbered solutions written for instructional clarity.</p>
            </details>
            <details class="xm-faq-item">
                <summary>How is this different from the AMC and AIME mock tests?</summary>
                <p>The <a href="<%=request.getContextPath()%>/math/amc/">AMC</a> and <a href="<%=request.getContextPath()%>/math/amc/aime.jsp">AIME</a> pages are timed competition emulators with scoring. This page is <em>untimed</em> practice — one problem at a time, full stepwise solutions on demand, no clock pressure. Useful for learning new techniques and reviewing worked examples.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Can I check my answer if it's a fraction or expression?</summary>
                <p>Yes. The Check button uses smart matching — fractions can be typed as <code>1/2</code> (matches <code>\frac{1}{2}</code>), radicals as <code>sqrt(5)</code>, and decimals automatically compare against fractions. For matrix or vector answers, click <strong>Peek</strong> to see the expected answer rendered in math and compare on paper.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Can I print a problem with its solution?</summary>
                <p>Yes. Click <strong>Print</strong> on any problem. The print view includes the question and full stepwise walkthrough at print-friendly typography with an 8gwifi.org/math/olympiad source line — useful as offline worksheets or saved PDFs.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Does this cover the Indian Math Olympiad path (RMO / INMO)?</summary>
                <p>Yes — the pool includes RMO, INMO, Pre-RMO, and IMO-shortlist style problems alongside US olympiad material. Difficulty mix is random so you'll see a range; use Next problem until something at the level you want shows up.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Are my stats saved across sessions?</summary>
                <p>Yes — attempted / correct / streak / best-streak save in your browser's localStorage. Nothing is sent to a server. Click Reset on the stat bar to clear them any time.</p>
            </details>
            <details class="xm-faq-item">
                <summary>How do I get a different problem?</summary>
                <p>Click <em>Next problem</em>. The engine picks a fresh random problem from the pool — and swaps to a different random shard once you've seen half of the current one, so you keep getting variety.</p>
            </details>
        </section>

    </section>

    <aside class="ms-rail" aria-label="Advertisements">
        <%@ include file="../../modern/ads/ad-ide-rail-top.jsp" %>
        <%@ include file="../../modern/ads/ad-ide-rail-bottom.jsp" %>
    </aside>

</main>

<%@ include file="../../modern/ads/ad-sticky-footer.jsp" %>
<%@ include file="../../modern/components/analytics.jsp" %>

<jsp:include page="/math/partials/math-libs.jsp" />

<script src="<%=request.getContextPath()%>/math/olympiad/js/practice-engine.js?v=<%=v%>"></script>
<script>
    OlympiadEngine.init({
        rootId:   'op-root',
        dataBase: '<%=request.getContextPath()%>/math/olympiad/data',
        bucket:   'olympiad-stepwise',
        title:    'Olympiad Stepwise Practice'
    });
</script>

</body>
</html>
