<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%--
    Multi-File Compiler Component

    For Java, Go, and other languages that may need multiple files.

    Parameters:
    - language: Programming language (java, go, cpp, etc.)
    - editorId: Unique ID for this editor instance
    - files: JSON array of files [{name: "Main.java", code: "...", main: true}]

    Usage:
    <jsp:include page="../tutorial-compiler-multifile.jsp">
        <jsp:param name="language" value="java" />
        <jsp:param name="editorId" value="compiler-java-classes" />
        <jsp:param name="files" value='[{"name":"Main.java","code":"public class Main { ... }","main":true},{"name":"Helper.java","code":"public class Helper { ... }"}]' />
    </jsp:include>
--%>
<%
    String language = request.getParameter("language");
    if (language == null) language = "java";

    String editorId = request.getParameter("editorId");
    if (editorId == null) editorId = "multicompiler1";

    String filesJson = request.getParameter("files");
    if (filesJson == null) {
        // Default single file
        if (language.equals("java")) {
            filesJson = "[{\"name\":\"Main.java\",\"code\":\"public class Main {\\n    public static void main(String[] args) {\\n        System.out.println(\\\"Hello, World!\\\");\\n    }\\n}\",\"main\":true}]";
        } else if (language.equals("go")) {
            filesJson = "[{\"name\":\"main.go\",\"code\":\"package main\\n\\nimport \\\"fmt\\\"\\n\\nfunc main() {\\n    fmt.Println(\\\"Hello, World!\\\")\\n}\",\"main\":true}]";
        } else {
            filesJson = "[{\"name\":\"main.py\",\"code\":\"print('Hello, World!')\",\"main\":true}]";
        }
    }
%>

<div class="multifile-compiler" id="<%= editorId %>-container" data-language="<%= language %>">
    <!-- File Tabs -->
    <div class="multifile-header">
        <div class="file-tabs" id="<%= editorId %>-tabs">
            <!-- Tabs generated by JavaScript -->
        </div>
        <div class="file-actions">
            <button class="file-action-btn" onclick="addFile('<%= editorId %>')" title="Add File">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M12 5v14M5 12h14"/>
                </svg>
            </button>
            <button class="compiler-btn compiler-btn-ghost" onclick="resetMultiCompiler('<%= editorId %>')" title="Reset">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/>
                    <path d="M3 3v5h5"/>
                </svg>
            </button>
            <button class="compiler-btn compiler-btn-primary" id="<%= editorId %>-run-btn" onclick="runMultiCompiler('<%= editorId %>')">
                <svg class="play-icon" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M8 5v14l11-7z"/>
                </svg>
                <span>Run</span>
            </button>
        </div>
    </div>

    <!-- Editor Area -->
    <div class="multifile-editor">
        <div class="line-numbers" id="<%= editorId %>-line-numbers"></div>
        <textarea id="<%= editorId %>-code"
                  class="compiler-textarea"
                  spellcheck="false"
                  autocomplete="off"></textarea>
    </div>

    <!-- Input Tab (hidden by default) -->
    <div class="multifile-input-section" id="<%= editorId %>-input-section" style="display: none;">
        <div class="input-header">
            <span>Input (stdin)</span>
            <button class="close-input-btn" onclick="hideInput('<%= editorId %>')">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M18 6L6 18M6 6l12 12"/>
                </svg>
            </button>
        </div>
        <textarea id="<%= editorId %>-input"
                  class="compiler-textarea compiler-input"
                  placeholder="Enter input for your program..."></textarea>
    </div>

    <!-- Output Section -->
    <div class="compiler-output" id="<%= editorId %>-output-container">
        <div class="output-header">
            <div class="output-title">
                <span class="output-label">Output</span>
                <span class="output-status" id="<%= editorId %>-status"></span>
            </div>
            <div class="output-actions">
                <button class="output-btn" onclick="showInput('<%= editorId %>')" title="Add Input">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M4 17l6-6-6-6M12 19h8"/>
                    </svg>
                </button>
                <span class="output-stats" id="<%= editorId %>-stats"></span>
                <button class="output-btn" onclick="copyMultiOutput('<%= editorId %>')" title="Copy">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                    </svg>
                </button>
                <button class="output-btn" onclick="clearMultiOutput('<%= editorId %>')" title="Clear">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                    </svg>
                </button>
            </div>
        </div>
        <div class="output-body">
            <pre id="<%= editorId %>-output" class="output-content">
<span class="output-placeholder">Click <strong>Run</strong> to execute your code</span></pre>
        </div>
    </div>
</div>

<style>
.multifile-compiler {
    border: 1px solid var(--border-color, #e2e8f0);
    border-radius: var(--radius-lg, 12px);
    overflow: hidden;
    margin: var(--space-6, 1.5rem) 0;
    background: var(--bg-secondary, #f8fafc);
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

[data-theme="dark"] .multifile-compiler {
    background: #1e1e1e;
    border-color: #333;
}

.multifile-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0 var(--space-2, 0.5rem);
    background: var(--bg-tertiary, #f1f5f9);
    border-bottom: 1px solid var(--border-color, #e2e8f0);
    min-height: 44px;
}

[data-theme="dark"] .multifile-header {
    background: #252526;
    border-color: #333;
}

.file-tabs {
    display: flex;
    gap: 2px;
    overflow-x: auto;
    padding: 6px 0;
}

.file-tab {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 6px 12px;
    font-size: var(--text-sm, 0.875rem);
    font-weight: 500;
    color: var(--text-secondary, #64748b);
    background: transparent;
    border: none;
    border-radius: var(--radius-md, 8px);
    cursor: pointer;
    white-space: nowrap;
    transition: all 0.15s ease;
}

.file-tab:hover {
    background: var(--bg-hover, rgba(0,0,0,0.05));
}

.file-tab.active {
    background: var(--bg-primary, #fff);
    color: var(--text-primary, #1e293b);
    box-shadow: 0 1px 2px rgba(0,0,0,0.05);
}

[data-theme="dark"] .file-tab.active {
    background: #1e1e1e;
    color: #fff;
}

.file-tab.main::before {
    content: '';
    width: 6px;
    height: 6px;
    background: var(--accent-primary, #2563eb);
    border-radius: 50%;
}

.file-tab-close {
    padding: 2px;
    background: transparent;
    border: none;
    color: var(--text-muted, #94a3b8);
    cursor: pointer;
    border-radius: 4px;
    opacity: 0;
    transition: all 0.15s ease;
}

.file-tab:hover .file-tab-close {
    opacity: 1;
}

.file-tab-close:hover {
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
}

.file-tab-close svg {
    width: 12px;
    height: 12px;
}

.file-actions {
    display: flex;
    align-items: center;
    gap: var(--space-2, 0.5rem);
}

.file-action-btn {
    padding: 6px;
    background: transparent;
    border: none;
    color: var(--text-secondary, #64748b);
    cursor: pointer;
    border-radius: var(--radius-md, 8px);
    transition: all 0.15s ease;
}

.file-action-btn:hover {
    background: var(--bg-hover, rgba(0,0,0,0.05));
    color: var(--text-primary, #1e293b);
}

.file-action-btn svg {
    width: 16px;
    height: 16px;
}

.multifile-editor {
    display: flex;
    min-height: 200px;
    max-height: 400px;
}

.multifile-input-section {
    border-top: 1px solid var(--border-color, #e2e8f0);
}

.input-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 6px 12px;
    background: var(--bg-tertiary, #f1f5f9);
    font-size: var(--text-sm, 0.875rem);
    color: var(--text-secondary, #64748b);
}

[data-theme="dark"] .input-header {
    background: #252526;
}

.close-input-btn {
    padding: 4px;
    background: transparent;
    border: none;
    color: var(--text-muted, #94a3b8);
    cursor: pointer;
    border-radius: 4px;
}

.close-input-btn:hover {
    background: rgba(239, 68, 68, 0.2);
    color: #ef4444;
}

.close-input-btn svg {
    width: 14px;
    height: 14px;
}

/* Add File Modal */
.add-file-modal {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0,0,0,0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
}

.add-file-dialog {
    background: var(--bg-primary, #fff);
    padding: var(--space-6, 1.5rem);
    border-radius: var(--radius-lg, 12px);
    width: 100%;
    max-width: 400px;
    box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1);
}

[data-theme="dark"] .add-file-dialog {
    background: #1e1e1e;
    border: 1px solid #333;
}

.add-file-dialog h3 {
    margin: 0 0 var(--space-4, 1rem) 0;
    font-size: var(--text-lg, 1.125rem);
}

.add-file-dialog input {
    width: 100%;
    padding: 10px 12px;
    font-size: var(--text-sm, 0.875rem);
    border: 1px solid var(--border-color, #e2e8f0);
    border-radius: var(--radius-md, 8px);
    margin-bottom: var(--space-4, 1rem);
    background: var(--bg-primary, #fff);
    color: var(--text-primary, #1e293b);
}

[data-theme="dark"] .add-file-dialog input {
    background: #252526;
    border-color: #333;
    color: #d4d4d4;
}

.add-file-actions {
    display: flex;
    gap: var(--space-2, 0.5rem);
    justify-content: flex-end;
}
</style>

<script>
(function() {
    const editorId = '<%= editorId %>';
    const language = '<%= language %>';
    const initialFilesJson = '<%= filesJson.replace("'", "\\'").replace("\n", "\\n") %>';

    // State
    let files = [];
    let activeFileIndex = 0;

    // Parse initial files
    try {
        files = JSON.parse(initialFilesJson);
    } catch (e) {
        console.error('Failed to parse files JSON:', e);
        files = [{name: 'main.py', code: 'print("Hello")', main: true}];
    }

    // Initialize
    document.addEventListener('DOMContentLoaded', function() {
        renderTabs();
        loadFile(0);
        setupEditor();
    });

    function renderTabs() {
        const tabsContainer = document.getElementById(editorId + '-tabs');
        tabsContainer.innerHTML = files.map((file, index) => `
            <button class="file-tab ${index === activeFileIndex ? 'active' : ''} ${file.main ? 'main' : ''}"
                    onclick="selectFile('${editorId}', ${index})">
                ${file.name}
                ${files.length > 1 && !file.main ? `
                    <span class="file-tab-close" onclick="event.stopPropagation(); removeFile('${editorId}', ${index})">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M18 6L6 18M6 6l12 12"/>
                        </svg>
                    </span>
                ` : ''}
            </button>
        `).join('');
    }

    function loadFile(index) {
        activeFileIndex = index;
        const textarea = document.getElementById(editorId + '-code');
        textarea.value = files[index].code;
        updateLineNumbers();
        renderTabs();
    }

    function saveCurrentFile() {
        const textarea = document.getElementById(editorId + '-code');
        files[activeFileIndex].code = textarea.value;
    }

    function setupEditor() {
        const textarea = document.getElementById(editorId + '-code');
        textarea.addEventListener('input', function() {
            saveCurrentFile();
            updateLineNumbers();
        });
        textarea.addEventListener('scroll', syncScroll);
        textarea.addEventListener('keydown', function(e) {
            if (e.key === 'Tab') {
                e.preventDefault();
                const start = this.selectionStart;
                const end = this.selectionEnd;
                this.value = this.value.substring(0, start) + '    ' + this.value.substring(end);
                this.selectionStart = this.selectionEnd = start + 4;
                saveCurrentFile();
                updateLineNumbers();
            }
        });
    }

    function updateLineNumbers() {
        const textarea = document.getElementById(editorId + '-code');
        const lineNumbers = document.getElementById(editorId + '-line-numbers');
        const lines = textarea.value.split('\n').length;
        let html = '';
        for (let i = 1; i <= lines; i++) html += i + '\n';
        lineNumbers.textContent = html;
    }

    function syncScroll() {
        const textarea = document.getElementById(editorId + '-code');
        const lineNumbers = document.getElementById(editorId + '-line-numbers');
        lineNumbers.scrollTop = textarea.scrollTop;
    }

    // Global functions
    window.selectFile = function(id, index) {
        if (id !== editorId) return;
        saveCurrentFile();
        loadFile(index);
    };

    window.removeFile = function(id, index) {
        if (id !== editorId || files.length <= 1 || files[index].main) return;
        files.splice(index, 1);
        if (activeFileIndex >= files.length) activeFileIndex = files.length - 1;
        loadFile(activeFileIndex);
    };

    window.addFile = function(id) {
        if (id !== editorId) return;

        // Create modal
        const modal = document.createElement('div');
        modal.className = 'add-file-modal';
        modal.innerHTML = `
            <div class="add-file-dialog">
                <h3>Add New File</h3>
                <input type="text" id="${editorId}-new-filename"
                       placeholder="filename.${language === 'java' ? 'java' : language === 'go' ? 'go' : 'py'}"
                       autofocus>
                <div class="add-file-actions">
                    <button class="compiler-btn compiler-btn-ghost" onclick="closeAddFileModal('${editorId}')">Cancel</button>
                    <button class="compiler-btn compiler-btn-primary" onclick="confirmAddFile('${editorId}')">Add</button>
                </div>
            </div>
        `;
        document.body.appendChild(modal);

        const input = document.getElementById(editorId + '-new-filename');
        input.focus();
        input.addEventListener('keydown', function(e) {
            if (e.key === 'Enter') window.confirmAddFile(id);
            if (e.key === 'Escape') window.closeAddFileModal(id);
        });
    };

    window.closeAddFileModal = function(id) {
        const modal = document.querySelector('.add-file-modal');
        if (modal) modal.remove();
    };

    window.confirmAddFile = function(id) {
        if (id !== editorId) return;
        const input = document.getElementById(editorId + '-new-filename');
        const filename = input.value.trim();
        if (!filename) return;

        // Default content based on language
        let defaultCode = '';
        if (language === 'java') {
            const className = filename.replace('.java', '');
            defaultCode = `public class ${className} {\n    \n}`;
        } else if (language === 'go') {
            defaultCode = `package main\n\n`;
        } else {
            defaultCode = `# ${filename}\n`;
        }

        files.push({ name: filename, code: defaultCode, main: false });
        window.closeAddFileModal(id);
        loadFile(files.length - 1);
    };

    window.showInput = function(id) {
        if (id !== editorId) return;
        document.getElementById(editorId + '-input-section').style.display = 'block';
    };

    window.hideInput = function(id) {
        if (id !== editorId) return;
        document.getElementById(editorId + '-input-section').style.display = 'none';
    };

    window.runMultiCompiler = function(id) {
        if (id !== editorId) return;
        saveCurrentFile();

        const outputEl = document.getElementById(editorId + '-output');
        const statusEl = document.getElementById(editorId + '-status');
        const statsEl = document.getElementById(editorId + '-stats');
        const runBtn = document.getElementById(editorId + '-run-btn');
        const input = document.getElementById(editorId + '-input').value;

        // Loading state
        outputEl.innerHTML = '<span class="output-placeholder">Compiling & Running...</span>';
        statusEl.textContent = 'Running';
        statusEl.className = 'output-status running';
        statsEl.textContent = '';
        runBtn.disabled = true;
        runBtn.innerHTML = '<span class="spinner"></span><span>Running</span>';

        const startTime = performance.now();

        // Find main file
        const mainFile = files.find(f => f.main) || files[0];

        // For multi-file, we send all files
        const payload = {
            language: language,
            code: mainFile.code,
            input: input,
            files: files.map(f => ({ name: f.name, content: f.code }))
        };

        fetch('<%= request.getContextPath() %>/OneCompilerFunctionality?action=execute', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        })
        .then(response => response.json())
        .then(data => {
            const endTime = performance.now();
            const execTime = ((endTime - startTime) / 1000).toFixed(2);

            let output = '';
            let isError = false;

            if (data.stdout) output += data.stdout;
            if (data.stderr) {
                if (output) output += '\n';
                output += data.stderr;
                isError = true;
            }
            if (data.error) {
                if (output) output += '\n';
                output += 'Error: ' + data.error;
                isError = true;
            }
            if (!output && !isError) {
                output = 'Program completed with no output.';
            }

            outputEl.textContent = output;
            outputEl.className = 'output-content ' + (isError ? 'error' : 'success');
            statusEl.textContent = isError ? 'Error' : 'Success';
            statusEl.className = 'output-status ' + (isError ? 'error' : 'success');
            statsEl.textContent = execTime + 's';
        })
        .catch(err => {
            outputEl.textContent = 'Execution failed: ' + err.message;
            outputEl.className = 'output-content error';
            statusEl.textContent = 'Failed';
            statusEl.className = 'output-status error';
        })
        .finally(() => {
            runBtn.disabled = false;
            runBtn.innerHTML = '<svg class="play-icon" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg><span>Run</span>';
        });
    };

    window.resetMultiCompiler = function(id) {
        if (id !== editorId) return;
        try {
            files = JSON.parse(initialFilesJson);
        } catch (e) {
            files = [{name: 'main.py', code: 'print("Hello")', main: true}];
        }
        activeFileIndex = 0;
        loadFile(0);
        document.getElementById(editorId + '-input').value = '';
        document.getElementById(editorId + '-output').innerHTML = '<span class="output-placeholder">Click <strong>Run</strong> to execute your code</span>';
        document.getElementById(editorId + '-status').textContent = '';
        document.getElementById(editorId + '-stats').textContent = '';
    };

    window.copyMultiOutput = function(id) {
        if (id !== editorId) return;
        const output = document.getElementById(editorId + '-output').textContent;
        navigator.clipboard.writeText(output);
    };

    window.clearMultiOutput = function(id) {
        if (id !== editorId) return;
        document.getElementById(editorId + '-output').innerHTML = '<span class="output-placeholder">Output cleared</span>';
        document.getElementById(editorId + '-status').textContent = '';
        document.getElementById(editorId + '-stats').textContent = '';
    };
})();
</script>
