package z.y.x.cube.cube444;

/**
 * Standalone parity test for {@link HighLowEdges}.
 *
 *   javac -d /tmp/cube-classes \
 *       src/main/java/z/y/x/cube/core/*.java \
 *       src/main/java/z/y/x/cube/cube444/*.java
 *   java -cp /tmp/cube-classes:src/main/resources \
 *       z.y.x.cube.cube444.HighLowEdgesTest
 *
 * (The {@code src/main/resources} entry on the classpath is needed so
 * the {@code highlow-edge-values-444.tsv} resource is found.  Inside
 * the WAR this is automatic.)
 *
 * Compares Java-computed orientation strings against the Python
 * reference solver's {@code highlow_edges_state} output for several
 * fixed scrambles.  If the lookup table or the orient-edges-tuples
 * are off by even one entry, this test catches it instantly.
 */
public final class HighLowEdgesTest {

    private static int pass = 0, fail = 0;

    private static void check(String name, boolean ok, String detail) {
        if (ok) pass++;
        else {
            fail++;
            System.err.println("  FAIL: " + name);
            System.err.println("        " + detail);
        }
    }

    /** Fixed (state, orient) pairs generated by the Python reference for
     *  scrambles produced by the same LCG used in our JS scratch tests
     *  (seeds 1, 7, 42, 1729 with 30 random moves), plus the solved cube. */
    private static final String[][] CASES = {
        // seed=1 (30 random moves)
        { "UUDBUFRUBDFBLUFFDLRRFULDUDBFRLRUBBULBFLULUBLBLLFLDDDRUDFRBFDURDRFRLUDLBRFRRUFFBDDBBLBDLFLURRBFDR",
          "UDDUDUDDDDDUDDUDDDUUDUUDUUUUUUDDDUUDUDUUUDDDUDUU" },
        // seed=7
        { "LLFDURBBFFLUULRRDBRFUDULFBUUBBFUFBDFLRLFUURDURDRBDFDLDFDUFDLFBLBDRRLFFUDBBBBRRURLUFBDLRRLLDDLBRU",
          "UUDDDDDDDDUUDUUUDDUDUDUUDDDDDDUDUUDUDDUUUUUUUDUU" },
        // seed=42
        { "LDFDDDRBFULURUDUBRURRFRUDRDFFLLDFLLRRBBBLFDFBBRUUUBLLLUFDRFDDFUBFRDUDDFFFBLBLRBLFLBDRLBBUUUURLRB",
          "UUDDDDDUDDDDDUUDDUDDUUUUDDDUUUDDUUUDUDUUUUDDUDUU" },
        // seed=1729
        { "RDDRRLDDLUBBLRLFLUFULLFURRLRUDFBFDFUFDFBRLFDDUBBFLULBDDBUBRUUBFDBFDDBFBURUUFRLLRFFLDRURDBBRULLRB",
          "UDDUDUUUDDUUDUUUUUUDUDDDUUDUDDDDDUUUDDDUDDUDUDUD" },
        // solved cube
        { Cube444.SOLVED, "UDDUUDDUDUDUUDUDDUUDDUUDDUDUUDUDDUUDDUUDUDDUUDDU" },
    };

    public static void main(String[] args) {
        System.out.println("HighLowEdges resource entries loaded: " + HighLowEdges.loadedEntryCount());
        check("loaded 1152 orientation entries",
            HighLowEdges.loadedEntryCount() == 1152,
            "got " + HighLowEdges.loadedEntryCount());

        for (int i = 0; i < CASES.length; i++) {
            String state = CASES[i][0];
            String expected = CASES[i][1];
            String got = HighLowEdges.stateOf(state);
            check("case[" + i + "] orientation matches Python reference",
                expected.equals(got),
                "expected " + expected + "\n        got      " + got);
        }

        System.out.println();
        System.out.println(pass + " passed, " + fail + " failed");
        System.exit(fail == 0 ? 0 : 1);
    }

    private HighLowEdgesTest() {}
}
