#!/usr/bin/env bash
# Regenerate modern/css/tool-page-bundle.css from its 4 source files.
#
# WHY: rsafunctions.jsp (and any other tool page that opts in) links a single
# concatenated bundle instead of 4 separate <link> tags. That cuts 3 HTTP
# requests from the critical path, improving LCP.
#
# WHEN TO RUN: after editing any of the 4 source CSS files listed below.
#
# Generates TWO bundles:
#
# tool-page-bundle.css         — blocking, on critical path
#   1. design-system.css      → CSS variables + base resets
#   2. navigation.css         → top nav header
#   3. tool-page.css          → single-column tool layout
#   4. three-column-tool.css  → 3-column input | output | ads layout
#   5. search.css             → top-nav search input (above the fold)
#
# tool-page-deferred.css       — async via media="print" onload swap
#   1. ads.css                → ad container styles (containers are below the fold)
#   2. dark-mode.css          → [data-theme="dark"] overrides only
#   3. footer.css             → page footer (below the fold)
#
# Usage:
#   ./scripts/build-css-bundle.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CSS_DIR="${ROOT}/src/main/webapp/modern/css"

cd "${CSS_DIR}"

# ─── critical bundle (blocking) ─────────────────────────────────────────────
CRITICAL_OUT="${CSS_DIR}/tool-page-bundle.css"
CRITICAL_SOURCES=(
  "design-system.css"
  "navigation.css"
  "tool-page.css"
  "three-column-tool.css"
  "search.css"
)

# ─── deferred bundle (async, below-fold / conditional) ──────────────────────
DEFERRED_OUT="${CSS_DIR}/tool-page-deferred.css"
DEFERRED_SOURCES=(
  "ads.css"
  "dark-mode.css"
  "footer.css"
)

build_bundle() {
  local out="$1"
  local label="$2"
  shift 2
  local -a sources=("$@")

  # Sanity: every source must exist before we start writing.
  for f in "${sources[@]}"; do
    if [ ! -f "$f" ]; then
      echo "ERROR: missing source file: ${CSS_DIR}/${f}" >&2
      exit 1
    fi
  done

  {
    echo "/* ========================================================================"
    echo "   $(basename "$out") — ${label}"
    echo "   Generated by scripts/build-css-bundle.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    echo "   DO NOT EDIT BY HAND — your changes will be overwritten."
    echo "   Edit the source files in ${CSS_DIR}/, then re-run the script."
    echo "   ====================================================================== */"
    echo ""
    local total=${#sources[@]}
    local i=0
    for f in "${sources[@]}"; do
      i=$((i + 1))
      echo "/* === [${i}/${total}] ${f} === */"
      cat "$f"
      echo ""
    done
  } > "$out"

  local bundle_size
  bundle_size=$(wc -c < "$out")
  local sources_size=0
  for f in "${sources[@]}"; do
    sources_size=$((sources_size + $(wc -c < "$f")))
  done
  echo "✓ wrote ${out}"
  echo "  bundle: ${bundle_size} bytes  (sources: ${sources_size} bytes + headers)"
}

build_bundle "$CRITICAL_OUT" "critical CSS bundle (blocking, on critical path)" "${CRITICAL_SOURCES[@]}"
build_bundle "$DEFERRED_OUT" "deferred CSS bundle (async, below-fold / conditional)" "${DEFERRED_SOURCES[@]}"
