#!/usr/bin/env bash
# Regenerate modern/js/tool-page-bundle.js from its 5 source files.
#
# WHY: Pages that opt in (e.g. rsafunctions.jsp) link a single concatenated
# bundle instead of 5 separate <script> tags. Cuts 4 HTTP requests from the
# page load, improving INP/TBT.
#
# Sources are concatenated in dependency order:
#   1. tool-utils.js       → ToolUtils.* helpers used by others
#   2. dark-mode.js        → window.darkMode singleton (independent)
#   3. categories-menu.js  → getToolIcon, toggleCategorySection
#   4. recent-tools.js     → depends on getToolIcon from #3
#   5. search.js           → depends on ToolUtils + getToolIcon
#
# Each non-IIFE file is wrapped in a per-file IIFE at bundle time so their
# top-level `class`/`const`/`let`/`function` declarations don't leak into the
# shared global scope or collide with each other.
# Public APIs (window.X = ...) keep working because they explicitly assign
# to window from inside the IIFE.
#
# WHEN TO RUN: after editing any of the 5 source JS files listed above.
#
# Usage:
#   ./scripts/build-js-bundle.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JS_DIR="${ROOT}/src/main/webapp/modern/js"
OUT="${JS_DIR}/tool-page-bundle.js"

cd "${JS_DIR}"

SOURCES=(
  "tool-utils.js"
  "dark-mode.js"
  "categories-menu.js"
  "recent-tools.js"
  "search.js"
)

for f in "${SOURCES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: missing source file: ${JS_DIR}/${f}" >&2
    exit 1
  fi
done

{
  echo "/* ========================================================================"
  echo "   tool-page-bundle.js — concatenated tool-page JS"
  echo "   Generated by scripts/build-js-bundle.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "   DO NOT EDIT BY HAND — your changes will be overwritten."
  echo "   Edit the source files in ${JS_DIR}/, then re-run the script."
  echo "   ====================================================================== */"
  echo ""

  for i in "${!SOURCES[@]}"; do
    n=$((i + 1))
    f="${SOURCES[$i]}"
    echo ""
    echo "/* === [${n}/${#SOURCES[@]}] ${f} === */"
    # Wrap each file in its own IIFE so top-level declarations don't leak.
    # Files that are already IIFE-wrapped (tool-utils.js, search.js) just get
    # an extra harmless wrap; their public window.X assignments still work.
    echo ";(function(){"
    cat "$f"
    echo "})();"
  done
} > "$OUT"

BUNDLE_SIZE=$(wc -c < "$OUT")
SOURCES_SIZE=0
for f in "${SOURCES[@]}"; do
  SOURCES_SIZE=$((SOURCES_SIZE + $(wc -c < "$f")))
done

echo "✓ wrote ${OUT}"
echo "  bundle: ${BUNDLE_SIZE} bytes  (sources: ${SOURCES_SIZE} bytes + wrappers + headers)"
