<!DOCTYPE html>
<html>
<head>
    <title>Rule of 72 Calculator</title>
    <meta name="description" content="A simple calculator for estimating the number of years it will take to double your investment based on the Rule of 72 formula.">
    <meta name="keywords" content="rule of 72, calculator, investment, finance, interest rate">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>
    <script>
        function calculate() {
            var interestRate = document.getElementById("interest-rate").value;
            var years = Math.round(72 / interestRate * 100) / 100;
            var result = document.getElementById("result");
            result.innerHTML = "It will take approximately " + years + " years to double your investment at a " + interestRate + "% interest rate.";
        }
    </script>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {
            "@context" : "http://schema.org",
            "@type" : "WebPage",
            "name" : "Rule of 72 calculator",
            "image" : "https://8gwifi.org/images/site/72.png",
            "url" : "https://8gwifi.org/72.jsp",
            "author" : {
                "@type" : "Person",
                "name" : "Anish Nath"
            },
            "datePublished" : "2023-02-18",
            "applicationCategory" : [ "rule of 72, calculator", "investment, finance, interest rate calculator" ],
            "downloadUrl" : "https://8gwifi.org/images/site/72.png",
            "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,AWS",
            "requirements" : "Rule of 72 calculator  ",
            "softwareVersion" : "v1.0"
        }
    </script>

</head>
<%@ include file="body-script.jsp"%>
<h1>Rule of 72 Calculator</h1>
<img class="img-fluid rounded" src="images/site/72.png" height="200" width="200" alt="rule72 ">
<p>The Rule of 72 is a simple formula used to estimate the number of years it will take to double your investment at a given interest rate. To use the rule, simply divide 72 by the interest rate. For example, if the interest rate is 6%, it would take approximately 12 years to double your investment (72 / 6 = 12).</p>
<p class="formula">Years to Double = 72 / Interest Rate</p>
<form>
    <label for="interest-rate">Interest Rate:</label>
    <input type="number" id="interest-rate" name="interest-rate" value="2" step="0.01">
    <br><br>
    <button class="btn btn-primary" type="button" onclick="calculate()">Calculate</button>
</form>
<br>
<div id="result"></div>

<hr>

<%--<%@ include file="addcomments.jsp"%>--%>

</div>

<%@ include file="body-close.jsp"%>