<!DOCTYPE html>
<html>
<head>
	<title>base64 image encoder</title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="Online convert your images to base64 encoded , base64 image converter, data uri scheme converter">
	<meta name="keywords" content="convert your images to base64, base64 image converter, data uri scheme converter">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "base64 image encoder, convert your image to base64 format ",
  "image" : "https://8gwifi.org/images/site//base64image.png",
  "url" : "https://8gwifi.org/base64image.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-02-14",
  "applicationCategory" : [ "base64 convert image", "image base64 convert", "data uri scheme"],
  "downloadUrl" : "https://8gwifi.org/base64image.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "base64 image converter, data uri scheme converter ",
  "softwareVersion" : "v1.0"
}
</script>


</head>
<%@ include file="body-script.jsp"%>



<h1 class="mt-4">Convert Your Image to Base64</h1>
<p>Use this tool to generate the Data URI scheme for your images and directly embedd in the web html page</p>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>

<hr>


<div class="custom-file">
	<input type="file" class="custom-file-input" name="filetag" id="filetag">
	<label class="custom-file-label" for="customFile">Upload Your Image and get the base64 decoded</label>
</div>

<hr>
<div id="outputtext"></div>

<hr>
<img src="" class="img-fluid" id="preview">

<script type="text/javascript">

	var fileTag = document.getElementById("filetag");
	var	preview = document.getElementById("preview");

	fileTag.addEventListener("change", function() {
		changeImage(this);
	});

	function changeImage(input) {
		var reader;
		$('#outputtext').html('<img src="images/712.GIF"> loading...');
		if (input.files && input.files[0]) {
			reader = new FileReader();
			reader.readAsDataURL(input.files[0]);

			reader.onload = function(e) {
				$('#preview').empty();
				$('#outputtext').empty();



				preview.setAttribute('src', e.target.result);
				var binaryString = e.target.result
				//console.log(btoa(binaryString))
				var x = btoa(binaryString)
				var y = atob(x)
				console.log(y)
				$('#outputtext').append('<textarea readonly rows="20" class="form-control"><img src="'+y+'"></textarea>');
			}


		}
	}
</script>



<hr>
<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
	<div>
		<ul>
			<li><a href="UrlEncodeDecodeFunctions.jsp"><font size="2.5px">URL Encoders/Decoders</font></a></li>
			<li><a href="HexToStringFunctions.jsp"><font size="2.5px">Hex To String Conversion</font></a></li>
			<li><a href="HexToStringFunctions.jsp"><font size="2.5px">String To Hex Conversion</font></a></li>
			<li><a href="base64Hex.jsp"><font size="2.5px">Base64 To Hex (ViceVersa)</font></a></li>
			<li><a href="Base64Functions.jsp"><font size="2.5px">Base64 Encode/Decode</font></a></li>
			<li><a href="StringFunctions.jsp"><font size="2.5px">Various String Functions</font></a></li>
			<li><a href="contactus.jsp">Feature Request</a></li>
		</ul>
	</div>
</div>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>


<h3 class="code-line" data-line-start=0 data-line-end=1 ><a id="About_Data_URI_0"></a>About Data URI</h3>
<p class="has-line-data" data-line-start="2" data-line-end="3">The <strong>data URI scheme</strong> is a <a href="https://en.wikipedia.org/wiki/Uniform_resource_identifier" title="Uniform resource identifier">uniform resource identifier (URI)</a> scheme that provides a way to include data in-line in <a href="https://en.wikipedia.org/wiki/Web_page" title="Web page">Web pages</a> as if they were external resources. The format of this scheme is</p>
<pre><code class="has-line-data" data-line-start="5" data-line-end="7">data:[&lt;mediatype&gt;][;base64],&lt;data&gt;
</code></pre>
<p class="has-line-data" data-line-start="8" data-line-end="9">The <strong>mediatype</strong>  is an Internet media type specification (with optional parameters.) The <strong>";base64"</strong> means that the data  is encoded as <strong>base64</strong>. Without <strong>";base64",</strong> the data is represented using ASCII encoding for octets inside the range of safe URL characters and using the standard <strong>%xx</strong> hex encoding of URLs for octets outside that range.</p>
<p class="has-line-data" data-line-start="10" data-line-end="11">If &lt;mediatype&gt; is omitted, it defaults to <strong>text/plain;charset=US-ASCII</strong>.  As a shorthand,  <strong>"text/plain"</strong> can be omitted but the charset parameter supplied.</p>
<p class="has-line-data" data-line-start="12" data-line-end="13">Examples of data URIs s</p>
<pre><code class="has-line-data" data-line-start="15" data-line-end="23">data:application/octet-stream;base64,QQo=
data:application/x-gzip;base64,H4sIANG6Ml4AA
data:image/png;base64,iVBORw0K
data:text/plain;base64,SlBFUFZNNzBTUE
data:image/gif;base64,R0lGODlhsARZAv
.....
.....
</code></pre>
<h3 class="code-line" data-line-start=24 data-line-end=25 ><a id="How_to_display_Base64_images_in_HTML_24"></a>How to display Base64 images in HTML?</h3>
<p class="has-line-data" data-line-start="26" data-line-end="27">You can embed the <em>image</em> data directly into the document with data URIs. The end result will look like this</p>
<pre><code class="has-line-data" data-line-start="29" data-line-end="31">&lt;img src=&quot;data:image/png;base64, iVBORw0KGgo.....&quot; alt=&quot;Image Display using this scheme&quot; /
</code></pre>
<h3 class="code-line" data-line-start=32 data-line-end=33 ><a id="Advantages___DisAdvantages_32"></a>Advantages  &amp; DisAdvantages</h3>
<ul>
	<li class="has-line-data" data-line-start="34" data-line-end="35">Data URIs consume less bandwidth</li>
	<li class="has-line-data" data-line-start="35" data-line-end="36">If you have small static images and use this scheme to increase the page speed</li>
	<li class="has-line-data" data-line-start="36" data-line-end="37">Data URIs are not separately cached</li>
	<li class="has-line-data" data-line-start="37" data-line-end="39">Special Security consideration needed</li>
</ul>


<%@ include file="footer_adsense.jsp"%>


<%@ include file="addcomments.jsp"%>

</div class="row">

<%@ include file="body-close.jsp"%>