<!DOCTYPE html>
<html>
<head>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online generate rootCA/IntermediateCA server certificate",
  "image" : "https://8gwifi.org/images/site/genca.png",
  "url" : "https://8gwifi.org/cafunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2017-09-25",
  "applicationCategory" : [ "generate certificate online", "online Test rootCA/IntermediateCA", "Generate Test ca certificate authority"],
  "downloadUrl" : "https://8gwifi.org/cafunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "generate certificate online,what is an intermediate certificate,root certificate vs server certificate,openssl create ca and sign certificate,openssl create intermediate ca,trial certificate online,test ca certificate generate online, generate ca authority,create your own certificate authority,ssl certificate check,digicert ssl checker,openssl create ca and sign certificate,openssl create intermediate ca
 ",
  "softwareVersion" : "v1.0"
}
</script>
	<title>Online rootCA/IntermediateCA,Certs Generation </title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="Online generate rootCA/IntermediateCA server certificate, Generate Test ca certificate authority,Create your own certificate authority (for testing)">
	<meta name="keywords"
		  content="generate certificate online,what is an intermediate certificate,root certificate vs server certificate,openssl create ca and sign certificate,openssl create intermediate ca,trial certificate online,test ca certificate generate online, generate ca authority,create your own certificate authority,ssl certificate check,digicert ssl checker,openssl create ca and sign certificate,openssl create intermediate ca
 ">
	<%@ include file="header-script.jsp"%>

	<script type="text/javascript">
		$(document).ready(function() {

			$('#generateca').click(function (event)
			{
				//
				$('#form').delay(200).submit()

			});

			$('#form').submit(function (event)
			{
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type: "POST",
					url: "GenCAFunctionality", //this is my servlet
					// data: "lengthOfString=" +$('#lengthOfString').val()+"&trimignore="+$('#trimignore').val()+"&methodName="+$('#methodName').val(),
					data: $("#form").serialize(),
					success: function(msg){
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});
		});

	</script>
</head>

<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Generate your Certificate Authority (rootCA/intCA/Certificate)</h1>
<hr>

	<div id="loading" style="display: none;">
		<img src="images/712.GIF" alt="" />Loading!
	</div>



			<form id="form" method="POST">
				<input type="hidden" name="methodName" id="methodName"
					   value="GENERATE_TEST_CA">
						<B>Generate Test CA Certificate </B>

					Provide CN (Hostname)<input class="form-control animated" id="p_dns_name" type="text" name="p_dns_name"
												value="">
					<input type="button" class="btn btn-primary" id="generateca" name="generateca" value="Generate CA Authority">
					<div id="output"></div>


			</form>
<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

			<hr>

			<%@ include file="footer_adsense.jsp"%>

			<h2 class="mt-4" id="pki"><a href="docs/pki.jsp">Click here to know How PKI Works</a></h2>
			<p>This application currenlty supports the following Test CA Hierarchy</p>
			<p><img src="images/rootCA.png" alt="TestCA Authority" /></p>
			<p><strong>Certificate filename extensions</strong><br />There are several commonly used filename extensions for X.509 certificates.</p>
			<ol>
				<li><strong>.pem</strong> &ndash; (Privacy-enhanced Electronic Mail) Base64 encoded DER certificate, enclosed between "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----"</li>
				<li><strong>.cer, .crt, .der</strong> &ndash; usually in binary DER form</li>
				<li><strong>.p7b, .p7c</strong> &ndash; PKCS#7 SignedData structure without data, just certificate(s) or CRL(s)</li>
				<li><strong>.p12</strong> &ndash; PKCS#12, may contain certificate(s) (public) and private keys (password protected)</li>
				<li><strong>.pfx</strong> &ndash; PFX, predecessor of PKCS#12</li>
				<li><strong>PKCS#7</strong> is a standard for signing or encrypting</li>
				<li><strong>PKCS#12</strong> evolved from the personal information exchange (PFX) standard and is used to exchange public and private objects in a single file</li>
			</ol>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
