<!DOCTYPE html>
<html>
<head>
	<title>Online Cipher Algorithms, Encryption Decryption using aes,aes/cbc/nopadding,aes/cbc/pkcs5padding,aes/ecb/nopadding,aes/ecb/pkcs5padding,aes_128/cbc/nopadding,aes_128/cfb/nopadding,aes_128/ecb/nopadding,aes_128/gcm/nopadding,aes_128/ofb/nopadding,aes_192/cbc/nopadding,aes_192/cfb/nopadding,aes_192/ecb/nopadding,aes_192/gcm/nopadding,aes_192/ofb/nopadding,aes_256/cbc/nopadding,aes_256/cfb/nopadding,aes_256/ecb/nopadding,aes_256/gcm/nopadding,aes_256/ofb/nopadding,aria,blowfish,blowfish,camellia,cast5,cast6,chacha,des,des/cbc/nopadding,des/cbc/pkcs5padding,des/ecb/nopadding,des/ecb/pkcs5padding,desede,desede,desede/cbc/nopadding,desede/cbc/pkcs5padding,desede/ecb/nopadding,desede/ecb/pkcs5padding,gcm,gost28147,grain128,grainv1,hc128,hc256,idea,noekeon,pbe,rc2,rc5,rc6,rijndael,salsa20,seed,shacal-2,skipjack,sm4,serpent,shacal2,tea,threefish-1024,threefish-256,threefish-512,tnepres,twofish,vmpc,vmpc-ksa3,xtea</title>



	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Encrypt/Decrypt Message",
  "image" : "https://github.com/anishnath/crypto-tool/blob/master/encryption_decryption.png",
  "url" : "https://8gwifi.org/CipherFunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2017-09-25",
  "applicationCategory" : [ "AES", "DES", "DESede", "Blowfish", "Twofish", "IDEA", "Rijndael", "CAST5", "AES/CBC/PKCS5Padding", "AES/CBC/NoPadding", "AES/ECB/NoPadding", "AES/ECB/PKCS5Padding", "DES/CBC/NoPadding", "DES/CBC/PKCS5Padding", "DES/ECB/NoPadding", "DES/ECB/PKCS5Padding", "DESede/CBC/NoPadding", "DESede/CBC/PKCS5Padding", "DESede/ECB/NoPadding", "DESede/ECB/PKCS5Padding" ],
  "downloadUrl" : "https://8gwifi.org/CipherFunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "encode,encrypt,encryption,online encrypt,decode,decrypt online,decryption,AES,DES,DESede,AES/CBC/PKCS5Padding,AES/ECB/NoPadding,AES/ECB/PKCS5Padding,DES/CBC/NoPadding,DES/CBC/PKCS5Padding,DES/ECB/NoPadding,DES/ECB/PKCS5Padding,DESede/CBC/NoPadding,DESede/CBC/PKCS5Padding,DESede/ECB/NoPadding,DESede/ECB/PKCS5Padding,Blowfish,MARS,RC6,Rijndael,Serpent,Twofish,online encyption decryption,CAST5 online,aes/ecb/pkcs5padding online,des decryption online,aes decryption online base64,decrypt rsa private key online,aes/cbc/pkcs5padding decrypt online,aes/cbc/pkcs5padding online,aes/cbc/pkcs5padding decrypt,aes 128 ecb online,aes/ecb/nopadding",
  "softwareVersion" : "v1.0"
}
</script>

	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>


	<meta name="description"
		  content="Encryption Decryption using aes,aes/cbc/nopadding,aes/cbc/pkcs5padding,aes/ecb/nopadding,aes/ecb/pkcs5padding,aes_128/cbc/nopadding,aes_128/cfb/nopadding,aes_128/ecb/nopadding,aes_128/gcm/nopadding,aes_128/ofb/nopadding,aes_192/cbc/nopadding,aes_192/cfb/nopadding,aes_192/ecb/nopadding,aes_192/gcm/nopadding,aes_192/ofb/nopadding,aes_256/cbc/nopadding,aes_256/cfb/nopadding,aes_256/ecb/nopadding,aes_256/gcm/nopadding,aes_256/ofb/nopadding,aria,blowfish,blowfish,camellia,cast5,cast6,chacha,des,des/cbc/nopadding,des/cbc/pkcs5padding,des/ecb/nopadding,des/ecb/pkcs5padding,desede,desede,desede/cbc/nopadding,desede/cbc/pkcs5padding,desede/ecb/nopadding,desede/ecb/pkcs5padding,gcm,gost28147,grain128,grainv1,hc128,hc256,idea,noekeon,pbe,rc2,rc5,rc6,rijndael,salsa20,seed,shacal-2,skipjack,sm4,serpent,shacal2,tea,threefish-1024,threefish-256,threefish-512,tnepres,twofish,vmpc,vmpc-ksa3,xtea "/>
	<meta name="keywords"
		  content="encode,encrypt,encryption,online encrypt,decode,decrypt online,decryption,AES,DES,DESede,AES/CBC/PKCS5Padding,AES/ECB/NoPadding,AES/ECB/PKCS5Padding,DES/CBC/NoPadding,DES/CBC/PKCS5Padding,DES/ECB/NoPadding,DES/ECB/PKCS5Padding,DESede/CBC/NoPadding,DESede/CBC/PKCS5Padding,DESede/ECB/NoPadding,DESede/ECB/PKCS5Padding,Blowfish,MARS,RC6,Rijndael,Serpent,Twofish,online encyption decryption,CAST5 online,aes/ecb/pkcs5padding online,des decryption online,aes decryption online base64,decrypt rsa private key online,aes/cbc/pkcs5padding decrypt online,aes/cbc/pkcs5padding online,aes/cbc/pkcs5padding decrypt,aes 128 ecb online,aes/ecb/nopadding"/>


	<meta name="author" content="CRYPO" />
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

	<%@ include file="include_css.jsp"%>
	<script type="text/javascript">
		$(document).ready(function() {

			$('#cipherparameternew').change(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#plaintext').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#secretkey').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#encrypt').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#decrypt').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "CipherFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});
		});
	</script>
</head>
<body>
<div id="page">
	<%@ include file="include.jsp"%>
	<div id="loading" style="display: none;">
		<img src="images/712.GIF" alt="" />Loading!
	</div>

	<article id="contentWrapper" role="main">
		<section id="content">
			<form id="form" method="POST">
				<input type="hidden" name="methodName" id="methodName"
					   value="CIPHERBLOCK_NEW">
				<fieldset name="Cipher Functionality">
					<legend>
						<B>Encrypt/Decrypt Message </B>
					</legend>
					<table>
						<tr>
							<td>
								<b>Choose Cipher</b><select name="cipherparameternew" id="cipherparameternew">
								<option selected value="<%="AES/CBC/PKCS5PADDING"%>">AES/CBC/PKCS5PADDING</option>
								<%
									String[] validList = { "AES","AES/CBC/NOPADDING","AES/ECB/NOPADDING","AES/ECB/PKCS5PADDING","AES_128/CBC/NOPADDING","AES_128/CFB/NOPADDING","AES_128/ECB/NOPADDING","AES_128/GCM/NOPADDING","AES_128/OFB/NOPADDING","AES_192/CBC/NOPADDING","AES_192/CFB/NOPADDING","AES_192/ECB/NOPADDING","AES_192/GCM/NOPADDING","AES_192/OFB/NOPADDING","AES_256/CBC/NOPADDING","AES_256/CFB/NOPADDING","AES_256/ECB/NOPADDING","AES_256/GCM/NOPADDING","AES_256/OFB/NOPADDING","ARIA","BLOWFISH","CAMELLIA","CAST5","CAST6","CHACHA","DES","DES/CBC/NOPADDING","DES/CBC/PKCS5PADDING","DES/ECB/NOPADDING","DES/ECB/PKCS5PADDING","DESEDE","DESEDE/CBC/NOPADDING","DESEDE/CBC/PKCS5PADDING","DESEDE/ECB/NOPADDING","DESEDE/ECB/PKCS5PADDING","GCM","GOST28147","GRAIN128","GRAINV1","HC128","HC256","IDEA","NOEKEON","PBEWITHMD2ANDDES","PBEWITHMD5AND128BITAES-CBC-OPENSSL","PBEWITHMD5AND192BITAES-CBC-OPENSSL","PBEWITHMD5AND256BITAES-CBC-OPENSSL","PBEWITHMD5ANDDES","PBEWITHMD5ANDRC2","PBEWITHSHA1ANDDES","PBEWITHSHA1ANDRC2","PBEWITHSHA256AND128BITAES-CBC-BC","PBEWITHSHA256AND192BITAES-CBC-BC","PBEWITHSHA256AND256BITAES-CBC-BC","PBEWITHSHAAND128BITAES-CBC-BC","PBEWITHSHAAND128BITRC2-CBC","PBEWITHSHAAND128BITRC4","PBEWITHSHAAND192BITAES-CBC-BC","PBEWITHSHAAND2-KEYTRIPLEDES-CBC","PBEWITHSHAAND256BITAES-CBC-BC","PBEWITHSHAAND3-KEYTRIPLEDES-CBC","PBEWITHSHAAND40BITRC2-CBC","PBEWITHSHAAND40BITRC4","PBEWITHSHAANDIDEA-CBC","PBEWITHSHAANDTWOFISH-CBC","PBEWITHHMACSHA1ANDAES_128","PBEWITHHMACSHA1ANDAES_256","PBEWITHHMACSHA224ANDAES_128","PBEWITHHMACSHA224ANDAES_256","PBEWITHHMACSHA256ANDAES_128","PBEWITHHMACSHA256ANDAES_256","PBEWITHHMACSHA384ANDAES_128","PBEWITHHMACSHA384ANDAES_256","PBEWITHHMACSHA512ANDAES_128","PBEWITHHMACSHA512ANDAES_256","PBEWITHMD5ANDDES","PBEWITHMD5ANDTRIPLEDES","PBEWITHSHA1ANDDESEDE","PBEWITHSHA1ANDRC2_128","PBEWITHSHA1ANDRC2_40","PBEWITHSHA1ANDRC4_128","PBEWITHSHA1ANDRC4_40","RC2","RC5","RC6","RIJNDAEL","SALSA20","SEED","SHACAL-2","SKIPJACK","SM4","SERPENT","SHACAL2","TEA","THREEFISH-1024","THREEFISH-256","THREEFISH-512","TNEPRES","TWOFISH","VMPC","VMPC-KSA3","XTEA" };
									for (int i = 0; i < validList.length; i++) {
										String param = validList[i];
								%>
								<option value="<%=param%>"><%=param%></option>
								<%	} %>
							</select>
							</td>
						</tr>
						<tr>
							<td>
								<b>Type Something</b>
								<textarea rows="5" cols="30" name="plaintext" placeholder="Type Something here..." id="plaintext"></textarea>
							</td>
						</tr>
						<tr>
							<td colspan="2" rowspan="2">
								<b>SecretKey</b><input id="secretkey" type="text" name="secretkey"
													   size="40" placeholder="2b7e151628aed2a6abf71589"
													   value="2b7e151628aed2a6abf71589">
							</td>
						</tr>
						<tr>
							<td>
								<input checked="checked"
									   id="encrypt" type="radio" name="encryptorDecrypt" value="encrypt">Encrypt
							</td>
							<td>
								<input id="decrypt" type="radio" name="encryptorDecrypt"
									   value="decrypt">Decrypt
							</td>
						</tr>
					</table>
					<div id="output"></div>
				</fieldset>

			</form>
			<%@ include file="include_security_links.jsp"%>
			<%@ include file="footer.jsp"%>
			<table style="width: 776px; height: 6320px; float: left;" border="1"><caption>&nbsp;</caption>
				<tbody>
				<tr style="height: 108px;">
					<td style="width: 239px; height: 108px;">
						<p><strong>AES</strong></p>
					</td>
					<td style="width: 527px; height: 108px;">
						<p>Advanced Encryption Standard</p>
						<p>Key sizes&nbsp;&nbsp; 128, 192 or 256 bits</p>
						<p>Block sizes 128 bits</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10, 12 or 14</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in CBC Mode (Counter Block Mode ) PKCS5 Padding</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES/CBC/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in ECB Mode (Electronic Code Book Mode ) No Padding</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in ECB Mode (Electronic Code Book Mode ) No Padding</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES/ECB/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in ECB Mode (Electronic Code Book Mode ) PKCS5PADDING</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES_128/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in CBC Mode (Counter Block Mode ) No Padding, CBC requires Initial Vector</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES_128/CFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>AES 128 bit Encryption in CBC Mode (Cipher Feedback Mode ) No Padding, CBC requires Initial Vector</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_128/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_128/GCM/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>GCM Mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_128/OFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes Encryption in Output Feedback Mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_192/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 192 bit encryption in CBC Mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_192/CFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 192 bit encryption in CFB Mode</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>AES_192/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>Aes 192 bit encryption in ECB Mode, ECB Mode doesn&rsquo;t require any Initial Vector</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_192/GCM/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 192 bit encryption in GCM mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_192/OFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 192 bit encryption in ofb mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_256/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 256 bit encryption in cbc mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_256/CFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 256 bit encryption in CFB mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_256/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 256 bit encryption in ECB mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_256/GCM/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 256 bit encryption in GCM mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>AES_256/OFB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Aes 256 bit encryption in OFB mode</p>
					</td>
				</tr>
				<tr style="height: 110px;">
					<td style="width: 239px; height: 110px;">
						<p><strong>ARIA</strong></p>
					</td>
					<td style="width: 527px; height: 110px;">
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; AES</p>
						<p>Key sizes&nbsp;&nbsp; 128, 192, or 256 bits</p>
						<p>Block sizes 128 bits</p>
					</td>
				</tr>
				<tr style="height: 270px;">
					<td style="width: 239px; height: 270px;">
						<p><strong>BLOWFISH</strong></p>
					</td>
					<td style="width: 527px; height: 270px;">
						<p>Designers&nbsp;&nbsp; Bruce Schneier</p>
						<p>First published&nbsp;&nbsp; 1993</p>
						<p>Successors&nbsp; Twofish</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 32&ndash;448 bits</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 16</p>
					</td>
				</tr>
				<tr style="height: 302px;">
					<td style="width: 239px; height: 302px;">
						<p><strong>CAMELLIA</strong></p>
					</td>
					<td style="width: 527px; height: 302px;">
						<p>Designers&nbsp;&nbsp; Mitsubishi Electric, NTT</p>
						<p>First published&nbsp;&nbsp; 2000</p>
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; E2, MISTY1</p>
						<p>Certification&nbsp;&nbsp;&nbsp;&nbsp; CRYPTREC, NESSIE</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 128, 192 or 256 bits</p>
						<p>Block sizes 128 bits</p>
						<p>Structure&nbsp;&nbsp; Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 18 or 24</p>
					</td>
				</tr>
				<tr style="height: 270px;">
					<td style="width: 239px; height: 270px;">
						<p><strong>CAST5/ CAST6</strong></p>
					</td>
					<td style="width: 527px; height: 270px;">
						<p>Designers&nbsp;&nbsp; Carlisle Adams and Stafford Tavares</p>
						<p>First published&nbsp;&nbsp; 1996</p>
						<p>Successors&nbsp; CAST-256</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 40 to 128 bits</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 12 or 16</p>
					</td>
				</tr>
				<tr style="height: 302px;">
					<td style="width: 239px; height: 302px;">
						<p><strong>CHACHA</strong></p>
					</td>
					<td style="width: 527px; height: 302px;">
						<p>Designers&nbsp;&nbsp; Daniel J. Bernstein</p>
						<p>First published&nbsp;&nbsp; 2007</p>
						<p>Related to&nbsp; Rumba20, ChaCha</p>
						<p>Certification&nbsp;&nbsp;&nbsp;&nbsp; eSTREAM portfolio</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 256 bits</p>
						<p>State size&nbsp; 512 bits</p>
						<p>Structure&nbsp;&nbsp; ARX</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 20</p>
					</td>
				</tr>
				<tr style="height: 302px;">
					<td style="width: 239px; height: 302px;">
						<p><strong>DES</strong></p>
					</td>
					<td style="width: 527px; height: 302px;">
						<p>Designers&nbsp;&nbsp; IBM</p>
						<p>First published&nbsp;&nbsp; 1975</p>
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lucifer</p>
						<p>Successors&nbsp; Triple DES, G-DES, DES-X, LOKI89, ICE</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 56 bits (+8 parity bits)</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; Balanced Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 16</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DES/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DES/CBC/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DES/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DES/ECB/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 256px;">
					<td style="width: 239px; height: 256px;">
						<p><strong>DESEDE</strong></p>
					</td>
					<td style="width: 527px; height: 256px;">
						<p>First published&nbsp;&nbsp; 1998 (ANS X9.52)</p>
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DES</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 168, 112 or 56 bits (keying option 1, 2, 3 respectively)</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 48 DES-equivalent rounds</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DESEDE/CBC/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DESEDE/CBC/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DESEDE/ECB/NOPADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>DESEDE/ECB/PKCS5PADDING</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>GCM</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>Galois/Counter Mode</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>GOST28147</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>GRAIN128</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>GRAINV1</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>HC128</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>HC256</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 302px;">
					<td style="width: 239px; height: 302px;">
						<p><strong>IDEA</strong></p>
					</td>
					<td style="width: 527px; height: 302px;">
						<p>Designers&nbsp;&nbsp; Xuejia Lai and James Massey</p>
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PES</p>
						<p>Successors&nbsp; MMB, MESH, Akelarre,</p>
						<p>IDEA NXT (FOX)</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 128 bits</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; Lai-Massey scheme</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8.5</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>NOEKEON</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>PBEWITHSHA1ANDRC4_128</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>PBKDF1 and PBKDF2 (Password-Based Key Derivation Function 2)</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>PBEWITHSHA1ANDRC4_40</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>PBKDF1 and PBKDF2 (Password-Based Key Derivation Function 2)</p>
					</td>
				</tr>
				<tr style="height: 174px;">
					<td style="width: 239px; height: 174px;">
						<p><strong>RC2</strong></p>
					</td>
					<td style="width: 527px; height: 174px;">
						<p>Designers&nbsp;&nbsp; Ron Rivest (RSA Security) designed in 1987)</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 40&ndash;2048 bits</p>
						<p>State size&nbsp; 2064 bits (1684 effective)</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1</p>
					</td>
				</tr>
				<tr style="height: 270px;">
					<td style="width: 239px; height: 270px;">
						<p><strong>RC5</strong></p>
					</td>
					<td style="width: 527px; height: 270px;">
						<p>Designers&nbsp;&nbsp; Ron Rivest</p>
						<p>First published&nbsp;&nbsp; 1994</p>
						<p>Successors&nbsp; RC6, Akelarre</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 0 to 2040 bits (128 suggested)</p>
						<p>Block sizes 32, 64 or 128 bits (64 suggested)</p>
						<p>Structure&nbsp;&nbsp; Feistel-like network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1-255</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>RC6</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 64px;">
					<td style="width: 239px; height: 64px;">
						<p><strong>RIJNDAEL</strong></p>
					</td>
					<td style="width: 527px; height: 64px;">
						<p>The Advanced Encryption Standard (AES), also called Rijndael</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SALSA20</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SEED</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SHACAL-2</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 238px;">
					<td style="width: 239px; height: 238px;">
						<p><strong>SKIPJACK</strong></p>
					</td>
					<td style="width: 527px; height: 238px;">
						<p>Designers&nbsp;&nbsp; NSA</p>
						<p>First published&nbsp;&nbsp; 1998 (declassified)</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 80 bits</p>
						<p>Block sizes 64 bits</p>
						<p>Structure&nbsp;&nbsp; unbalanced Feistel network[1]</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 32</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SM4</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SERPENT</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>SHACAL2</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>TEA</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 306px;">
					<td style="width: 239px; height: 306px;">
						<p><strong>THREEFISH</strong></p>
					</td>
					<td style="width: 527px; height: 306px;">
						<p>Designers&nbsp;&nbsp; Bruce Schneier, Niels Ferguson, Stefan Lucks, Doug Whiting, Mihir Bellare, Tadayoshi Kohno, Jon Callas, Jesse Walker</p>
						<p>First published&nbsp;&nbsp; 2008</p>
						<p>Related to&nbsp; Blowfish, Twofish</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 256, 512 or 1024 bits</p>
						<p>(key size is equal to block size)</p>
						<p>Block sizes 256, 512 or 1024 bits</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 72 (80 for 1024-bit block size)</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>TNEPRES</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 334px;">
					<td style="width: 239px; height: 334px;">
						<p><strong>TWOFISH</strong></p>
					</td>
					<td style="width: 527px; height: 334px;">
						<p>Designers&nbsp;&nbsp; Bruce Schneier</p>
						<p>First published&nbsp;&nbsp; 1998</p>
						<p>Derived from&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Blowfish, SAFER, Square</p>
						<p>Related to&nbsp; Threefish</p>
						<p>Certification&nbsp;&nbsp;&nbsp;&nbsp; AES finalist</p>
						<p>Cipher detail</p>
						<p>Key sizes&nbsp;&nbsp; 128, 192 or 256 bits</p>
						<p>Block sizes 128 bits</p>
						<p>Structure&nbsp;&nbsp; Feistel network</p>
						<p>Rounds&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 16</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>VMPC</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>VMPC-KSA3</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				<tr style="height: 46px;">
					<td style="width: 239px; height: 46px;">
						<p><strong>XTEA</strong></p>
					</td>
					<td style="width: 527px; height: 46px;">
						<p>&nbsp;</p>
					</td>
				</tr>
				</tbody>
			</table>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p><strong>Cipher  modes</strong></p>
			<ul>
				<li>Electronic Code Book (ECB)</li>
				<li>Cipher Block Chaining (CBC)</li>
				<li>Cipher Feedback (CFB)</li>
				<li>Output Feedback (OFB)</li>
			</ul>
			<p><strong>Electronic Code Book</strong></p>
			<ul>
				<li>Native encryption mode</li>
				<li>Provides the recipe of substitutions and permutations that will be performed on the block of plaintext.</li>
				<li>Data within a file does not have to be encrypted in a certain order.</li>
				<li>Used for small amounts of data, like challenge-response, key management tasks.</li>
				<li>Also used to encrypt PINs in ATM machines.</li>
			</ul>
			<p><strong>Cipher Block Chaining</strong></p>
			<ul>
				<li>Each block of text, the key, and the value based on the previous block is processed in the algorithm and applied to the next block of text.</li>
			</ul>
			<p><strong>Cipher Feedback </strong></p>
			<ul>
				<li>The previously generated ciphertext from the last encrypted block of data is inputted into the algorithm to generate random values.</li>
				<li>These random values are processed with the current block of plaintext to create ciphertext.</li>
				<li>This mode is used when encrypting individual characters is required.</li>
			</ul>
			<p><strong>Output Feedback </strong></p>
			<ul>
				<li>Functioning like a stream cipher by generating a stream of random binary bits to be combined with the plaintext to create ciphertext.</li>
				<li>The ciphertext is fed back to the algorithm to form a portion of the next input to encrypt the next stream of bits<span style="font-size: 12.0pt; font-family: 'TimesNewRoman',serif;">.</span></li>
				<li><strong>DES has been broken with Internet network of PC&rsquo;s </strong></li>
			</ul>
			<p>DES is considered vulnerable by brute force search of the key &ndash; replaced by triple DES and AES&nbsp;</p>
			<p><strong>Triple DES</strong></p>
			<ul>
				<li>Double encryption is subject to meet in the middle attack</li>
				<li>Encrypt on one end decrypt on the other and compare the values</li>
				<li>So Triple DES is used</li>
				<li>Can be done several different ways:
					<ul>
						<li>DES &ndash; EDE2 (encrypt key 1, decrypt key 2, encrypt key 1)</li>
						<li>DES &ndash; EE2 (encrypt key 1, encrypt key 2, encrypt key 1)</li>
						<li>DES &ndash;EE3 (encrypt key 1, encrypt key 2, encrypt key 3) - most secure</li>
					</ul>
				</li>
				<li>Advanced Encryption Standard</li>
				<li>Block Cipher that will replace DES</li>
				<li>Anticipated that Triple DES will remain approved for Government Use</li>
				<li>AES announced by NIST in January 1997 to find replacement for DES</li>
			</ul>
			<p><strong>5 Finalists</strong></p>
			<ul>
				<li>MARS</li>
				<li>RC6</li>
				<li>Rijndael</li>
				<li>Serpent</li>
				<li>Blowfish</li>
			</ul>

		</section>
	</article>

</div>
</body>
</html>