<!DOCTYPE html>
<html>
<head>
	<title>Contach Us Page</title>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->


	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="contach us">
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>


</head>

<%@ include file="body-script.jsp"%>
<h1 class="mt-4">Contact Us/ Feature Request</h1>

<p>For feature request and other support reach out to me </p>

<p>   <a href="mailto:zarigatongy@gmail.com">Email Me</a>.<br>  </p>
<p>Twitter : @anish2good</p>


<p>Currently i'm the only mainter of this project, Apologizes for any delay </p>

<hr>


<%@ include file="thanks.jsp"%>

<hr>
<div class="sharethis-inline-share-buttons"></div>

<hr>


<%@ include file="footer_adsense.jsp"%>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>

