<!DOCTYPE html>
<html>
<head>
    <title>docker compose file generator</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="generate docker compose file online, docker-compose.yml file generate "/>
    <meta name="keywords" content="online docker compose file generate, docker compose generate, generate docker-compose file online"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>


    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "docker compose generator",
  "image" : "https://8gwifi.org/images/site/dc.png",
  "url" : "https://8gwifi.org/dc.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-02-26",
  "applicationCategory" : [ "docker compose yaml file" , "generate docker compose file", "docker-compose.yaml file generate online"],
  "downloadUrl" : "https://8gwifi.org/dc.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Generate docker compose file onliine ",
  "softwareVersion" : "v1.0"
}
</script>


    <script type="text/javascript">
        $(document).ready(function() {

            $('#generatedc').click(function (event)
            {
                //
                $('#form').delay(200).submit()

            });

            $('#form').submit(function (event)
            {
                //
                $('#output').html('<img src="images/712.GIF"> loading...');
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "DockerFunctionality", //this is my servlet

                    data: $("#form").serialize(),
                    success: function(msg){
                        $('#output').empty();
                        $('#output').append(msg);

                    }
                });
            });
        });

    </script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Generate Docker Compose YAML File</h1>
<p>This tool will help you to generate docker-compose.yaml using V3</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>

<%@ include file="footer_adsense.jsp"%>

<form id="form" method="POST">
    <input type="hidden" name="methodName" id="methodName" value="GENERATE_DC">

    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="serviceName">Service Name</label>
            <input type="text" class="form-control form-control-sm" name="serviceName" id="serviceName" placeholder="svcname">
        </div>
        <div class="form-group col-md-4">
            <label for="image">Docker Image</label>
            <input type="text" class="form-control form-control-sm" id="image" name="image" placeholder="nginx">
        </div>
        <div class="form-group col-md-4">
            <label for="container_name">container Name</label>
            <input type="text" class="form-control form-control-sm" id="container_name" name="container_name" placeholder="nginxc">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="entrypoint">Entrypoint</label>
            <input type="text" class="form-control form-control-lg" id="entrypoint" name="entrypoint" placeholder="/code/entrypoint.sh && ls -ltr">
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="expose">volumes</label>
            <input type="text" class="form-control form-control-lg" name="volumes" id="volumes" placeholder="db-data:/var/lib/data1,www-data:/var/lib/www">
            <small>To add multiple volume use "," as delimeter</small>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="environment">Environment</label>
            <input type="text" class="form-control form-control-lg" id="environment" name="environment" placeholder="NGINX_PORT=80,NGNIX_HOST=test">
            <small>Format env1=val1,env=val</small>
        </div>
        <div class="form-group col-md-6">
            <label for="labels">Labels </label>
            <input type="text" class="form-control form-control-lg" id="labels" name="labels" placeholder="app=stage,app1=db">
            <small>Format app=nginx,env=staging</small>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="expose">expose</label>
            <input type="text" class="form-control form-control-sm" name="expose" id="expose" placeholder="80,443">
        </div>
        <div class="form-group col-md-6">
            <label for="ports">ports</label>
            <input type="text" class="form-control form-control-sm" name="ports" id="ports" placeholder="8080,8443">
        </div>
    </div>


    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="user">user</label>
            <input type="text" class="form-control form-control-sm" name="user" id="user" placeholder="1000">
        </div>
        <div class="form-group col-md-3">
            <label for="image">working_dir</label>
            <input type="text" class="form-control form-control-sm" id="working_dir" name="working_dir" placeholder="/code">
        </div>
        <div class="form-group col-md-3">
            <label for="container_name">domainname</label>
            <input type="text" class="form-control form-control-sm" id="domainname" name="domainname" placeholder="nginx.8gwifi.org">
        </div>

        <div class="form-group col-md-3">
            <label for="container_name">hostname</label>
            <input type="text" class="form-control form-control-sm" id="hostname" name="hostname" placeholder="nginx-demo">
        </div>

    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="ipc">ipc</label>
            <input type="text" class="form-control form-control-sm" name="ipc" id="ipc" placeholder="host">
        </div>

        <div class="form-group col-md-4">
            <label for="mac_address">mac_address</label>
            <input type="text" class="form-control form-control-sm" name="mac_address" id="mac_address" placeholder="8a:ca:58:b9:e9:51">
        </div>

        <div class="form-group col-md-2">
            <label for="privileged">privileged</label>
            <select class="form-control" name="privileged" id="privileged">
                <option value="false" selected >false</option>
                <option value="true">true</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label for="restart_policy">restart_policy</label>
            <select class="form-control" name="restart_policy" id="restart_policy">
                <option value="any" selected >any</option>
                <option value="on-failure">on-failure</option>
                <option value="none">none</option>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="dns">dns</label>
            <input type="text" class="form-control form-control-sm" name="dns" id="dns" placeholder="8.8.8.8,9.9.9.9">
        </div>
        <div class="form-group col-md-3">
            <label for="dns_search">dns_search</label>
            <input type="text" class="form-control form-control-sm" id="dns_search" name="dns_search" placeholder="dc1.example.com,dc2.example.com">
        </div>
        <div class="form-group col-md-3">
            <label for="links">links</label>
            <input type="text" class="form-control form-control-sm" id="links" name="links" placeholder="db,redis,db:database">
            <small>Link to containers</small>
        </div>
        <div class="form-group col-md-3">
            <label for="depends_on">depends_on</label>
            <input type="text" class="form-control form-control-sm" id="depends_on" name="depends_on" placeholder="db,redis">
            <small>dependent services</small>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="dns">limits CPU</label>
            <input type="text" class="form-control form-control-sm" name="cpus" id="cpus" placeholder="0.50">
        </div>
        <div class="form-group col-md-3">
            <label for="dns_search">limits memory</label>
            <input type="text" class="form-control form-control-sm" id="memory" name="memory" placeholder="50M">
        </div>
        <div class="form-group col-md-3">
            <label for="links">reservations CPU</label>
            <input type="text" class="form-control form-control-sm" id="rcpus" name="rcpus" placeholder="0.25">
        </div>
        <div class="form-group col-md-3">
            <label for="rmemory">reservations Memory</label>
            <input type="text" class="form-control form-control-sm" id="rmemory" name="rmemory" placeholder="20M">
        </div>
    </div>


    <div class="form-row">
        <div class="form-group col-md-9">
            <label for="constraints">placement(constraints)</label>
            <input type="text" class="form-control" name="constraints" id="constraints" placeholder="node.role == manager">
        </div>

        <div class="form-group col-md-5">
            <input class="form-check-input" type="checkbox" value="healthcheck" name="healthcheck" id="healthcheck">
            <label for="healthcheck">Add HealthCheck</label>
        </div>


    </div>



    <input type="button" class="btn btn-primary" id="generatedc" name="Generate docker Compose" value="Generate docker-compose.yml">
</form>

<div id="output"></div>

<hr>
<p> Related Tool </p>

<ul>
    <li><a href="jwkfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) Generate</font> </a></li>
    <li><a href="jwkconvertfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) to PEM Convert</font> </a></li>
    <li><a href="jwsparse.jsp"><font size="2.5px">JWS Parser</font> </a></li>
    <li><a href="jwsgen.jsp"><font size="2.5px">JWS Generate Key Sign Data</font> </a></li>
    <li><a href="jwssign.jsp"><font size="2.5px">JWS Sign Data with custom key</font> </a></li>
    <li><a href="jwsverify.jsp"><font size="2.5px">JWS Signature Verification</font> </a></li>
</ul>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>
<hr>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>