<!DOCTYPE html>
<html>
<head>
    <title>Online compare text differences between two text files </title>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online compare text differences between two text files",
  "image" : "https://8gwifi.org/images/diff.png",
  "url" : "https://8gwifi.org/diff.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2019-12-11",
  "applicationCategory" : [ "Online compare text differences between two text files", "online diff tool", ],
  "downloadUrl" : "https://8gwifi.org/diff.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Online compare text differences between two text files",
  "softwareVersion" : "v1.0"
}
</script>

    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Online compare text differences between two text files">
    <meta name="keywords" content="Online compare text differences between two text files">
    <meta name="author" content="anish Nath" />
    <meta name="robots" content="index,follow" />
    <meta name="googlebot" content="index,follow" />
    <meta name="resource-type" content="document" />
    <meta name="classification" content="tools" />
    <meta name="language" content="en" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>
    <script SRC="js/diff_match_patch.js"></SCRIPT>


    <script>
        var dmp = new diff_match_patch();

        function launch() {
            var text1 = document.getElementById('text1').value;
            var text2 = document.getElementById('text2').value;
            dmp.Diff_Timeout = parseFloat(document.getElementById('timeout').value);
            dmp.Diff_EditCost = parseFloat(document.getElementById('editcost').value);

            var ms_start = (new Date()).getTime();
            var d = dmp.diff_main(text1, text2);
            var ms_end = (new Date()).getTime();

            if (document.getElementById('semantic').checked) {
                dmp.diff_cleanupSemantic(d);
            }
            if (document.getElementById('efficiency').checked) {
                dmp.diff_cleanupEfficiency(d);
            }
            var ds = dmp.diff_prettyHtml(d);
            document.getElementById('outputdiv').innerHTML = ds + '<BR>Time: ' + (ms_end - ms_start) / 1000 + 's';
        }
    </script>

</head>

<%@ include file="body-script.jsp"%>
<h1 class="mt-4">Online compare text differences between two text files</h1>



<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>

<form class="form-horizontal" id="form" action="#" >

    <div class="row">
        <div class="col">
            <label for="text1">Text Version#1</label>
            <textarea class="form-control" id="text1" rows="10">Hello</textarea>
        </div>
        <div class="col">
            <label for="text2">Text Version#2</label>
            <textarea class="form-control" id="text2" rows="10">hello demo</textarea>
        </div>
    </div>

    <div class="row">
        <label for="timeout" class="col-sm-2 col-form-label">Diff timeout (Seconds):</label>
        <div class="col-sm-10">
            <input type="text"  class="form-control" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" id="timeout" value="1">
        </div>
    </div>

    <div class="form-check">
        <input class="form-check-input" type="radio" name="cleanup" id="raw" value="option1" checked>
        <label class="form-check-label" for="raw">
            No Cleanup
        </label>
    </div>

    <div class="form-check">
        <input class="form-check-input" type="radio" checked name="cleanup" id="semantic" value="option1" checked>
        <label class="form-check-label" for="semantic">
            Semantic Cleanup
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="cleanup" id="efficiency" value="option2">
        <label class="form-check-label" for="efficiency">
            Efficiency Cleanup (COST)
        </label>

        <div class="col-sm-10">
            <input type="text"  class="form-control" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" id="editcost" value="1">
        </div>

    </div>

    <button type="button" onClick="launch()" VALUE="Compute Diff" class="btn btn-primary">Compute Diff</button>



</form>

<hr>


<div id="outputdiv"></div>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="footer_adsense.jsp"%>

<%@ include file="addcomments.jsp"%>

</div>



<%@ include file="body-close.jsp"%>

