<!DOCTYPE html>
<html>
<head>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "online hexdump generate for a file and text",
  "image" : "https://8gwifi.org/images/site/hexdump.jpg",
  "url" : "https://8gwifi.org/hexdump.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2019-12-17",
  "applicationCategory" : [ "online hexdump" , "generate hexdump for file" , "generate hexdump for text"],
  "downloadUrl" : "https://8gwifi.org/hexdump.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "online generate hexdump of file or a given text",
  "softwareVersion" : "v1.0"
}
</script>

    <title>online hexdump for file or text</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="online hexdump for file or text">
    <meta name="keywords" content="generate hexdump online, online hexdump for a file, hexdump for a text, hexdump online, hesdump generator">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>
    <script src="https://unpkg.com/@root/hexdump/dist/hexdump.min.js"></script>
    <script src="js/hexdump-min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            $('#inputtext').keyup(function (event)
            {
                $('#output').empty();

                var text = document.getElementById("inputtext").value;

                // console.log(text)

                var base = document.getElementById("form-base").value;
                var width = document.getElementById("form-width").value;
                var formSpacing = document.getElementById("form-spacing").value;

                $('#output').append(window.hexdump(asciiToUint8Array(text)));

                new Hexdump(text, {
                    container: 'hexdump'
                    , base: base
                    , width: width
                    , byteGrouping: formSpacing
                    , html: true
                    , lineNumber: true
                    , style: {
                        lineNumberLeft: ''
                        , lineNumberRight: ':'
                        , stringLeft: '|'
                        , stringRight: '|'
                        , hexLeft: ''
                        , hexRight: ''
                        , hexNull: '.g'
                        , stringNull: '.'
                    }
                })

            });



        });

    </script>

    <script>

        function asciiToUint8Array(str) {
            var chars = [];
            for (var i = 0; i < str.length; ++i)
                chars.push(str.charCodeAt(i));
            return new Uint8Array(chars);
        }

    </script>

</head>

<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Generate Hex Dump</h1>
<hr>


<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>


<form id="form" method="POST">

    <div id='form-row'>
        <div id='box'>
            <select name='width' id="form-base">
                <option selected>hexadecimal</option>
                <option>decimal</option>
                <option>binary</option>
            </select>
            Base Type
        </div>

        <div id='box'>
            <select name='width' id="form-width">
                <option selected>8</option>
                <option>16</option>
                <option>24</option>
                <option>32</option>
            </select>
            Width
        </div>

        <div id="box">
            <select name='width' id="form-spacing">
                <option>0</option>
                <option selected>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
            Byte Group
        </div>

        <!--                 <div id='box'>
                          <input type="checkbox" name="ascii" id="ascii" />
                          ASCII only
                        </div> -->
        <!--
                        <div id='box'>
                          <input type="checkbox" name="linenumbers" id="linenumbers" checked='true' />
                          Line Numbers
                        </div> -->
        <!--
                        <div id='box'>
                          <input type="checkbox" name="html" id="html" checked='true' />
                          HTML / Selecting Effects
                        </div> -->

    </div>


    <div class="form-group">
        <label for="inputtext">Input Message</label>
        <textarea class="form-control" id="inputtext" name="text" placeholder="Type your message here to generate Message Digest" rows="4"></textarea>
    </div>


    <hr>
    <code><pre class="form-control" id="hexdump"></pre></code>
    <hr>
    <pre  class="form-control" id="output"></pre>
</form>

<hr>
<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>


<hr>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
