<!DOCTYPE html>
<html>
<head>
<title>Online String to hex or Hex To String Conversion</title>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta name="description" content="Online String to Hex, Hex To String Conversion, Generate Hex String from the givn String, Generate String from the given Hex String, ascii,utf-8,utf-16,iso,window1252 ">
<meta name="keywords" content="String to Hex Conversion,expression hex bytes in string, convert hex with encoding schemes ">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

	<%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Convert String to Hex (Vice Versa)",
  "image" : "https://8gwifi.org/images/site/hex.png",
  "url" : "https://8gwifi.org/HexToStringFunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-12-06",
  "applicationCategory" : [ "String to hex","hex to string" ,"string to hex ascii" ," string to hex utf-8" , " string to hex utf-16", "string to hex ISO-8859-1" ,  ],
  "downloadUrl" : "https://8gwifi.org/HexToStringFunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
  "requirements" : "Online String to Hex, Hex To String Conversion, Generate Hex String from the givn String, Generate String from the given Hex String, ascii,utf-8,utf-16,iso,window1252",
  "softwareVersion" : "v1.0"
}
</script>

<script type="text/javascript">
        $(document).ready(function() {


        	  $('#delimiter1').click(function (event)
                      {
           			$('#form').delay(200).submit()
                      });

        	  $('#delimiter2').click(function (event)
                      {
           			$('#form').delay(200).submit()
                      });

         	  $('#delimiter').click(function (event)
                      {
           			$('#form').delay(200).submit()
                      });

			$('#inputtext').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});
           
            
            $('#form').submit(function (event)
                    {
                    //	
                  $('#outputtext1').html('<img height="20" width="20"  src="images/712.GIF"> loading...');
         			 event.preventDefault();
                        $.ajax({
                            type: "POST",
                            url: "StringFunctionality", //this is my servlet
                           data: $("#form").serialize(),
                            success: function(msg){    
                            	  $('#outputtext1').empty();
                            		    $('#outputtext').empty();
                                     $('#outputtext').append(msg);
                                     
                            }
                        }); 
                    });
        });
   
    </script>
</head>

<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Convert String to Hex (Vice Versa)</h1>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>

<hr>


	<div id="outputtext1"> </div>
	<form id="form" method="POST">
	<input type="hidden" name="methodName" id="methodName" value="CALCULATE_HEXSTRING">


		<div class="form-check form-check-inline">
			<input class="form-check-input" checked="checked" type="radio" id="encode" name="enCodeDecode" value="encode">
			<label class="form-check-label" for="encode">StringToHex
			</label>

		</div>




		<div class="form-check form-check-inline">
			<input type="radio" id="decode" name="enCodeDecode" value="decode">
			<label class="form-check-label" for="decode">HexToString</label>
		</div>

		<hr>

		<p>Delimiter to Output (For String to Hex )</p>
		<div class="form-check form-check-inline">
		<input  type="radio" id="delimiter" name="delimiter" value="">Nothing
		<input type="radio" id="delimiter1" name="delimiter" value=" ">SPACE
        <input checked="checked" type="radio" id="delimite2" name="delimiter" value=":">:(Colon)
		</div>
		<hr>


		<div class="form-group row">
			<label for="inputtext"  class="font-weight-bold col-sm-2 col-form-label">Input</label>
			<div class="col-sm-10">
				<textarea name="inputtext" class="form-control" id="inputtext" cols="2" rows="3" placeholder="Type Soemthing and submit"></textarea>
			</div>
		</div>


		<div class="form-group row">
			<label for="outputtext"  class="font-weight-bold col-sm-2 col-form-label">Output</label>
			<div class="col-sm-10">
		<textarea name="outputtext" class="form-control" id="outputtext" cols="2" rows="3" ></textarea>
			</div>
		</div>

		<hr>


		<p>Encoding/Decoding Scheme</p>

		<div class="form-check form-check-inline">
			<input class="form-control" checked="checked" type="radio" id="encoding" name="encoding" value="ASCII">
			<label class="form-check-label" for="encoding">ASCII
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding1" name="encoding" value="UTF-8">
			<label class="form-check-label" for="encoding1">UTF-8
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding2" name="encoding" value="UTF-16">
			<label class="form-check-label" for="encoding2">UTF-16
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding4" name="encoding" value="ISO-8859-1">
			<label class="form-check-label" for="encoding4">ISO-8859-1
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding5" name="encoding" value="ISO-8859-2">
			<label class="form-check-label" for="encoding5">ISO-8859-2
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding6" name="encoding" value="ISO-8859-6">
			<label class="form-check-label" for="encoding6">ISO-8859-6
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding7" name="encoding" value="ISO-8859-15">
			<label class="form-check-label" for="encoding7">ISO-8859-15
			</label>
		</div>

		<div class="form-check form-check-inline">
			<input type="radio" id="encoding8" name="encoding" value="Windows-1252">
			<label class="form-check-label" for="encoding8">Windows-1252
			</label>
		</div>


		<div>
		<input  class="btn btn-primary" type="submit" name="convert" id="convert" value="Start Converting">
			</div>

	</form>

<hr>
<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
	<div>
		<ul>
			<li><a href="UrlEncodeDecodeFunctions.jsp"><font size="2.5px">URL Encoders/Decoders</font></a></li>
			<li><a href="HexToStringFunctions.jsp"><font size="2.5px">Hex To String Conversion</font></a></li>
			<li><a href="HexToStringFunctions.jsp"><font size="2.5px">String To Hex Conversion</font></a></li>
			<li><a href="base64Hex.jsp"><font size="2.5px">Base64 To Hex (ViceVersa)</font></a></li>
			<li><a href="Base64Functions.jsp"><font size="2.5px">Base64 Encode/Decode</font></a></li>
			<li><a href="StringFunctions.jsp"><font size="2.5px">Various String Functions</font></a></li>
			<li><a href="contactus.jsp">Feature Request</a></li>
		</ul>
	</div>
</div>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>




<%@ include file="footer_adsense.jsp"%>


<%@ include file="addcomments.jsp"%>

</div class="row">

<%@ include file="body-close.jsp"%>

