<%@ page import="z.y.x.Security.RSAUtil" %>
<%@ page import="java.security.KeyPair" %>
<!DOCTYPE html>
<html>
<head>


	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "jwk to pem convertor, pem to jwk convert online, jwk openssl format pem",
  "image" : "https://8gwifi.org/docs/jwkconvert.png",
  "url" : "https://8gwifi.org/jwkconvertfunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "applicationCategory" : [ "jwk", "openssl", "pem" , "jwt"].
  "datePublished" : "2018-09-28",
  "downloadUrl" : "https://8gwifi.org/jwkfunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
  "requirements" : "jwk to pem convertor, pem to jwk convert online, jwk openssl format pem",
  "softwareVersion" : "v1.0"
}
</script>

	<title>jwk to pem convertor, pem to jwk convert online, jwk openssl format pem </title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>

	<meta name="keywords" content="jwk key to pem convert online, pem to jwk key convert " />
	<meta name="description" content="online jwk to pem online, pem to jwk online" />

	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>



	<script type="text/javascript">
		$(document).ready(function() {


			$('#submit').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "JWKFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);


					}
				});
			});

		});
	</script>
</head>


<%@ include file="body-script.jsp"%>

<h1 class="mt-4">JWK to PEM Convertor online</h1>
<hr>


<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>

</fieldset>


<form id="form" class="form-horizontal" method="POST">
	<input type="hidden" name="methodName" id="methodName"
		   value="CONVERT_JWK">


	<p><strong>Convert JWK to pem format, pem to JWK online </strong> </p>

	<div class="form-check">
		<input class="form-check-input" checked="checked" type="radio" name="param" id="JWK-to-PEM" value="JWK-to-PEM" >
		<label class=" form-check-label" for="JWK-to-PEM">
			JWK-to-PEM (RSA and EC Supported)
		</label>
	</div>

	<div class="form-check">
		<input class="form-check-input"  type="radio" name="param" id="PEM-to-JWK" value="PEM-to-JWK" >
		<label class="form-check-label" for="PEM-to-JWK">
			PEM-to-JWK (RSA Only)
		</label>
	</div>

	<div class="form-group">
		<label for="input">Input</label>
		<textarea class="form-control" id="input" name="input" rows="7">{
"kty": "RSA",
"n": "33TqqLR3eeUmDtHS89qF3p4MP7Wfqt2Zjj3lZjLjjCGDvwr9cJNlNDiuKboODgUiT4ZdPWbOiMAfDcDzlOxA04DDnEFGAf-kDQiNSe2ZtqC7bnIc8-KSG_qOGQIVaay4Ucr6ovDkykO5Hxn7OU7sJp9TP9H0JH8zMQA6YzijYH9LsupTerrY3U6zyihVEDXXOv08vBHk50BMFJbE9iwFwnxCsU5-UZUZYw87Uu0n4LPFS9BT8tUIvAfnRXIEWCha3KbFWmdZQZlyrFw0buUEf0YN3_Q0auBkdbDR_ES2PbgKTJdkjc_rEeM0TxvOUf7HuUNOhrtAVEN1D5uuxE1WSw",
"e": "AQAB",
"d": "DjU54mYvHpICXHjc5-JiFqiH8NkUgOG8LL4kwt3DeBp9bP0-5hSJH8vmzwJkeGG9L79EWG4b_bfxgYdeNX7cFFagmWPRFrlxbd64VRYFawZHRJt-2cbzMVI6DL8EK4bu5Ux5qTiV44Jw19hoD9nDzCTfPzSTSGrKD3iLPdnREYaIGDVxcjBv3Tx6rrv3Z2lhHHKhEHb0RRjATcjAVKV9NZhMajJ4l9pqJ3A4IQrCBl95ux6Xm1oXP0i6aR78cjchsCpcMXdP3WMsvHgTlsZT0RZLFHrvkiNHlPiil4G2_eHkwvT__CrcbO6SmI_zCtMmypuHJqcr-Xb7GPJoa64WoQ",
"p": "8K33pX90XX6PZGiv26wZm7tfvqlqWFT03nUMvOAytqdxhO2HysiPn4W58OaJd1tY4372Qpiv6enmUeI4MidCie-s-d0_B6A0xfhU5EeeaDN0xDOOl8yN-kaaVj9b4HDR3c91OAwKpDJQIeJVZtxoijxl-SRx3u7Vs_7meeSpOfE",
"q": "7a5KnUs1pTo72A-JquJvIz4Eu794Yh3ftTk_Et-83aE_FVc6Nk-EhfnwYSNpVmM6UKdrAoy5gsCvZPxrq-eR9pEwU8M5UOlki03vWY_nqDBpJSIqwPvGHUB16zvggsPQUyQBfnN3N8XlDi12n88ltvWwEhn1LQOwMUALEfka9_s",
"dp": "DB9nGuHplY_7Xv5a5UCs5YgxkWPtJFfbIZ1Zr-XHCCY09JIWReOGQG226OhjwixKtOK_OqmAKtMKM9OmKviJRHNbDhbTxumN3u7cL8dftjXpSryiEQlPmWyW94MneI2WNIrvh4wruQuDt8EztgOiDFxwcnUgey8iend7WmZnE7E",
"dq": "O-bSTUQ4N_UuQezgkF3TDrnBraO67leDGwRbfiE_U0ghQvqh5DA0QSPVzlWDZc9KUitvj8vxsR9o1PW9GS0an17GJEYuetLnkShKK3NWOhBBX6d1yP9rVdH6JhgIJEy_g0Suz7TAFiFc8i7JF8u4QJ05C8bZAMhOLotqftQeVOM",
"qi": "InfGmkb2jNkPGuNiZ-mU0-ZrOgLza_fLL9ErZ35jUPhGFzdGxJNobklvsNoTd-E2GAU41YkJh24bncMLvJVYxHHA5iF7FBWx1SvpEyKVhhnIcuXGD7N5PbNZzEdmr9C6I7cPVkWO-sUV7zfFukexIcANmsd_oBBGKRoYzP5Tti4"
}</textarea>
	</div>



	<div id="output"></div>


	<input type="button" class="btn btn-primary" value="submit" id="submit" name="Generate JSON Web Keys">

	<br>



</form>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<h1><a id="Generate_a_JSON_Web_Key_JWK_0"></a>Generate a JSON Web Key (JWK)</h1>
<p>A JSON object that represents a cryptographic key.  The members of the object represent properties of the key, including its value.</p>
<p><strong>Example JWK</strong></p>
<pre><code>{
      &quot;kty&quot;:&quot;EC&quot;,
      &quot;crv&quot;:&quot;P-256&quot;,
      &quot;x&quot;:&quot;f83OJ3D2xF1Bg8vub9tLe1gHMzV76e8Tus9uPHvRVEU&quot;,
      &quot;y&quot;:&quot;x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0&quot;,
      &quot;kid&quot;:&quot;Id that can be uniquely Identified&quot;
  }
</code></pre>
<p>The <strong>kty</strong> (key type) parameter identifies the cryptographic algorithm  family used with the key, such as <strong>RSA</strong> or <strong>EC</strong></p>
<ul>
	<li><strong>RSA</strong> keys, prefred key Size 2048,4096, used for signature and encryption</li>
	<li><strong>Elliptic curve keys</strong>: EC keys and EC operations with the following designations:
		<ul>
			<li><strong>P-256</strong>  a.k.a secp256r1 (<strong>NIST</strong>) or prime256v1 (<strong>ANSI X9.62</strong>)</li>
			<li><strong>P-384</strong>  a.k.a secp384r1  (NIST)</li>
			<li><strong>P-521</strong> a.k.a  secp521r1  (NIST)</li>
		</ul>
	</li>
	<li><strong>Octet Key Pair</strong> : Octet key pairs are used to represent Edwards curve keys. They bear the JWK type designation “OKP” and are used for JSON Web Signatures (JWS) with Ed25519 / Ed448 and JSON Web Encryption (JWE) with ECDH with X25519 / X448</li>
	<li><strong>Octet Sequence keys</strong> : The octet sequence JWK format is intended for representing secret keys, such as keys for use in HMAC and AES
		<ul>
			<li><strong>HS256</strong> : indicates that this token is signed using HMAC-SHA256</li>
			<li><strong>HS384</strong></li>
			<li><strong>HS512</strong></li>
			<li>AES Keys</li>
		</ul>
	</li>
</ul>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>