<!DOCTYPE html>
<html>
<head>
    <title>Online JWS key generator</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Generate JWS key using alogrithms HS256,H354,H512,RS256,RS512,RS384,PS256,PS356,PS512,ES256,ES384,ES512 "/>
    <meta name="keywords" content="online jws key generator, jws mac key, jws rsa key generator, jws ec key generator"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>


    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "online jws key generator, jws mac key, jws rsa key generator, jws ec key generator",
  "image" : "https://8gwifi.org/images/site/jwsgen.png",
  "url" : "https://8gwifi.org/jwsgen.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-01-24",
  "applicationCategory" : [ "online jws generate" , "generate jws online", "jws online" , "jws signature" , "jws rsa key" , "jws mac key"],
  "downloadUrl" : "https://8gwifi.org/jwsgen.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Generate JWS key, sign payload using alogrithms HS256,H354,H512,RS256,RS512,RS384,PS256,PS356,PS512,ES256,ES384,ES512 ",
  "softwareVersion" : "v1.0"
}
</script>


    <script type="text/javascript">
        $(document).ready(function() {
            $('#HS256').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#payload').keyup(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#HS384').click(function (event)
            {
                $('#form').delay(200).submit()
            });
            $('#HS512').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#RS256').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#RS384').click(function (event)
            {
                $('#form').delay(200).submit()
            });
            $('#RS512').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#PS256').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#PS384').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#PS512').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#ES256').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#ES384').click(function (event)
            {
                $('#form').delay(200).submit()
            });

            $('#ES512').click(function (event)
            {
                $('#form').delay(200).submit()
            });
            $('#form').submit(function (event)
            {
                //
                $('#output').html('<img src="images/712.GIF"> loading...');
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "JWSFunctionality", //this is my servlet

                    data: $("#form").serialize(),
                    success: function(msg){
                        $('#output').empty();
                        $('#output').append(msg);

                    }
                });
            });
        });

    </script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Generate JWS key and Sign Payload</h1>
<p>This tool will help you to signed the payload and generate the serialiazed JWS Key using Algorithms HMAC,RSA and EC</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>



<form id="form" method="POST">
    <input type="hidden" name="methodName" id="methodName" value="GENERATE_JSONKEY">


    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-2 pt-0">JWS Algo</legend>

            <div class="col-sm-10">

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="HS256" value="HS256">
                    <label class="form-check-label" for="HS256">HS256</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="HS384" value="HS384">
                    <label class="form-check-label" for="HS384">HS384</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="HS512" value="HS512">
                    <label class="form-check-label" for="HS512">HS512</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="RS256" value="RS256">
                    <label class="form-check-label" for="RS256">RS256</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="RS384" value="RS384">
                    <label class="form-check-label" for="RS384">RS384</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="RS512" value="RS512">
                    <label class="form-check-label" for="RS512">RS512</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="PS256" value="PS256">
                    <label class="form-check-label" for="PS256">PS256</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="PS384" value="PS384">
                    <label class="form-check-label" for="PS384">PS384</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="PS512" value="PS512">
                    <label class="form-check-label" for="PS512">PS512</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="ES256" value="ES256">
                    <label class="form-check-label" for="ES256">ES256</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="ES384" value="ES384">
                    <label class="form-check-label" for="ES256">ES384</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="algo" id="ES512" value="ES512">
                    <label class="form-check-label" for="ES512">ES512</label>
                </div>
            </div>
            <div class="col-sm-10">
                <label for="payload">Payload</label>
    <textarea class="form-control" name="payload" id="payload" rows="5">{
  "sub": "1234567890",
  "name": "Anish Nath",
  "iat": 1516239022
}</textarea>
            </div>

            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Generate JWS Keys</button>
            </div>

        </div>

    </fieldset>


</form>

<div id="output"></div>

<hr>

<ul>
    <li><a href="jwkfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) Generate</font> </a></li>
    <li><a href="jwkconvertfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) to PEM Convert</font> </a></li>
    <li><a href="jwsparse.jsp"><font size="2.5px">JWS Parser</font> </a></li>
    <li><a href="jwsgen.jsp"><font size="2.5px">JWS Generate Key Sign Data</font> </a></li>
    <li><a href="jwssign.jsp"><font size="2.5px">JWS Sign Data with custom key</font> </a></li>
</ul>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>
<hr>
<h3 class="code-line" data-line-start=0 data-line-end=1 ><a id="JWS_0"></a>JWS</h3>

<p class="has-line-data" data-line-start="1" data-line-end="2">JSON Web Signature (JWS) represents content secured with <strong>digital signatures</strong> or Message Authentication Codes (MACs) using JSON based data structures</p>
<p class="has-line-data" data-line-start="3" data-line-end="4"><strong>JWS HMAC Algo</strong></p>
<ul>
    <li class="has-line-data" data-line-start="5" data-line-end="6">HS256 - HMAC with SHA-256, requires 256+ bit secret</li>
    <li class="has-line-data" data-line-start="6" data-line-end="7">HS384 - HMAC with SHA-384, requires 384+ bit secret</li>
    <li class="has-line-data" data-line-start="7" data-line-end="9">HS512 - HMAC with SHA-512, requires 512+ bit secret</li>
</ul>
<p class="has-line-data" data-line-start="9" data-line-end="10"><strong>JWS RSA Algo</strong></p>
<ul>
    <li class="has-line-data" data-line-start="11" data-line-end="12">RS256 - RSA PKCS#1 signature with SHA-256</li>
    <li class="has-line-data" data-line-start="12" data-line-end="13">RS384 - RSA PKCS#1 signature with SHA-384</li>
    <li class="has-line-data" data-line-start="13" data-line-end="14">RS512 - RSA PKCS#1 signature with SHA-512</li>
    <li class="has-line-data" data-line-start="14" data-line-end="15">PS256 - RSA PSS signature with SHA-256</li>
    <li class="has-line-data" data-line-start="15" data-line-end="16">PS384 - RSA PSS signature with SHA-384</li>
    <li class="has-line-data" data-line-start="16" data-line-end="18">PS512 - RSA PSS signature with SHA-512</li>
</ul>
<p class="has-line-data" data-line-start="18" data-line-end="19"><strong>JWS Elliptic Curve (EC) Algo</strong></p>
<ul>
    <li class="has-line-data" data-line-start="20" data-line-end="21">ES256 - EC P-256 DSA with SHA-256</li>
    <li class="has-line-data" data-line-start="21" data-line-end="22">ES384 - EC P-384 DSA with SHA-384</li>
    <li class="has-line-data" data-line-start="22" data-line-end="23">ES512 - EC P-521 DSA with SHA-512</li>
</ul>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>