<!DOCTYPE html>
<html>
<head>
    <title>Online JWS JSON Parser</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="JWS JSON parser online "/>
    <meta name="keywords" content="online jws parser, decode the JWS object, online jws decoder, jws payload, jws serialization, JWS tutorial"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>


    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online JWS JSON Parser, Decode the JWSObject",
  "image" : "https://8gwifi.org/images/site/jwsparse.png",
  "url" : "https://8gwifi.org/jwsparse.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-01-24",
  "applicationCategory" : [ "online jws parser" , "jws json decoder", "jws online" , "jws signature" , "jws rsa key" , "jws mac key" ,"jws tutorial"],
  "downloadUrl" : "https://8gwifi.org/jwsparse.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Parse jws json object ",
  "softwareVersion" : "v1.0"
}
</script>


    <script type="text/javascript">
        $(document).ready(function() {


            $('#serialized').keyup(function (event)
            {
                $('#form').delay(200).submit()
            });


            $('#form').submit(function (event)
            {
                //
                $('#output').html('<img src="images/712.GIF"> loading...');
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "JWSFunctionality", //this is my servlet

                    data: $("#form").serialize(),
                    success: function(msg){
                        $('#output').empty();
                        $('#output').append(msg);

                    }
                });
            });
        });

    </script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Parse JWS </h1>
<p>This tool will help you to Parse JWS Object and determine the JWS Header, Payload and Signature</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>



<form id="form" method="POST">
    <input type="hidden" name="methodName" id="methodName" value="PARSE_JWS">


    <fieldset class="form-group">
        <div class="row">

            <div class="col-sm-10">
                <label for="serialized">JWS Serialzied Object</label>
    <textarea class="form-control" name="serialized" id="serialized" rows="5">eyJhbGciOiJIUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.9tFLrurxXWKBDh317ly24fP03We-uzSZtPf7Yqy_oSw</textarea>
            </div>

            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Parse JWS</button>
            </div>

        </div>

    </fieldset>


</form>

<div id="output"></div>


<hr>

<ul>
<li><a href="jwkfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) Generate</font> </a></li>
<li><a href="jwkconvertfunctions.jsp"><font size="2.5px">JSON Web Key (JWK) to PEM Convert</font> </a></li>
<li><a href="jwsparse.jsp"><font size="2.5px">JWS Parser</font> </a></li>
<li><a href="jwsgen.jsp"><font size="2.5px">JWS Generate Key Sign Data</font> </a></li>
<li><a href="jwssign.jsp"><font size="2.5px">JWS Sign Data with custom key</font> </a></li>
</ul>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>
<hr>
<h2 class="code-line" data-line-start=0 data-line-end=1 ><a id="JWS_JSON_Serialization_Overview_0"></a>JWS JSON Serialization Overview</h2>
<p class="has-line-data" data-line-start="1" data-line-end="2">A JWS is represented as the concatenation of</p>
<p class="has-line-data" data-line-start="3" data-line-end="6"><code>BASE64URL(UTF8(JWS Protected Header)) || '.' ||</code><br>
    <code>BASE64URL(JWS Payload) || '.' ||</code><br>
    <code>BASE64URL(JWS Signature)</code></p>
<p class="has-line-data" data-line-start="7" data-line-end="8">In the JWS JSON Serialization, a JWS is represented as a JSON object containing some or all of these four members:</p>
<ul>
    <li class="has-line-data" data-line-start="9" data-line-end="10"><strong>protected</strong>, with the value <code>BASE64URL(UTF8(JWS Protected Header))</code></li>
    <li class="has-line-data" data-line-start="10" data-line-end="14"><strong>header</strong>, with the value JWS Unprotected Header for example<br>
        <code>{&quot;alg&quot;:&quot;HS256&quot;}</code><br>
        Encoding this JWS Protected Header as <code>BASE64URL(UTF8(JWS Protected Header))</code> gives this value:<br>
        <code>eyJhbGciOiJIUzI1NiJ9</code></li>
    <li class="has-line-data" data-line-start="14" data-line-end="15"><strong>payload</strong>, with the value <code>BASE64URL(JWS Payload)</code> for example the payload</li>
</ul>
<pre><code class="has-line-data" data-line-start="16" data-line-end="22">{
  &quot;sub&quot;: &quot;1234567890&quot;,
  &quot;name&quot;: &quot;Anish Nath&quot;,
  &quot;iat&quot;: 1516239022
}
</code></pre>
<p class="has-line-data" data-line-start="22" data-line-end="23">Encoding this JWS Payload as <code>BASE64URL(JWS Payload)</code> gives this value</p>
<pre><code class="has-line-data" data-line-start="24" data-line-end="27">ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0

</code></pre>
<ul>
    <li class="has-line-data" data-line-start="27" data-line-end="29"><strong>signature</strong>, with the value <code>BASE64URL(JWS Signature)</code> Computing the HMAC with the HMAC<br>
        SHA-256</li>
</ul>
<pre><code class="has-line-data" data-line-start="30" data-line-end="32">9tFLrurxXWKBDh317ly24fP03We-uzSZtPf7Yqy_oSw
</code></pre>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>