<!DOCTYPE html>
<html>
<head>
	<title>kubernetes pods,deployments,service yaml json generator</title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="Online generate kubernetes pods,deployments,service generator in YAML and JSON file">
	<meta name="keywords" content="kubernetes pods config generator online">

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "kubernetes pods,deployment.service generator",
  "image" : "https://8gwifi.org/images/site/kube.png",
  "url" : "https://8gwifi.org/kube.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-02-19",
  "applicationCategory" : [ "kubernetes config genarator", "kubernetes pod yaml generate", "kubenrtes pod json generate"],
  "downloadUrl" : "https://8gwifi.org/kube.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "kubernetes deployment, pods config generator online",
  "softwareVersion" : "v1.0"
}
</script>


	<script type="text/javascript">
		$(document).ready(function() {

			$('#form').show();
			$('#service').hide();
			$('#nport').hide();
			$('#nport1').hide();
			$('#lip').hide();
			$('#exName').hide();
			$('#portmap').show();
			$('#portmap1').show();

			$('#selectkubeobject').change(function (event)
			{
				var x = $( "#selectkubeobject" ).val();
				if(x==1)
				{
					$('#form').show();
					$('#service').hide();
				}
				if(x==2)
				{
					$('#form').hide();
					$('#service').show();
				}


			});

			$('#type').change(function (event)
			{

				var x = $( "#type" ).val();
				if("NodePort" === x)
				{
					$('#nport').show();
					$('#nport1').show();
					$('#exshow').show();
					$('#lip').hide();
					$('#cip').show();
					$('#exName').hide();
					$('#portmap').show();
					$('#portmap1').show();
					$('#showexternalIPs').show();

				}
				else if ("LoadBalancer" ===x)
				{
					$('#nport').show();
					$('#nport1').show();
					$('#exshow').show();
					$('#lip').show();
					$('#cip').show();
					$('#exName').hide();
					$('#portmap').show();
					$('#portmap1').show();
					$('#showexternalIPs').show();
				}
				else if ("ClusterIP" ===x)
				{
					$('#nport').show();
					$('#nport1').show();
					$('#exshow').show();
					$('#lip').hide();
					$('#cip').show();
					$('#exName').hide();
					$('#portmap').show();
					$('#portmap1').show();
					$('#showexternalIPs').show();
				}
				else if ("ExternalName" ===x)
				{
					$('#exshow').hide();
					$('#nport').hide();
					$('#nport1').hide();
					$('#exshow').show();
					$('#lip').hide();
					$('#cip').hide();
					$('#exName').show();
					$('#portmap').hide();
					$('#portmap1').hide();
					$('#showexternalIPs').hide();
				}
				else{
					$('#nport').hide();
					$('#nport1').hide();
					$('#lip').hide();
				}

			});



			$('#generateservice').click(function (event)
			{
				//
				$('#service').delay(200).submit()

			});


			$('#generatesshpods').click(function (event)
			{
				//
				$('#form').delay(200).submit()

			});

			$('#generatedeployment').click(function (event)
			{
				//
				$('#deployment').val('deployment')
				$('#form').delay(200).submit()

			});


			$('#form').submit(function (event)
			{
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type: "POST",
					url: "KubeFunctionality", //this is my servlet
					data: $("#form").serialize(),
					success: function(msg){
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});

			$('#service').submit(function (event)
			{
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type: "POST",
					url: "KubeFunctionality", //this is my servlet
					data: $("#service").serialize(),
					success: function(msg){
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});
		});

	</script>


</head>
<%@ include file="body-script.jsp"%>



<h1 class="mt-4">Kubernetes YAML/JSON Generator (Pods/Deployments/Service)</h1>
<p>Use this tool to generate kubernetes Pods output in YAML and JSON</p>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>

<%@ include file="footer_adsense.jsp"%>

<hr>

<form id="showoptions">
	<div class="form-group">
		<label for="selectkubeobject">Build Kubernetes Object</label>
		<select class="form-control" id="selectkubeobject">
			<option value="1">Pods/Deployment</option>
			<option value="2">Service</option>
		</select>
	</div>
</form>


<form id="service" method="POST">
	<h4>Configure Service </h4>
	<hr>
	<div class="form-row">

		<div class="form-group col-md-6">
			<label for="name">Name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="service Name in Lowercase">
			<small>Service Name must be unique within a namespace</small>
		</div>
		<div class="form-group col-md-6">
			<label for="namespace">Namespace</label>
			<input type="text" class="form-control" value="default" id="namespace" name="namespace">
			<small>An empty namespace is equivalent to the "default"  </small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-4">
			<label for="type">Service Type</label>
			<select class="form-control" name="type" id="type">
				<option value="ClusterIP" selected>ClusterIP</option>
				<option value="NodePort">NodePort</option>
				<option value="LoadBalancer">LoadBalancer</option>
				<option value="ExternalName">ExternalName</option>
			</select>
		</div>

		<div class="form-group col-md-8">
			<label for="label">Labels</label>
			<input type="text" class="form-control" value="app=nginx,env=staging" name="label" id="label" placeholder="app=nginx,env=staging">
			<small>Format app=nginx,env=staging</small>
		</div>

	</div>

	<div id="exshow" class="form-row">

		<div id="cip" class="form-group col-md-6">
			<label for="clusterIP">clusterIP</label>
			<input type="text" class="form-control" id="clusterIP" value="" name="clusterIP" placeholder="">
			<small>Valid values "None", empty string (""), or a valid IP .</small>
		</div>

		<div  id="lip" class="form-group col-md-6">
			<label for="loadBalancerIP">loadBalancerIP</label>
			<input type="text" class="form-control" id="loadBalancerIP" name="loadBalancerIP" placeholder="192.168.1.1">
			<small> LoadBalancer will get created with the IP specified in this field.</small>
		</div>


		<div  id="exName" class="form-group col-md-6">
			<label for="externalName">externalName</label>
			<input type="text" class="form-control" id="externalName" name="externalName" placeholder="my.service.example.com">
			<small>external reference CNAME </small>
		</div>

	</div>

	<div id="portmap" class="form-row">
		<div class="form-group col-md-3">
			<label for="port">PORT-Name</label>
			<input type="text" class="form-control" placeholder="http" value="http" id="portname" name="portname">
		</div>
		<div class="form-group col-md-2">
			<label for="port">PORT</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="80" value="80" id="port" name="port">
		</div>
		<div class="form-group col-md-3">
			<label for="targetPort">TargetPort</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="80" value="80" name="targetPort" id="targetPort">
		</div>

		<div id="nport" class="form-group col-md-2">
			<label for="targetPort">Node Port</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="32745" value="" name="nodePort" id="nodePort">
		</div>

		<div class="form-group col-md-2">
			<label for="protocol">Protocol</label>
			<select class="form-control" name="protocol" id="protocol">
				<option value="TCP" selected>TCP</option>
				<option value="UDP">UDP</option>
				<option value="SCTP">SCTP</option>
			</select>
		</div>


	</div>
	<div id="portmap1" class="form-row">
		<div class="form-group col-md-3">
			<label for="port">PORT-Name</label>
			<input type="text" class="form-control" placeholder="https" value="" id="portname1" name="portname1">
		</div>
		<div class="form-group col-md-2">
			<label for="env2">PORT</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="443" value="" id="port1" name="port1">
		</div>
		<div class="form-group col-md-3">
			<label for="v2">TargetPort</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="8443" value="" name="targetPort1" id="targetPort1">
		</div>

		<div id="nport1" class="form-group col-md-2">
			<label for="targetPort">Node Port</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="32746" value="" name="nodePort1" id="nodePort1">
		</div>

		<div class="form-group col-md-2">
			<label for="protocol">Protocol</label>
			<select class="form-control" name="protocol1" id="protocol1">
				<option value="TCP" >TCP</option>
				<option value="UDP">UDP</option>
				<option value="SCTP">SCTP</option>
			</select>
		</div>

	</div>

	<div id="showexternalIPs"  class="form-row">
		<div class="form-group col-md-8" >
			<label for="externalIPs">externalIPs</label>
			<input type="text" class="form-control" placeholder="104.27.177.30,104.27.177.30" value="" name="externalIPs" id="externalIPs">
			<small>List of external Ip's leave Blank if not managed by external</small>
		</div>

		<div class="form-group col-md-2">
			<label for="sessionAffinity">sessionAffinity</label>
			<select class="form-control" name="sessionAffinity" id="sessionAffinity">
				<option value="None" selected >None</option>
				<option value="ClientIP">ClientIP</option>
			</select>
		</div>

	</div>

	<hr>


	<input type="hidden" name="methodName" id="methodName"  value="SERVICE_GENERATE">
	<input type="button" class="btn btn-primary" id="generateservice" name="generata Service" value="Generate Service Spec">
</form>

<form id="form" method="POST">

	<input type="hidden" name="methodName" id="methodName"  value="POD_GENERATE">
	<input type="hidden" name="deployment" id="deployment"  value="pod">

	<h4>Configure Metadata </h4>
	<hr>

	<div class="form-row">



		<div class="form-group col-md-6">
			<label for="name">Name</label>
			<input type="text" class="form-control" id="name" name="name" placeholder="podName">
			<small>Name must be unique within a namespace</small>
		</div>
		<div class="form-group col-md-6">
			<label for="namespace">Namespace</label>
			<input type="text" class="form-control" value="default" id="namespace" name="namespace">
			<small>An empty namespace is equivalent to the "default"  </small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-4">
			<label for="annotation">Annotation</label>
			<input type="text" class="form-control" id="annotation" name="annotation">
			<small>annotations to attach metadata</small>
		</div>
		<div class="form-group col-md-8">
			<label for="label">Labels</label>
			<input type="text" class="form-control" value="app=nginx,env=staging" name="label" id="label" placeholder="app=nginx,env=staging">
			<small>Format app=nginx,env=staging</small>
		</div>
	</div>


	<hr>

	<h4>Configure Container Spec </h4>
	<hr>

	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="image">Docker Image</label>
			<input type="text" class="form-control" id="image" value="nginx" name="image">
			<small>Docker Image Name Example: nginx</small>
		</div>
		<div class="form-group col-md-6">
			<label for="containerName">Container Name</label>
			<input type="text" class="form-control" value="" name="containerName" id="containerName" placeholder="nginxc">
			<small>Name of the container  DNS_LABEL</small>
		</div>


	</div>


	<div class="form-row">


		<div class="form-group col-md-4">
			<label for="imagePullPolicy">Image Pull Policy</label>
			<select class="form-control" name="imagePullPolicy" id="imagePullPolicy">
				<option value="IfNotPresent" selected>IfNotPresent</option>
				<option value="Always">Always</option>
				<option value="latest">latest</option>
			</select>
		</div>

		<div class="form-group col-md-4">
			<label for="restartPolicy">restartPolicy</label>
			<select class="form-control" name="restartPolicy" id="restartPolicy">
				<option value="Always" selected>Always</option>
				<option value="OnFailure">OnFailure</option>
				<option value="Never">Never</option>
			</select>
		</div>

		<div class="form-group col-md-4">
			<label for="dnsPolicy">dnsPolicy</label>
			<select class="form-control" name="dnsPolicy" id="dnsPolicy">
				<option value="ClusterFirst" selected>ClusterFirst</option>
				<option value="ClusterFirstWithHostNet">ClusterFirstWithHostNet</option>
				<option value="None">None</option>
			</select>
		</div>

	</div>

	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="containercommand">Container Commands</label>
			<input type="text" class="form-control" placeholder="ls -ltr,touch a" value="" id="containercommand" name="containercommand">
			<small>To add multiple commands use "," as delimeter ls -ltr,touch a </small>
		</div>
		<div class="form-group col-md-6">
			<label for="containerargs">Container Arguments</label>
			<input type="text" class="form-control" placeholder="A,B,C" value="" name="containerargs" id="containerargs">
			<small>To add multiple argument use "," as delimeter</small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="containercommand">Container ports</label>
			<input type="text" class="form-control" value="80" placeholder="80,443" id="containerPorts" name="containerPorts">
			<small>To add multiple pors use "," as delimeter 80,443</small>
		</div>
		<div class="form-group col-md-6">
			<label for="volumeMounts">volumeMounts</label>
			<input type="text" class="form-control" value="" placeholder="/mnt/data" name="volumeMounts" id="volumeMounts">
			<small>To add multiple volumeMounts use "," as delimeter</small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="env1">ENV</label>
			<input type="text" class="form-control" placeholder="NGINX_HOST" value="" id="env1" name="env1">
		</div>
		<div class="form-group col-md-6">
			<label for="v1">VALUE</label>
			<input type="text" class="form-control" placeholder="8gwifi.org" value="" name="v1" id="v1">
		</div>
	</div>
	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="env2">ENV</label>
			<input type="text" class="form-control" placeholder="NGINX_PORT" value="" id="env2" name="env2">
		</div>
		<div class="form-group col-md-6">
			<label for="v2">VALUE</label>
			<input type="text" class="form-control" placeholder="80" value="" name="v2" id="v2">
		</div>
	</div>


	<div class="form-row">
		<div class="form-group col-md-4">
			<label for="livenessProbepath">livenessProbe</label>
			<input type="text" class="form-control" value="" placeholder="/healthz" id="livenessProbepath" name="livenessProbepath">
			<small>livenessProbe PATH</small>
		</div>
		<div class="form-group col-md-4">
			<label for="livenessProbeport">Port</label>
			<input type="text" class="form-control" value="" size="10" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="80" id="livenessProbeport" name="livenessProbeport">
			<small>livenessProbe Port</small>
		</div>
		<div class="form-group col-md-4">
			<label for="livenessProbescheme">scheme</label>
			<input type="text" class="form-control" id="livenessProbescheme" placeholder="HTTP" value="" name="livenessProbescheme">
			<small>livenessProbe scheme</small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-4">
			<label for="readinessProbepath">readinessProbe</label>
			<input type="text" class="form-control" value="" placeholder="/healthz" id="readinessProbepath" name="readinessProbepath">
			<small>readinessProbe PATH</small>
		</div>
		<div class="form-group col-md-4">
			<label for="readinessProbeport">Port</label>
			<input type="text" class="form-control" value="" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" placeholder="10254" size="10" id="readinessProbeport" name="readinessProbeport">
			<small>readinessProbe Port</small>
		</div>
		<div class="form-group col-md-4">
			<label for="readinessProbescheme">scheme</label>
			<input type="text" class="form-control"  id="readinessProbescheme" placeholder="HTTP" value="" name="readinessProbescheme">
			<small>readinessProbe scheme</small>
		</div>
	</div>

	<div class="form-row">
		<div class="form-group col-md-3">
			<label for="nameservers">nameservers</label>
			<input type="text" class="form-control" id="nameservers" value="" placeholder="1.1.1.1,2.2.2.2" name="nameservers">
			<small>dnsConfig nameservers</small>
		</div>
		<div class="form-group col-md-4">
			<label for="searches">searches</label>
			<input type="text" class="form-control" value="" name="searches" id="searches" placeholder="ns1.svc.cluster-domain.example">
			<small>dnsConfig searches</small>
		</div>

		<div class="form-group col-md-2">
			<label for="optionsN">options Name</label>
			<input type="text" class="form-control" value="" name="optionsN" id="optionsN" placeholder="ndots">
		</div>

		<div class="form-group col-md-2">
			<label for="optionsV">options Value</label>
			<input type="text" class="form-control" value="" name="optionsV" id="optionsV" placeholder="2">
		</div>

	</div>

	<div class="form-row">
		<div class="form-group col-md-3">
			<label for="subdomain">subdomain</label>
			<input type="text" class="form-control" id="subdomain" value="" placeholder="subdomain" name="subdomain">
			<small>subdomain</small>
		</div>
		<div class="form-group col-md-3">
			<label for="serviceAccountName">serviceAccountName</label>
			<input type="text" class="form-control" value="" name="serviceAccountName" id="serviceAccountName" placeholder="serviceAccountName">
			<small>serviceAccountName</small>
		</div>

		<div class="form-group col-md-3">
			<label for="subdomain">hostname</label>
			<input type="text" class="form-control" id="hostname" value="" placeholder="hostname" name="hostname">
			<small>hostname</small>
		</div>
		<div class="form-group col-md-3">
			<label for="nodeName">nodeName</label>
			<input type="text" class="form-control" value="" name="nodeName" id="nodeName" placeholder="nodeName">
			<small>where pod will run</small>
		</div>



	</div>
	<hr>

	<h4> Add SecurityContext</h4>


	<div class="form-row">

		<div class="form-group col-md-">
			<input class="form-check-input" type="checkbox" name="apployonPod" id="apployonPod" value="apployonPod" id="apployonPod">
			<label class="form-check-label" for="apployonPod">
				On Pod Level
			</label>
		</div>


		<div class="form-group col-md-2">
			<label for="fsGroup">fsGroup</label>
			<input type="text" class="form-control" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" id="fsGroup" value="" placeholder="2000" name="fsGroup">
			<small>fsGroup</small>
		</div>
		<div class="form-group col-md-2">
			<label for="serviceAccountName">runAsGroup</label>
			<input type="text" class="form-control" value="" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" name="runAsGroup" id="runAsGroup" placeholder="1000">
			<small>runAsGroup</small>
		</div>

		<div class="form-group col-md-2">
			<label for="runAsNonRoot">runAsNonRoot</label>
			<input type="text" class="form-control" id="runAsNonRoot"  value="" placeholder="true" name="runAsNonRoot">
			<small>runAsNonRoot</small>
		</div>
		<div class="form-group col-md-2">
			<label for="runAsUser">runAsUser</label>
			<input type="text" class="form-control" value="" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" name="runAsUser" id="runAsUser" placeholder="1000">
			<small>runAsUser</small>
		</div>



	</div>



	<input type="button" class="btn btn-primary" id="generatesshpods" name="generata spec" value="Generate POD SPEC">
	<input type="button" class="btn btn-primary" id="generatedeployment" name="generata spec with Deployment" value="Generate Deployment">
</form>

<hr>
<div id="output"></div>

<%@ include file="footer_adsense.jsp"%>


<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>


<hr>
<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
	<div>
		<ul>
			<li><a href="dc.jsp">Docker Compose Generator</a></li>
			<li><a href="dc1.jsp">Docker run to Docker Compose Conversion</a></li>
			<li><a href="dc2.jsp">Docker Compose to docker run Conversion</a></li>
			<li><a href="kube.jsp">Kubertes Spec Generate(Pods/svc)</a></li>
			<li><a href="kube1.jsp">Docker Compose to Kubernetes conversion</a></li>
			<li><a href="kube2.jsp">Kubernetes  to Docker compose conversion</a></li>
			<li><a href="jsonparser.jsp">JSON-2-YAML Convertor</a></li>
			<li><a href="yamlparser.jsp">YAML-2-JSON Convertor</a></li>
			<li><a href="qrcodegen.jsp">QR Code generate</a></li>
			<li><a href="hexdump.jsp">Online Hexdump Generate</a></li>
			<li><a href="diff.jsp">Compare text differences</a></li>
			<li><a href="UrlEncodeDecodeFunctions.jsp">URL Encoders/Decoders</a></li>
			<li><a href="HexToStringFunctions.jsp">Hex To String Conversion</a></li>
			<li><a href="HexToStringFunctions.jsp">String To Hex Conversion</a></li>
			<li><a href="base64Hex.jsp">Base64 To Hex (ViceVersa)</a></li>
			<li><a href="Base64Functions.jsp">Base64 Encode/Decode</a></li>
			<li><a href="base64image.jsp">Base64 Image Converter(data:image/png)</a></li>
			<li><a href="StringFunctions.jsp">Various String Functions</a></li>
		</ul>
	</div>
</div>

<hr>
<h2 class="mt-4">Kubernetes Topic </h2>
<div>
	<ul>
		<li>
			<a href="docs/ansible-kube-install.jsp">kubernetes install on using ansible</a>
		</li>
		<li>
			<a href="docs/kube-install.jsp">kube install on in centos7/ubuntu7</a>
		</li>
		<li>
			<a href="docs/kube-dash.jsp">kubernetes Dashbaord Setup</a>
		</li>
		<li>
			<a href="docs/kube-pods.jsp">Pod,Cluster,Deploy,ReplicaSet Light Dive</a>
		</li>
		<li>
			<a href="docs/kube-nginx.jsp">kubernetes secure nginx deployment</a>
		</li>
		<li>
			<a href="docs/kube-ports.jsp">kubernetes Port, Targetport and NodePort</a>
		</li>
		<li>
			<a href="docs/kube-namespaces.jsp">kubernetes Namespace</a>
		</li>
		<li>
			<a href="docs/kube-auth.jsp">kubenetes Auth,Authorization,Admission</a>
		</li>
		<li>
			<a href="docs/kube-rbac.jsp">kubernetes Role-Based Access Control</a>
		</li>
		<li>
			<a href="docs/CVE-2018-1002105.jsp">Kubernetes Privilege Escalation Vulnerability</a>
		</li>
		<li>
			<a href="docs/prometheus-dashboard.jsp">Prometheus Dashboard Access</a>
		</li>
		<li>
			<a href="docs/kube-mysql.jsp">Kubernetes mysql installation</a>
		</li>
		<li>
			<a href="docs/kube-jenkins.jsp">Kubernetes Jenkins installation</a>
		</li>
		<li>
			<a href="docs/podman-jenkins.jsp">Podman Jenkins installation</a>
		</li>
		<li>
			<a href="docs/kube-mariadb.jsp">Kubernetes mariadb installation</a>
		</li>
		<li>
			<a href="docs/kube-wordpress.jsp">Kubernetes wordpress installation</a>
		</li>
		<li>
			<a href="docs/kube-drupal.jsp">Kubernetes drupal installation</a>
		</li>
		<li>
			<a href="docs/kube-traefik.jsp">Kubernetes traefik installation</a>
		</li>

		<li>
			<a href="docs/kube-traefik2.jsp">Kubernetes Ingress traefik </a>
		</li>

		<li>
			<a href="docs/kube-debug.jsp">kubernetes service external ip pending ?</a>
		</li>

		<li>
			<a href="docs/kube-Istio.jsp">Service Mesh With Istio</a>
		</li>

		<li>
			<a href="docs/kube-externalname.jsp">Access SVC in Another Namespaces</a>
		</li>

		<li>
			<a href="docs/kube-java.jsp">kubernetes Java client example</a>
		</li>

		<li>
			<a href="docs/kube-lets.jsp">kubernetes letsencrypt deploy wild card certificate</a>
		</li>

		<li>
			<a href="docs/docker-install.jsp">Right Way to Install Docker</a>
		</li>

		<li>
			<a href="docs/docker-privaterepo.jsp">Docker Private repo with SSL and AUTH</a>
		</li>

		<li>
			<a href="docs/docker-baseimage.jsp">Creating Docker Base Image</a>
		</li>

		<li>
			<a href="docs/containers.jsp">Container Runtime (RUNC,RKT,CRI-O,Conatinerd) </a>
		</li>

		<li>
			<a href="docs/podman-install.jsp">Podman Install on Ubuntu/Debian</a>
		</li>
	</ul>
</div>



<hr>



<%@ include file="footer_adsense.jsp"%>


<%@ include file="addcomments.jsp"%>

</div class="row">

<%@ include file="body-close.jsp"%>