<!DOCTYPE html>
<html>
<head>
    <title>translate kubernetes resourses to docker compose </title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="generate docker compose file from kubernetes pods,deployment,statefulset,replication controller"/>
    <meta name="keywords" content="kubernetes pods to docker compose, convert kubernetes deployment to docker compose">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>


    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "docker compose generator",
  "image" : "https://8gwifi.org/images/site/kube2.png",
  "url" : "https://8gwifi.org/kube2.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-03-17",
  "applicationCategory" : [ "kubernetes to docker compose" , "pods to docker compose" , "kubernetes deployment to docker compose"],
  "downloadUrl" : "https://8gwifi.org/kube2.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "convert kubernetes resources to docker compose file",
  "softwareVersion" : "v1.0"
}
</script>


    <script type="text/javascript">
        $(document).ready(function() {

            $('#generatedc').click(function (event)
            {
                //
                $('#form').delay(200).submit()

            });

            $('#form').submit(function (event)
            {
                //
                $('#output').html('<img src="images/712.GIF"> loading...');
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "KubeFunctionality", //this is my servlet

                    data: $("#form").serialize(),
                    success: function(msg){
                        $('#output').empty();
                        $('#output').append(msg);

                    }
                });
            });
        });

    </script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Translate Kubernetes Resources to Docker Compose</h1>
<p>This tool will help to convert the kubernetes pod,deployment,statefulset,replication controller to Docker Compose file</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>

<%@ include file="footer_adsense.jsp"%>

<form id="form" method="POST">
    <input type="hidden" name="methodName" id="methodName" value="KUBE_2_COMPOSE">



    <div class="form-row">
        <div class="form-group">
            <label for="kubestuff">Paste your Docker Compose file</label>
            <textarea class="form-control" name="kubestuff" id="kubestuff" cols="100" rows="20">
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    generated: by 8gwifi.org
  labels:
    app: nginx
    env: staging
  name: demo
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: demo
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  terminationGracePeriodSeconds: 0

#This is Deployment Configuration Kube definition
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    com.example.empty-label: com.example.empty-label
    generated.by: 8gwifi.org
    com.example.number: '42'
    com.example.description: Accounting webapp
  labels:
    app: demo.25
  name: deployment.name.84
  namespace: default
spec:
  replicas: 6
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: demo.25
  template:
    metadata:
      labels:
        app: demo.25
      namespace: default
    spec:
      containers:
      - command:
        - /code/entrypoint.sh
        - -p
        - '3000'
        env:
        - name: RACK_ENV
          value: development
        - name: SHOW
          value: 'true'
        - name: SESSION_SECRET
        - name: BAZ
          value: '3'
        envFrom:
          configMapRef:
            name: env_file_from_configmap_4
        image: redis
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - echo
            - '"hello world"'
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: my-web-container
        ports:
        - containerPort: 3000
          name: portname.0
          protocol: tcp
        - containerPort: 8000
          name: portname.2
          protocol: tcp
        - containerPort: 22
          name: portname.4
          protocol: tcp
        securityContext:
          capabilities:
            add:
            - ALL
            drop:
            - NET_ADMIN
            - SYS_ADMIN
          privileged: true
          runAsGroup: 1000
          runAsUser: 1000
          seLinuxOptions:
            level: s0:c100,c200
            type: svirt_apache_t
        stdin: true
        tty: true
        volumeDevices:
        - devicePath: /dev/ttyUSB0
          name: mydevice0
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: pvo.0
        - mountPath: /var/lib/mysql
          name: pvo.1
        - mountPath: /code
          name: pvo.2
        - mountPath: /var/www/html
          name: pvo.3
        - mountPath: /etc/configs/
          name: pvo.4
          readOnly: true
        - mountPath: /var/lib/mysql
          name: pvo.5
        - mountPath: /run
          name: pvotmpfs_0
        - mountPath: /tmp
          name: pvotmpfs_1
        workingDir: /code
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 9.9.9.9
        searches:
        - dc1.example.com
        - dc2.example.com
      hostAliases:
      - hostnames:
        - somehost
        ip: 162.242.195.82
      - hostnames:
        - otherhost
        ip: 50.31.209.229
      hostPID: true
      hostname: foo
      nodeSelector:
        node: foo
      restartPolicy: OnFailure
      subdomain: foo.com
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvo.1
        persistentVolumeClaim:
          claimName: claimname.0
      - name: pvo.2
        persistentVolumeClaim:
          claimName: claimname.1
      - name: pvo.3
        persistentVolumeClaim:
          claimName: claimname.2
      - name: pvo.4
        persistentVolumeClaim:
          claimName: claimname.3
      - name: pvo.5
        persistentVolumeClaim:
          claimName: claimname.4
      - hostPath:
          path: /dev/ttyUSB0
        name: mydevice0
      - emptyDir:
          medium: Memory
        name: pvotmpfs_0
      - emptyDir:
          medium: Memory
        name: pvotmpfs_1
</textarea>
        </div>
    </div>
    <input type="button" class="btn btn-primary" id="generatedc" name="Generate Kubernetes Resources" value="Generate Docker Compose">
</form>

<hr>

<div id="output"></div>

<hr>

<div class="sharethis-inline-share-buttons"></div>

<%@ include file="footer_adsense.jsp"%>

<hr>
<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
    <div>
        <ul>
            <li><a href="kube.jsp">Kubertes Spec Generate(Pods/svc)</a></li>
            <li><a href="dc.jsp">Docker Compose Generator</a></li>
            <li><a href="dc1.jsp">Docker run to Docker Compose Conversion</a></li>
            <li><a href="dc2.jsp">Docker Compose to docker run Conversion</a></li>
            <li><a href="kube1.jsp">Docker Compose to Kubernetes conversion</a></li>
            <li><a href="kube2.jsp">Kubernetes to Docker compose conversion</a></li>
            <li><a href="jsonparser.jsp">JSON-2-YAML Convertor</a></li>
            <li><a href="yamlparser.jsp">YAML-2-JSON Convertor</a></li>
            <li><a href="qrcodegen.jsp">QR Code generate</a></li>
            <li><a href="hexdump.jsp">Online Hexdump Generate</a></li>
            <li><a href="diff.jsp">Compare text differences</a></li>
            <li><a href="UrlEncodeDecodeFunctions.jsp">URL Encoders/Decoders</a></li>
            <li><a href="HexToStringFunctions.jsp">Hex To String Conversion</a></li>
            <li><a href="HexToStringFunctions.jsp">String To Hex Conversion</a></li>
            <li><a href="base64Hex.jsp">Base64 To Hex (ViceVersa)</a></li>
            <li><a href="Base64Functions.jsp">Base64 Encode/Decode</a></li>
            <li><a href="base64image.jsp">Base64 Image Converter(data:image/png)</a></li>
            <li><a href="StringFunctions.jsp">Various String Functions</a></li>
        </ul>
    </div>
</div>

<hr>
<h2 class="mt-4">Kubernetes Topic </h2>
<div>
    <ul>
        <li>
            <a href="docs/ansible-kube-install.jsp">kubernetes install on using ansible</a>
        </li>
        <li>
            <a href="docs/kube-install.jsp">kube install on in centos7/ubuntu7</a>
        </li>
        <li>
            <a href="docs/kube-dash.jsp">kubernetes Dashbaord Setup</a>
        </li>
        <li>
            <a href="docs/kube-pods.jsp">Pod,Cluster,Deploy,ReplicaSet Light Dive</a>
        </li>
        <li>
            <a href="docs/kube-nginx.jsp">kubernetes secure nginx deployment</a>
        </li>
        <li>
            <a href="docs/kube-ports.jsp">kubernetes Port, Targetport and NodePort</a>
        </li>
        <li>
            <a href="docs/kube-namespaces.jsp">kubernetes Namespace</a>
        </li>
        <li>
            <a href="docs/kube-auth.jsp">kubenetes Auth,Authorization,Admission</a>
        </li>
        <li>
            <a href="docs/kube-rbac.jsp">kubernetes Role-Based Access Control</a>
        </li>
        <li>
            <a href="docs/CVE-2018-1002105.jsp">Kubernetes Privilege Escalation Vulnerability</a>
        </li>
        <li>
            <a href="docs/prometheus-dashboard.jsp">Prometheus Dashboard Access</a>
        </li>
        <li>
            <a href="docs/kube-mysql.jsp">Kubernetes mysql installation</a>
        </li>
        <li>
            <a href="docs/kube-jenkins.jsp">Kubernetes Jenkins installation</a>
        </li>
        <li>
            <a href="docs/podman-jenkins.jsp">Podman Jenkins installation</a>
        </li>
        <li>
            <a href="docs/kube-mariadb.jsp">Kubernetes mariadb installation</a>
        </li>
        <li>
            <a href="docs/kube-wordpress.jsp">Kubernetes wordpress installation</a>
        </li>
        <li>
            <a href="docs/kube-drupal.jsp">Kubernetes drupal installation</a>
        </li>
        <li>
            <a href="docs/kube-traefik.jsp">Kubernetes traefik installation</a>
        </li>

        <li>
            <a href="docs/kube-traefik2.jsp">Kubernetes Ingress traefik </a>
        </li>

        <li>
            <a href="docs/kube-debug.jsp">kubernetes service external ip pending ?</a>
        </li>

        <li>
            <a href="docs/kube-Istio.jsp">Service Mesh With Istio</a>
        </li>

        <li>
            <a href="docs/kube-externalname.jsp">Access SVC in Another Namespaces</a>
        </li>

        <li>
            <a href="docs/kube-java.jsp">kubernetes Java client example</a>
        </li>

        <li>
            <a href="docs/kube-lets.jsp">kubernetes letsencrypt deploy wild card certificate</a>
        </li>

        <li>
            <a href="docs/docker-install.jsp">Right Way to Install Docker</a>
        </li>

        <li>
            <a href="docs/docker-privaterepo.jsp">Docker Private repo with SSL and AUTH</a>
        </li>

        <li>
            <a href="docs/docker-baseimage.jsp">Creating Docker Base Image</a>
        </li>

        <li>
            <a href="docs/containers.jsp">Container Runtime (RUNC,RKT,CRI-O,Conatinerd) </a>
        </li>

        <li>
            <a href="docs/podman-install.jsp">Podman Install on Ubuntu/Debian</a>
        </li>
    </ul>
</div>


<hr>


<%@ include file="thanks.jsp"%>
<hr>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>