<!DOCTYPE html>
<html>
<head>

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "online message digest of a file ",
  "image" : "https://8gwifi.org/images/site/hash.png",
  "url" : "https://8gwifi.org/mdfile.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2019-07-23",
  "applicationCategory" : [ "hashing online", "generate message digest online of file", "SHA", "SHA-1", "SHA-224", "SHA-256", "SHA-512"],
  "downloadUrl" : "https://8gwifi.org/mdfile.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Calculate or verify  Message Digest Algorithms of a file using hash algorithms sha sha-1 sha-224 sha-256 sha-384 sha-512 ",
  "softwareVersion" : "v1.0"
}
</script>

    <style>

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color: #15824B;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }

    </style>

    <title>Generate Hash value for a file using SHA algorithms </title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Calculate or verify dessage Digest Algorithms of a give file using hash algorithms SHA-1,SHA-256,SHA-384,SHA-512 webcrypto ">
    <meta name="keywords" content="Calculate or verify digest Algorithms of a give file using hash algorithms SHA-1,SHA-256,SHA-384,SHA-512">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>

    <%
        String[] validList = { "SHA-256","SHA-384","SHA-512"};
    %>



    <script type="text/javascript">
        $(document).ready(function() {


            $('#output').hide();


//            $('#cipherparameternew').change(function(event) {
//                //
//                // event.preventDefault();
//                $('#form').delay(200).submit()
//            });
//
//            $('#inputtext').keyup(function (event)
//            {
//                $('#form').delay(200).submit()
//            });
//
//
//            $('#sun').click(function (event)
//            {
//                $('#form').delay(200).submit()
//            });
//
//            $('#form').submit(function (event)
//            {
//                //
//                $('#output').html('<img src="images/712.GIF"> loading...');
//                event.preventDefault();
//                $.ajax({
//                    type: "POST",
//                    url: "MDFunctionality", //this is my servlet
//
//                    data: $("#form").serialize(),
//                    success: function(msg){
//                        $('#output').empty();
//                        $('#output').append(msg);
//
//                    }
//                });
//            });
        });

        function readURL(input) {
            if (input.files && input.files[0]) {


                reader = new FileReader();


                reader.onload = function(e) {

                    var data = e.target.result

                    var str = document.getElementById("cipherparameternew").value;

                    if (str == "SHA-1") {
                        SHA_1_HASH(data)
                    }
                    if (str == "SHA-256") {
                        SHA_256_HASH(data)
                    }

                    if (str == "SHA-384") {
                        SHA_384_HASH(data)
                    }

                    if (str == "SHA-512") {
                        SHA_512_HASH(data)
                    }

                    document.getElementById("inner").innerHTML = "Generated HASH("+str+")";

                    $('#output').show();

                };

               reader.readAsArrayBuffer(input.files[0]);


            } else {
                removeUpload();
            }
        }


        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });


        function SHA_256_HASH(reader) {

            return crypto.subtle.digest("SHA-256", reader).then(
                    function (hash) {
                        document.getElementById("hashtext").value = hex(hash)
                    }
            );
        }
        function SHA_512_HASH(reader) {
            return crypto.subtle.digest("SHA-512", reader).then(
                    function (hash) {
                        document.getElementById("hashtext").value = hex(hash)
                    }
            );
        }

        function SHA_384_HASH(reader) {

            var str = document.getElementById("plainTextGCM").value;
            var buffer = new TextEncoder("utf-8").encode(str);
            return crypto.subtle.digest("SHA-512", reader).then(
                    function (hash) {
                        document.getElementById("hashtext").value = hex(hash)
                    }
            );
        }

        function SHA_1_HASH(reader) {

            //var buffer = new TextEncoder("utf-8").encode(reader);
            return crypto.subtle.digest("SHA-1", reader).then(
                    function (hash) {
                        document.getElementById("hashtext").value = hex(hash)
                    }
            );
        }



        function hex(buffer) {
            var hexCodes = [];
            var view = new DataView(buffer);
            for (var i = 0; i < view.byteLength; i += 4) {
                // Using getUint32 reduces the number of iterations needed (we process 4 bytes each time)
                var value = view.getUint32(i)
                // toString(16) will give the hex representation of the number without padding
                var stringValue = value.toString(16)
                // We use concatenation and slice for padding
                var padding = '00000000'
                var paddedValue = (padding + stringValue).slice(-padding.length)
                hexCodes.push(paddedValue);
            }
            // Join all the hex strings into one

            return hexCodes.join("");
        }


    </script>
</head>

<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Generate Message Digest of a File</h1>
<hr>


<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>


            <form id="form" method="POST">
                <input type="hidden" name="methodName" id="methodName" value="CALCULATE_MD">
                <fieldset name="Message Digest Functionality">
                    <b>Choose Message Digest </b>

                    <select  size="5"  name="cipherparameternew" id="cipherparameternew">
                        <option selected value="SHA-1">SHA-1</option>
                        <%
                            for (int i = 0; i < validList.length; i++) {
                                String param = validList[i];
                        %>
                        <option value="<%=param%>"><%=param%></option>
                        <%}%>
                    </select>

                    <div class="image-upload-wrap">
                        <input class="file-upload-input" type='file' onchange="readURL(this);" />
                        <div class="drag-text">
                            <h3>Drag or upload a file to calculate the hash Value e</h3>
                        </div>
                    </div>

                    <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Generate Hash </button>

                <div id="output">
                    <p id="inner"></p>
                    <textarea class="form-control" name="hashtext" id="hashtext" rows="3"></textarea>

</div>
            </form>

<hr>
<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>


<hr>
            <p>Hashing is not encryption. There is no secret, no key in hashing</p>
            <p>Hashing is a function from some bit string (usually variable length) to another bit string (usually smaller, and of fixed length</p>
            <hr>

            <p>Strengths of the Security Properties of the Approved Hash Algorithms</p>

                <table class="table">
                    <tbody>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA-1</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 256</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 384</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 512</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 512/224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>SHA- 512/256</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>Collision Resistance Strength in bits</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>&lt; 80</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>112</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>128</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>192</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>256</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>112</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>128</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>Preimage Resistance Strength in bits</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>160</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>256</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>384</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>512</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>256</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>Second Preimage Resistance Strength in bits</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>105- 160</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>201- 224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>201- 256</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>384</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>394- 512</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>224</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="layoutArea">
                                <div class="column">
                                    <p>256</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>

            <hr>

            <p><strong>List of Hash function and the length</strong></p>
            <table class="table">
                <tbody>
                <tr>
                    <td style="width: 253px;"><strong>Name</strong></td>
                    <td style="width: 143px;"><strong>Length</strong></td>
                </tr>
                <tr>
                    <td style="width: 253px;">MD2</td>
                    <td style="width: 143px;">128 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">MD4</td>
                    <td style="width: 143px;">128 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">MD5</td>
                    <td style="width: 143px;">128 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">MD6</td>
                    <td style="width: 143px;">Up to 512 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-1</td>
                    <td style="width: 143px;">160 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-224</td>
                    <td style="width: 143px;">224 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-256</td>
                    <td style="width: 143px;">256 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-384</td>
                    <td style="width: 143px;">384 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-512</td>
                    <td style="width: 143px;">512 bits</td>
                </tr>
                <tr>
                    <td style="width: 253px;">SHA-3&nbsp;(originally known as Keccak)</td>
                    <td style="width: 143px;">arbitrary</td>
                </tr>
                </tbody>
            </table>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
