<!DOCTYPE html>
<html>
<head>


	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "nacl seal box Public Key Cryptography",
  "image" : "https://8gwifi.org/images/site/nacl4.png",
  "url" : "https://8gwifi.org/naclsealboxenc.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-12-20",
  "applicationCategory" : [ "nacl seal box", "nacl crypto_box", "nacl", "nacl seal box encryption decryption", "libsodium", "cryptography", "eccrypt", "crypto_stream_aes128ctr", "crypto_stream_salsa208", "nacl online", "libsodium online", "Cryptography in NaCl" "aesgcm" ],
  "downloadUrl" : "https://8gwifi.org/naclsealboxenc.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "nacl seal box Public Key Cryptography, nacl seal box tutorial, nacl online, nacl seal box encryption decryptio, nacl generate keys, nacl tutorial crypto_box,curve25519,xsalsa20,poly130",
  "softwareVersion" : "v1.0"
}
</script>

	<title>nacl seal box Public Key Cryptography </title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>

	<meta name="keywords" content="nacl seal box Public Key Cryptography, nacl seal box tutorial, nacl online, nacl seal box encryption decryptio, nacl generate keys, nacl tutorial crypto_box,curve25519,xsalsa20,poly1305" />
	<meta name="description" content="nacl seal box Public Key Cryptography, nacl seal box tutorial, nacl online, nacl seal box encryption decryptio, nacl generate keys, nacl tutorial crypto_box,curve25519,xsalsa20,poly130" />

	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>


	<script type="text/javascript">
		$(document).ready(function() {




			$('#submit').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#publickeyparam').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#privatekeyparam').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#message').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#keysize1').click(function(event) {
				//
				// event.preventDefault();
				$('#form1').delay(200).submit()
			});

			$('#keysize2').click(function(event) {
				//
				// event.preventDefault();
				$('#form1').delay(200).submit()
			});

			$('#keysize3').click(function(event) {
				//
				// event.preventDefault();
				$('#form1').delay(200).submit()
			});

			$('#keysize4').click(function(event) {
				//
				// event.preventDefault();
				$('#form1').delay(200).submit()
			});

			$('#cipherparameter1').click(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#cipherparameter2').click(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#cipherparameter3').click(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#cipherparameter4').click(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#encryptparameter').click(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#decryptparameter').click(function(event) {

				var text = $('#output').find('textarea[name="encrypedmessagetextarea"]').val();
				if ( text != null ) {
					$("#message").val(text);
				}
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "NaclFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);
						$("#publickeyparam").resizable();
						$("#privatekeyparam").resizable();

					}
				});
			});

		});
	</script>
</head>


<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Nacl SealedBox Public Key Cryptography</h1>

<p>Sealed boxes are designed to anonymously send messages to a recipient given its public key.</p>
<p>Only the recipient can decrypt these messages, using its private key. While the recipient can verify the integrity of the message, it cannot verify the identity of the sender. </p>
<hr>


<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>







<form id="form" class="form-horizontal" method="POST">
	<input type="hidden" name="methodName" id="methodName" value="NACL_SEALBOX_ENCRYPT">


	<div class="radio">
		<label>
			<input checked id="encryptparameter" type="radio" name="encryptdecryptparameter" value="encrypt">
			Nacl Seal Box Encrypt
		</label>
	</div>
	<div class="radio">
		<label>
			<input id="decryptparameter" type="radio" name="encryptdecryptparameter" value="decrypt">
			Nacl Seal Box Decrypt
		</label>
	</div>




	<table class="table">
		<tr>
			<th>Public Key (Bob) 32 bit Hex </th>
			<th>Private Key (Bob) 32 bit Hex</th>
		</tr>

		<tr>
			<td>
				<textarea class="form-control animated" rows="3"   name="publickeyparam" id="publickeyparam">2bfb3554e563470f076d91b2dfbc58944ac0aea4d0ee9ec80ce2df22398bb545</textarea>
			</td>
			<td>
				<textarea class="form-control animated" rows="3"   name="privatekeyparam" id="privatekeyparam">6cf6a2fb7faf47aa2cbd090ba2f2cfd81cce75ed7fa41f4dc88bd7d3a2374643</textarea>
			</td>


		</tr>


		<tr>

			<td>
				<b>ClearText Message</b><textarea class="form-control" rows="5"  placeholder="Type Something Here..."  name="message" id="message"></textarea>
			</td>
			<td width="50%">
				<b>output</b><div id="output"></div>
			</td>
		</tr>
	</table>


</form>

<ul>
	<li><a href="naclencdec.jsp"><font size="2.5px">Nacl xsalsa20 Encryption & Decryption</font></a></li>
	<li><a href="naclaead.jsp"><font size="2.5px">Nacl AEAD Encryption & Decryption</font></a></li>
	<li><a href="naclboxenc.jsp"><font size="2.5px">nacl seal box Encryption & Decryption</font></a></li>
	<li><a href="naclsealboxenc.jsp"><font size="2.5px">Nacl SealBox Encryption & Decryption</font></a></li>
</ul>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="footer_adsense.jsp"%>

<h2 class="mt-4" id="naclbox1">Public-key authenticated encryption: crypto_box</h2>

<p>Sealed boxes leverage the crypto_box construction (X25519, XSalsa20-Poly1305). </p>

<p>The premise of <strong>boxes</strong> is that Alice and Bob know each other and write to each other. Alice can use a box to send a message to Bob. On receipt of the box, Bob knows (a) it came from Alice, and (b) nobody else could have read or tampered with it.

</p><p>	The premise of sealed boxes is that Bob has an anonymous dropbox. Alice can use a sealed box to send a message to Bob. On receipt of the box, Bob knows nobody but the sender could have read or tampered with it. But he knows nothing about who the sender was—it could have been Alice, or Charlie, or Dominique.</p>
<hr>

<h2 class="mt-4" id="naclbox12">How to perform NAcl Cryptography </h2>

<table id="tablePreview" class="table table-bordered">
	<!--Table head-->
	<thead>
	<tr>
		<th><a href="/docs/go-nacl.jsp">Go Lang</a> </th>
		</tr>
	</tr>
	</thead>
	<tbody>
	</tbody>
	</table>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
