<%@ page import="z.y.x.Security.Utils" %>
<!DOCTYPE html>
<html>
<head>
	<title>Nacl xsalsa20 Encryption & Decryption</title>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Nacl xsalsa20 Encryption & Decryption",
  "image" : "https://8gwifi.org/images/site/nacl1.png",
  "url" : "https://8gwifi.org/naclencdec.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-12-19",
  "applicationCategory" : [ "nacl", "libsodium", "cryptography", "eccrypt", "crypto_stream_aes128ctr", "crypto_stream_salsa208", "nacl online", "libsodium online", "Cryptography in NaCl" ],
  "downloadUrl" : "https://8gwifi.org/naclencdec.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : ""Nacl xsalsa20 Encryption & Decryption online, nacl encryption decryption online, eccrypt online, libsodium encryption online, secret box encryption secret box crypto_stream",
  "softwareVersion" : "v1.0"
}
</script>

	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="Nacl xsalsa20 Encryption & Decryption online, nacl encryption decryption online, eccrypt online, Cryptography in NaCl">
	<meta name="keywords" content="Nacl xsalsa20 Encryption & Decryption online, nacl encryption decryption online, eccrypt online, libsodium encryption online, secret box encryption secret box crypto_stream, Cryptography in NaCl, nacl tutorial"/>
	<meta name="author" content="CRYPTO" />
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>

	<script type="text/javascript">
		$(document).ready(function() {

			$('#cipherparameternew').change(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#plaintext').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#secretkey').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#nacl').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#encrypt').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#decrypt').click(function(event) {

				var text = $('#output').find('textarea[name="encrypedmessagetextarea"]').val();
				if ( text != null ) {
					$("#plaintext").val(text);
				}

				$('#form').delay(200).submit()
			});

			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "NaclFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});
		});
	</script>
</head>

<%@ include file="body-script.jsp"%>
<h1 class="mt-4">Nacl xsalsa20 Encryption & Decryption</h1>

<p>A Playgroud for nacl Secret-key encryption: crypto_stream: xsalsa20_xor </p>
<p>The crypto_stream_xor function guarantees that the ciphertext has the same length as the plaintext, and is the plaintext xor the output of crypto_stream. Consequently crypto_stream_xor can also be used to decrypt</p>

			<div id="loading" style="display: none;">
				<img src="images/712.GIF" alt="" />Loading!
			</div>

			<form class="form-horizontal" id="form" method="POST">
				<input type="hidden" name="methodName" id="methodName" value="NACL_crypto_stream_xsalsa20_xor">


				<div class="radio">
					<label>
						<input checked="checked" id="encrypt" type="radio" name="encryptorDecrypt" value="encrypt">Encrypt
					</label>
				</div>
				<div class="radio">
					<label>
						<input id="decrypt" type="radio" name="encryptorDecrypt" value="decrypt">Decrypt
					</label>
				</div>


				<div class="form-group">
					<label for="plaintext" class="col-sm-2 control-label"></label>
					<div class="col-sm-10">
						<textarea class="form-control" rows="3" name="plaintext" placeholder="Type Something here..." id="plaintext"></textarea>
					</div>
				</div>

				<%

					String hex = Utils.toHexEncoded(Utils.getIV(24));
				%>

				<div class="form-group">
					<label for="secretkey">Nonce (24 bit) in Hex</label>
					<input type="text" class="form-control"  name="nonce" id="nonce" placeholder="a23c6e1a4aa987e766ecad497f2f4166fb4117b64adfb8bc" value="<%=hex%>">
				</div>

				<div class="form-group">
					<label for="secretkey">Key (32 bit) in Hex</label>
					<input type="password" class="form-control"  name="secretkey" id="secretkey" placeholder="thisismystrongpasswordof32bitkey" value="thisismystrongpasswordof32bitkey">
				</div>



				<div id="output"></div>
			</form>

<ul>
	<li><a href="naclencdec.jsp"><font size="2.5px">Nacl xsalsa20 Encryption & Decryption</font></a></li>
	<li><a href="naclaead.jsp"><font size="2.5px">Nacl AEAD Encryption & Decryption</font></a></li>
	<li><a href="naclboxenc.jsp"><font size="2.5px">Nacl Box Encryption & Decryption</font></a></li>
	<li><a href="naclsealboxenc.jsp"><font size="2.5px">Nacl SealBox Encryption & Decryption</font></a></li>
</ul>
			<hr>

			<div class="sharethis-inline-share-buttons"></div>
			<%@ include file="thanks.jsp"%>




			<hr>

			<%@ include file="footer_adsense.jsp"%>

			<h2 class="mt-4" id="thepbealgo">Secret-key encryption: crypto_stream</h2>
			<p>The crypto_stream_xor function encrypts a message m using a secret key k and a nonce n</p>
			<p>NaCl does not make any promises regarding the resistance of crypto_stream to "related-key attacks." It is the caller's responsibility to use proper key-derivation functions.</p>

		NaCl supports the following secret-key encryption functions:

	<table class="table">
		<tr><th><tt>crypto_stream</tt></th><th>Primitive</th><th><tt>KEYBYTES</tt></th><th><tt>NONCEBYTES</tt></th></tr>
		<tr><td><tt>crypto_stream_aes128ctr</tt></td><td>AES-128-CTR</td><td>16</td><td>16</td></tr>
		<tr><td><u>[TO DO:] <tt>crypto_stream_aes256ctr</tt></u></td><td>AES-256-CTR</td><td>32</td><td>16</td></tr>
		<tr><td><tt>crypto_stream_salsa208</tt></td><td>Salsa20/8</td><td>32</td><td>8</td></tr>
		<tr><td><tt>crypto_stream_salsa2012</tt></td><td>Salsa20/12</td><td>32</td><td>8</td></tr>
		<tr><td><tt>crypto_stream_salsa20</tt></td><td>Salsa20/20</td><td>32</td><td>8</td></tr>
		<tr><td><tt>crypto_stream_xsalsa20</tt></td><td>XSalsa20/20</td><td>32</td><td>24</td></tr>
	</table>

<h2 class="mt-4" id="thepbealgo"> <a href="https://8gwifi.org/docs/go-nacl.jsp">Learn more about Nacl cryptography</a> </h2>
			<%@ include file="addcomments.jsp"%>

		</div>

<%@ include file="body-close.jsp"%>

