<!DOCTYPE html>
<html>
<head>


	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online OCSP tester Check revocation status of your SSL certificate online via OCSP protocol.",
  "image" : "https://github.com/anishnath/crypto-tool/blob/master/ocsp.png",
  "url" : "https://8gwifi.org/rsafunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-09-09",
  "applicationCategory" : ["Check revocation status of your SSL certificate online  OCSP protocol" ,"openssl ocsp query" ,"ocsp request and ocsp response debug" , "debug ocsp "],
  "downloadUrl" : "https://8gwifi.org/ocsp.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
  "requirements" : "perform ocsp query, openssl ocsp query, ocsp request response, ocsp query online, extract OCSP uri",
  "softwareVersion" : "v1.0"
}
</script>

	<title>Online OCSP tester Check revocation status of your SSL certificate online via OCSP protocol. </title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>

	<meta name="keywords" content="Check revocation status of your SSL certificate online  OCSP protocol, ocsp response unauthrized, debug OCSP online, ocsp request and ocsp response debug, openssl ocsp query" />
	<meta name="description" content="Check revocation status of your SSL certificate online via OCSP protocol, ocsp response unauthrized, debug OCSP online, ocsp openssl query, ocsp interview questions " />

	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>



	<script type="text/javascript">
		$(document).ready(function() {
			$('#submit').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "OCSPFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);
						$("#pem_1").resizable();
						$("#pem_2").resizable();

					}
				});
			});

		});
	</script>
</head>


<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Online OCSP Request/Response</h1>
<hr>


<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>


</fieldset>


<form id="form" class="form-horizontal" method="POST">
	<input type="hidden" name="methodName" id="methodName"
		   value="CALCULATE_OCSP">

	<table class="table">
		<tr>
			<th>Server Certificate</th>
			<th>Intermediate Certificates </th>
		</tr>

		<tr>
			<td>
				<textarea class="form-control animated" rows="10"   name="p_pem1" id="p_pem1">-----BEGIN CERTIFICATE-----
MIIF/TCCBOWgAwIBAgISA/80l7+l1Fw2xRGAn5/V8owgMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA3MjIwNzU5MjRaFw0x
ODEwMjAwNzU5MjRaMBUxEzARBgNVBAMTCjhnd2lmaS5vcmcwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDD80G293JoZaHdzQZ1y9qT5HaaxumFhmrhkhsZ
BvvYY7WezLzuKkRgb+eyiBT0z5gzPfW3CKnNc/RXlPT53eRUf3zy8EWwzGgUHODi
+x86g2HHzOOIJUMhFcu8nMxlFWmYUE3CzwcZCVXJyLMiPbOIqd5XuTxrbebLrI2Q
mytV7YLCfUurlv+X6HEhjGGTqQzdjJRF0LvrALPgPJhxbMgwpmVWi797f2noHKTj
ZeqRKS9pl4dZpEgBlpLbkRc+N8tWAfKiWAw/HDN7RkLKuTNKmAWlKMAZdjRFDTOc
vIC/IKQzWFYhkCt29dvIQMrr+sCVB/gQ0cBjK+ms2y2bT7pJAgMBAAGjggMQMIID
DDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFASRBHzTfFovjmNwcgLnhzoUIunZMB8G
A1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMwYTAu
BggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9yZzAv
BggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8w
FQYDVR0RBA4wDIIKOGd3aWZpLm9yZzCB/gYDVR0gBIH2MIHzMAgGBmeBDAECATCB
5gYLKwYBBAGC3xMBAQEwgdYwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2Vu
Y3J5cHQub3JnMIGrBggrBgEFBQcCAjCBngyBm1RoaXMgQ2VydGlmaWNhdGUgbWF5
IG9ubHkgYmUgcmVsaWVkIHVwb24gYnkgUmVseWluZyBQYXJ0aWVzIGFuZCBvbmx5
IGluIGFjY29yZGFuY2Ugd2l0aCB0aGUgQ2VydGlmaWNhdGUgUG9saWN5IGZvdW5k
IGF0IGh0dHBzOi8vbGV0c2VuY3J5cHQub3JnL3JlcG9zaXRvcnkvMIIBAgYKKwYB
BAHWeQIEAgSB8wSB8ADuAHUA23Sv7ssp7LH+yj5xbSzluaq7NveEcYPHXZ1PN7Yf
v2QAAAFkwTcBAwAABAMARjBEAiAlnLsP6q6vc65OA5j+VdntLVcj9rhD73y5hS1F
uVwtsQIgJ7b9/U90tvOPh9XVIK1U1ZbRv9CQNVv4bQbrfyxvP9AAdQApPFGWVMg5
ZbqqUPxYB9S3b79Yeily3KTDDPTlRUf0eAAAAWTBNwL4AAAEAwBGMEQCICDKbBEA
rvxm3rTO5BY2ltXSY2X/0h68O9WC4Ym7O8MNAiB/+Ed4RHBIbeHMfpEtqin/bw5Q
T3GRZNAbGJFlFrNwHTANBgkqhkiG9w0BAQsFAAOCAQEANNWOBbrlwvEaa8GYc3FL
oOlcCgv6kuJN6jWOKfocX7DXDKMuJ9ImbGsWY0/Eb7ehNghiWBXRpCwpXP1tHXAv
GdnVfMajz7V6fdO3lX/T4jYHIaOzs46DPAchjBspDuPglqswQUD1X+FR57v/8hUe
JV3pPI1H1i3aNSBbg9q5CLpjSmZ5V0OJFQod+4Ru6evux0HyJTnXR+gdjujfnIm1
Fku2fMS4eM/tmMOjxQT1eY7KxSBOwTCfLIPls09Sa72UNAPC8bInT1KRR5wNXcNc
EYq3/Uh15XFI/y94xFgzvoQatuMBYBoju8+/64bupR7DcIr/z1TSy3JkymOjFJDp
qw==
-----END CERTIFICATE-----</textarea>
			</td>
			<td>
				<textarea class="form-control animated" rows="10"   name="p_pem2" id="p_pem2">-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----</textarea>
			</td>

		</tr>

		<tr>
			<td> <input class="btn btn-primary" type="button" name="submit" size="10" value="Perform PCSP Query" id="submit">  </td>
		</tr>

	</table>

	<div id="output"></div>

</form>

<hr>


<%@ include file="thanks.jsp"%>

<hr>

<h3 class="mt-4" id="theocsp"> <a href="https://8gwifi.org/docs/ocsp.jsp">Checkout the Tech blog on Online Certificate Status Protocol (OCSP) </a></h3>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
