<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<title>Strong Password Generator – Random, Secure, High‑Entropy (Online)</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Free online strong password generator. Create random, secure, high‑entropy passwords with length/entropy control, symbols, exclude similar characters, and instant strength meter. 100% client‑side."/>
    <meta name="keywords" content="strong password generator, random password generator, secure password generator, generate strong passwords online, high entropy passwords, password strength meter, exclude similar characters, copy password, create passwords online" />
    <link rel="canonical" href="https://8gwifi.org/passwdgen.jsp"/>
    <meta name="robots" content="index,follow" />
    <meta property="og:title" content="Strong Password Generator – Random, Secure, High‑Entropy (Online)"/>
    <meta property="og:description" content="Generate secure, random passwords with adjustable length or entropy. Exclude similar characters, require sets, and copy/download. Runs entirely in your browser."/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://8gwifi.org/passwdgen.jsp"/>
    <meta property="og:image" content="https://8gwifi.org/images/site/pass.png"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:title" content="Strong Password Generator – Random, Secure, High‑Entropy (Online)"/>
    <meta name="twitter:description" content="Free client‑side password generator with entropy controls, symbols, exclude‑similar, and strength meter."/>
    <meta name="twitter:image" content="https://8gwifi.org/images/site/pass.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

	<script type="application/ld+json">
    {
      "@context" : "https://schema.org",
      "@type" : "WebApplication",
      "name" : "Strong Password Generator (Online)",
      "image" : "https://8gwifi.org/images/site/pass.png",
      "url" : "https://8gwifi.org/passwdgen.jsp",
      "author" : {"@type" : "Person","name" : "Anish Nath"},
      "datePublished" : "2018-05-26",
      "applicationCategory" : "UtilitiesApplication",
      "operatingSystem" : "All",
      "downloadUrl" : "https://8gwifi.org/passwdgen.jsp",
      "softwareVersion" : "v1.1",
      "offers": {"@type":"Offer","price":"0","priceCurrency":"USD"},
      "featureList": [
        "Length or entropy based generation",
        "Exclude similar/ambiguous characters",
        "Require at least one from each selected set",
        "Avoid sequences and adjacent repeats",
        "Instant strength meter and crack‑time estimate",
        "Copy and download generated passwords"
      ]
    }
    </script>

    <script type="application/ld+json">
    {
      "@context":"https://schema.org",
      "@type":"FAQPage",
      "mainEntity":[
        {"@type":"Question","name":"How do I generate a strong password?","acceptedAnswer":{"@type":"Answer","text":"Select the character sets you need, choose a length (12–24+) or target entropy, then click Generate. Use the strength meter and crack‑time estimate to gauge security."}},
        {"@type":"Question","name":"Are passwords generated client‑side?","acceptedAnswer":{"@type":"Answer","text":"Yes. All generation happens in your browser using the Web Crypto API for randomness when available. Nothing is uploaded or stored on our servers."}},
        {"@type":"Question","name":"What does exclude similar characters do?","acceptedAnswer":{"@type":"Answer","text":"It removes visually ambiguous characters such as O/0, l/1, |, and certain symbols to make passwords easier to read and transcribe."}},
        {"@type":"Question","name":"Length vs entropy—what should I choose?","acceptedAnswer":{"@type":"Answer","text":"Both work. Length is straightforward (e.g., 16 chars). Entropy aims for a target bit strength. Higher entropy increases resistance to brute force attacks."}},
        {"@type":"Question","name":"How strong should my password be?","acceptedAnswer":{"@type":"Answer","text":"For most accounts, 12–16 characters with mixed sets is good. For high‑value accounts, consider 20+ characters. Always enable two‑factor authentication when possible."}}
      ]
    }
    </script>

<style>
  .pg .card-header{padding:.6rem .9rem;font-weight:600}
  .pg .card-body{padding:.9rem}
  .pg .form-group{margin-bottom:.6rem}
  .mono{font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace}
  .meter{height:.75rem;background:#e9ecef;border-radius:6px;overflow:hidden}
  .meter>span{display:block;height:100%;background:#dc3545}
  .meter.ok>span{background:#fd7e14}
  .meter.good>span{background:#28a745}
  .meter.excellent>span{background:#17a2b8}
  .small-muted{font-size:.9rem;color:#6c757d}
</style>

<script type="text/javascript">
    "use strict";

    var CHARACTER_SETS = [
      [true,  "Numbers",        "0123456789"],
      [true,  "Lowercase",      "abcdefghijklmnopqrstuvwxyz"],
      [false, "Uppercase",      "ABCDEFGHIJKLMNOPQRSTUVWXYZ"],
      [false, "ASCII symbols",  "!\"#$%" + String.fromCharCode(38) + "'()*+,-./:;" + String.fromCharCode(60) + "=>?@[\\]^_`{|}~"],
      [false, "Space",          " "]
    ];
    var AMBIGUOUS = new Set([...'O0oIl1|`~;:"' + "'" + '.,{}[]()<>/\\']);

    var passwordText = document.createTextNode("");
    var statisticsText = document.createTextNode("\u00A0");

    function init() {
    //document.getElementById("password").appendChild(passwordText);
    //document.getElementById("statistics").appendChild(statisticsText);
    var elements = document.createDocumentFragment();
    CHARACTER_SETS.forEach(function(entry, i) {
    var spanElem = document.createElement("span");
    var inputElem = document.createElement("input");
    inputElem.type = "checkbox";
    inputElem.checked = entry[0];
    inputElem.id = "charset-" + i;
    spanElem.appendChild(inputElem);
    var labelElem = document.createElement("label");
    labelElem.htmlFor = inputElem.id;
    labelElem.appendChild(document.createTextNode(" " + entry[1] + " "));
    var smallElem = document.createElement("small");
    smallElem.appendChild(document.createTextNode("(" + entry[2] + ")"));
    labelElem.appendChild(smallElem);
    spanElem.appendChild(labelElem);
    elements.appendChild(spanElem);
    elements.appendChild(document.createElement("br"));
    });
    var containerElem = document.getElementById("charset-checkboxes");
    if (!containerElem) { return; }
    containerElem.insertBefore(elements, containerElem.firstChild);
    }

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init);
    } else {
      init();
    }

    // The one and only function called from the HTML code
    function generate() {
    // Gather the character set
    var charsetStr = "";
    CHARACTER_SETS.forEach(function(entry, i) {
    if (document.getElementById("charset-" + i).checked)
    charsetStr += entry[2];
    });
    if (document.getElementById("custom").checked)
    charsetStr += document.getElementById("customchars").value;
    charsetStr = charsetStr.replace(/ /, "\u00A0");  // Replace space with non-breaking space

    // Convert to array and remove duplicate characters
    var charset = [];
    for (var i = 0; charsetStr.length > i; i++) {
    var c = charsetStr.charCodeAt(i);
    var s = null;
    if (0xD800 > c || c >= 0xE000)  // Regular UTF-16 character
    s = charsetStr.charAt(i);
    else if (c >= 0xD800 ? 0xDC00 > c : false) {  // High surrogate
    if (charsetStr.length > i + 1) {
    var d = charsetStr.charCodeAt(i + 1);
    if (d >= 0xDC00 ? 0xE000 > d : false) {
    // Valid character in supplementary plane
    s = charsetStr.substr(i, 2);
    i++;
    }
    // Else discard unpaired surrogate
    }
    } else if (d >= 0xDC00 ? 0xE000 > d : false)  // Low surrogate
    i++;  // Discard unpaired surrogate
    else
    throw "Assertion error";
    if (s != null ? charset.indexOf(s) == -1 : false)
    charset.push(s);
    }

    var password = "";
    var statistics = "";
    if (charset.length == 0)
    alert("Error: Character set is empty");
    else if (document.getElementById("by-entropy").checked ? charset.length == 1 : false)
    alert("Error: Need at least 2 distinct characters in set");
    else {
    var length;
    if (document.getElementById("by-length").checked)
    length = parseInt(document.getElementById("length").value, 10);
    else if (document.getElementById("by-entropy").checked)
    length = Math.ceil(parseFloat(document.getElementById("entropy").value) * Math.log(2) / Math.log(charset.length));
    else
    throw "Assertion error";

    if (0 > length)
    alert("Negative password length");
    else if (length > 10000)
    alert("Password length too large");
    else {
    for (var i = 0; length > i; i++)
    password += charset[randomInt(charset.length)];

    var entropy = Math.log(charset.length) * length / Math.log(2);
    var entropystr;
    if (70 > entropy)
    entropystr = entropy.toFixed(2);
    else if (200 > entropy)
    entropystr = entropy.toFixed(1);
    else
    entropystr = entropy.toFixed(0);
    statistics = "Length = " + length + " chars, \u00A0\u00A0Charset size = " + charset.length + " symbols, \u00A0\u00A0Entropy = " + entropystr + " bits";
    }
    }
    passwordText.data = password;
    statisticsText.data = statistics;
    document.getElementById("password").value=password
    document.getElementById("statistics").value=statistics


    //alert(document.getElementById("length").value)
    //alert(statistics)
    }

    // Returns a random integer in the range [0, n) using a variety of methods
    function randomInt(n) {
    var x = randomIntMathRandom(n);
    x = (x + randomIntBrowserCrypto(n)) % n;
    return x;
    }

    // Not secure or high quality, but always available
    function randomIntMathRandom(n) {
    var x = Math.floor(Math.random() * n);
    if (0 > x || x >= n)
    throw "Arithmetic exception";
    return x;
    }

    var cryptoObject = null;

    // Uses a secure, unpredictable random number generator if available; otherwise returns 0
    function randomIntBrowserCrypto(n) {
    if (cryptoObject == null)
    return 0;
    // Generate an unbiased sample
    var x = new Uint32Array(1);
    do cryptoObject.getRandomValues(x);
    while (x[0] - x[0] % n > 4294967296 - n);
    return x[0] % n;
    }

    function initCrypto() {
    var textNode = document.createTextNode("\u2717");
    var tgt = document.getElementById("crypto-getrandomvalues-entropy");
    if (tgt) { try { tgt.appendChild(textNode); } catch(e){} }

    if ("crypto" in window)
    cryptoObject = crypto;
    else if ("msCrypto" in window)
    cryptoObject = msCrypto;
    else
    return;

    if (!("getRandomValues" in cryptoObject) || !("Uint32Array" in window) || typeof Uint32Array != "function")
    cryptoObject = null;
    else
    textNode.data = "\u2713";
    }

    initCrypto();
    </script>

<!-- Advanced JS: enhanced generator, meter, copy/download. Overrides generate() safely. -->
<script>
  function clamp(v, lo, hi){ return Math.max(lo, Math.min(hi, v)); }
  function readPgOptions(){
    return {
      excludeSimilar: document.getElementById('exclude-similar') ? document.getElementById('exclude-similar').checked : false,
      requireEach: document.getElementById('require-each') ? document.getElementById('require-each').checked : false,
      noRepeatAdjacent: document.getElementById('no-repeat-adj') ? document.getElementById('no-repeat-adj').checked : false,
      avoidSequences: document.getElementById('avoid-seq') ? document.getElementById('avoid-seq').checked : false
    };
  }
  function buildPgCharset(opts){
    var charsetStr='';
    if(typeof CHARACTER_SETS!=='undefined'){
      CHARACTER_SETS.forEach(function(entry,i){ var el=document.getElementById('charset-'+i); if(el && el.checked) charsetStr+=entry[2]; });
    }
    var custom=document.getElementById('custom'); var customchars=document.getElementById('customchars');
    if(custom && custom.checked && customchars) charsetStr+=customchars.value;
    charsetStr=charsetStr.replace(/ /g,'\u00A0');
    var set=[]; for(var i=0;i<charsetStr.length;i++){ var ch=charsetStr[i]; if(opts.excludeSimilar && typeof AMBIGUOUS!=='undefined' && AMBIGUOUS.has(ch)) continue; if(set.indexOf(ch)===-1) set.push(ch); }
    return set;
  }
  function pickFromSet(sourceStr, masterSet, opts){
    var pool=[]; for(var i=0;i<sourceStr.length;i++){ var ch=sourceStr[i]; if(opts.excludeSimilar && typeof AMBIGUOUS!=='undefined' && AMBIGUOUS.has(ch)) continue; if(masterSet.indexOf(ch)!==-1 && pool.indexOf(ch)===-1) pool.push(ch); }
    if(pool.length===0) return masterSet[randomInt(masterSet.length)];
    return pool[randomInt(pool.length)];
  }
  function pgShuffle(arr){ for(var i=arr.length-1;i>0;i--){ var j=randomInt(i+1); var t=arr[i]; arr[i]=arr[j]; arr[j]=t; } return arr; }
  function wouldMakeSeq(out,c){ var n=out.length; if(n<2) return false; var a=out[n-2].charCodeAt(0), b=out[n-1].charCodeAt(0), d=c.charCodeAt(0); return (b===a+1 && d===b+1) || (b===a-1 && d===b-1); }
  function renderMeter(bits){ var meter=document.getElementById('entropyMeter'); if(!meter) return; var bar=meter.querySelector('span'); var pct=Math.max(0,Math.min(100,Math.round(bits/2))); meter.className='meter'; if(bits>=100) meter.classList.add('excellent'); else if(bits>=80) meter.classList.add('good'); else if(bits>=60) meter.classList.add('ok'); bar.style.width=pct+'%'; }
  function crackEstimate(bits){ var gps=1e10; var sec=Math.pow(2,bits)/gps; return humanTime(sec); }
  function humanTime(sec){ if(!isFinite(sec)||sec<=0) return 'instant'; var units=[['yr',31557600],['day',86400],['hr',3600],['min',60],['sec',1]]; var parts=[]; for(var i=0;i<units.length;i++){ var v=Math.floor(sec/units[i][1]); if(v>0){ parts.push(v+' '+units[i][0]+(v>1?'s':'')); sec-=v*units[i][1]; if(parts.length===2) break; } } return parts.length? parts.join(' ') : 'less than 1 sec'; }

  // Override original generate()
  function generate(){
    var opts=readPgOptions();
    var charset=buildPgCharset(opts);
    if(charset.length===0){ alert('Error: Character set is empty'); return; }
    if(document.getElementById('by-entropy') && document.getElementById('by-entropy').checked && charset.length<2){ alert('Error: Need at least 2 distinct characters in set'); return; }
    var length=16;
    if(document.getElementById('by-length') && document.getElementById('by-length').checked){
      var len=parseInt(document.getElementById('length').value,10)||16; length=clamp(len,4,2048);
    } else if(document.getElementById('entropy')){
      var bits=parseFloat(document.getElementById('entropy').value)||128; length=Math.ceil(bits*Math.log(2)/Math.log(charset.length)); length=clamp(length,4,2048); var lr=document.getElementById('lengthRange'); if(lr) lr.value=length; var ln=document.getElementById('length'); if(ln) ln.value=length;
    }
    var countEl=document.getElementById('count'); var count=countEl? clamp(parseInt(countEl.value,10)||1,1,200):1;
    var out=[]; for(var j=0;j<count;j++){ out.push(generateOne(length, charset, opts)); }
    var first=out[0]||''; var list=out.join('\n');
    var pw=document.getElementById('password'); if(pw) pw.value=first;
    var pl=document.getElementById('passwordList'); if(pl) pl.value=list;
    var bits=(Math.log(charset.length)||0)*length/Math.log(2); var stats='Length = '+length+' chars,  Charset size = '+charset.length+' symbols,  Entropy = '+(bits<70?bits.toFixed(2):bits<200?bits.toFixed(1):bits.toFixed(0))+' bits'; var st=document.getElementById('statistics'); if(st) st.value=stats; renderMeter(bits); var ct=document.getElementById('crackTime'); if(ct) ct.textContent=crackEstimate(bits);
  }

  function generateOne(length, charset, opts){
    var out=[]; var pre=[]; if(opts.requireEach && typeof CHARACTER_SETS!=='undefined'){ CHARACTER_SETS.forEach(function(entry,i){ var el=document.getElementById('charset-'+i); if(el && el.checked){ pre.push(pickFromSet(entry[2], charset, opts)); } }); }
    for(var i=pre.length;i<length;i++){ var c,guard=0; do{ c=charset[randomInt(charset.length)]; guard++; } while(((opts.noRepeatAdjacent && out.length>0 && out[out.length-1]===c) || (opts.avoidSequences && wouldMakeSeq(out,c))) && guard<1000); out.push(c); }
    out=out.concat(pre); pgShuffle(out); return out.join('');
  }

  function copyField(id, btn){ try{ var el=document.getElementById(id); var val=(el&&el.value)||''; if(navigator.clipboard && navigator.clipboard.writeText){ navigator.clipboard.writeText(val).then(function(){ showCopied(btn); }); } else { var ta=document.createElement('textarea'); ta.value=val; document.body.appendChild(ta); ta.select(); try{ document.execCommand('copy'); }catch(e){} document.body.removeChild(ta); showCopied(btn); } }catch(e){} }
  function showCopied(btn){ try{ if(window.jQuery && $(btn).tooltip){ $(btn).tooltip({title:'Copied!', trigger:'manual', placement:'top'}); $(btn).tooltip('show'); setTimeout(function(){ try{$(btn).tooltip('hide').tooltip('dispose');}catch(e){} },900); } else if(btn){ var orig=btn.getAttribute('data-orig')||btn.innerHTML; btn.setAttribute('data-orig',orig); btn.innerHTML='Copied!'; setTimeout(function(){ btn.innerHTML=btn.getAttribute('data-orig'); },900); } }catch(e){} }
  function toggleVisibility(id, btn){ try{ var el=document.getElementById(id); if(!el) return; if(el.type==='text'){ el.type='password'; if(btn) btn.textContent='👁️'; } else { el.type='text'; if(btn) btn.textContent='🙈'; } }catch(e){} }
  function downloadList(){ try{ var v=(document.getElementById('passwordList').value)||''; var blob=new Blob([v],{type:'text/plain'}); var a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='passwords.txt'; document.body.appendChild(a); a.click(); document.body.removeChild(a); }catch(e){} }
</script>

    </head>


<%@ include file="body-script.jsp"%>

<div class="container mt-4 pg">
  <h1 class="mb-2">Advanced Password Generator</h1>
  <p class="text-muted">Generate strong random passwords with configurable character sets, entropy/length, and smart constraints. All generation happens in your browser.</p>

  <form method="get" onsubmit="generate(); return false;">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-3">
          <h5 class="card-header">Character Sets</h5>
          <div class="card-body">
            <div id="charset-checkboxes" class="mb-2"></div>
            <div class="form-group form-inline">
              <div class="form-check mr-2">
                <input type="checkbox" class="form-check-input" id="custom" />
                <label class="form-check-label" for="custom">Custom</label>
              </div>
              <input type="text" class="form-control form-control-sm" id="customchars" placeholder="Add extra characters" oninput="document.getElementById('custom').checked=true;" />
            </div>
            <div class="form-group">
              <div class="form-check"><input class="form-check-input" type="checkbox" id="exclude-similar"><label class="form-check-label" for="exclude-similar">Exclude similar/ambiguous (O,0,l,1,|,{,},…)</label></div>
              <div class="form-check"><input class="form-check-input" type="checkbox" id="require-each" checked><label class="form-check-label" for="require-each">Require at least one from each selected set</label></div>
              <div class="form-check"><input class="form-check-input" type="checkbox" id="no-repeat-adj" checked><label class="form-check-label" for="no-repeat-adj">No adjacent repeats (e.g., aa, 11)</label></div>
              <div class="form-check"><input class="form-check-input" type="checkbox" id="avoid-seq"><label class="form-check-label" for="avoid-seq">Avoid simple sequences (abc, 123)</label></div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card mb-3">
          <h5 class="card-header">Length & Entropy</h5>
          <div class="card-body">
            <div class="form-group">
              <div class="form-check">
                <input type="radio" class="form-check-input" name="type" id="by-length" checked>
                <label class="form-check-label" for="by-length">Length</label>
              </div>
              <input type="range" class="custom-range" min="4" max="128" step="1" id="lengthRange" value="16" oninput="document.getElementById('length').value=this.value; document.getElementById('by-length').checked=true;" />
              <input type="number" class="form-control" min="4" max="512" value="16" step="1" id="length" oninput="document.getElementById('lengthRange').value=this.value; document.getElementById('by-length').checked=true;" />
            </div>
            <div class="form-group">
              <div class="form-check">
                <input type="radio" class="form-check-input" name="type" id="by-entropy">
                <label class="form-check-label" for="by-entropy">Target entropy (bits)</label>
              </div>
              <input type="number" class="form-control" min="32" value="128" step="1" id="entropy" oninput="document.getElementById('by-entropy').checked=true;" />
            </div>
            <div class="form-group">
              <label for="count">How many passwords</label>
              <input type="number" id="count" class="form-control" min="1" max="200" value="5">
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="card mb-3">
          <h5 class="card-header">Strength</h5>
          <div class="card-body">
            <div class="meter" id="entropyMeter"><span style="width:0%"></span></div>
            <span id="crypto-getrandomvalues-entropy" style="display:none"></span>
            <small class="small-muted">Crack time (at 1e10 guesses/sec): <span id="crackTime">–</span></small>
            <div class="form-group mt-2">
              <label for="statistics">Stats</label>
              <input type="text" class="form-control" id="statistics" readonly placeholder="Statistics will appear here">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <h5 class="card-header">Generate</h5>
      <div class="card-body">
        <div class="form-row align-items-center">
          <div class="col-md-8 mb-2">
            <div class="input-group input-group-lg">
              <input type="password" class="form-control mono" id="password" name="password" placeholder="First password appears here" readonly>
              <div class="input-group-append">
                <button type="button" class="btn btn-outline-secondary" title="Show/Hide" onclick="toggleVisibility('password', this)">👁️</button>
                <button type="button" class="btn btn-outline-secondary" title="Copy" onclick="copyField('password', this)">Copy</button>
              </div>
            </div>
          </div>
          <div class="col-md-4 mb-2 text-md-right">
            <button type="submit" class="btn btn-primary mr-2" onclick="generate(); return false;">Generate</button>
            <button type="button" class="btn btn-outline-secondary mr-2" onclick="copyField('passwordList', this)">Copy All</button>
            <button type="button" class="btn btn-outline-secondary" onclick="downloadList()">Download</button>
          </div>
        </div>
        <div class="form-group mt-3">
          <label for="passwordList">All passwords (one per line)</label>
          <textarea id="passwordList" class="form-control mono" rows="6" readonly></textarea>
        </div>
      </div>
    </div>
  </form>

  <hr>
  <p class="small-muted">Thanks to Project Nayuki for the original entropy-based generator idea. This version adds constraints, strength meter, copy/download, and multiple outputs.</p>

  <div id="output"></div>

  <hr>

  <div class="sharethis-inline-share-buttons"></div>
  <%@ include file="thanks.jsp"%>

  <hr>

  <%@ include file="footer_adsense.jsp"%>

  <h2 class="mt-4" id="thersaalgorithm">Strong password characteristics</h2>
  <p><strong>A strong password</strong> is random. Entropy measures randomness for the process, not the password alone. Longer passwords with larger character sets yield more entropy.</p>
  <ul>
    <li>Use at least 12–16 characters for accounts; more for high-value targets.</li>
    <li>Avoid reusing passwords and personal information.</li>
    <li>Prefer a password manager and MFA whenever possible.</li>
  </ul>
</div>
<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
