<!DOCTYPE html>
<html>
<head>
<title>Strong Random Password Generator Online with Entropy</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="This tool allows you to generate random passwords using true randomness,Strong Password Generator to create secure random passwords"/>
    <meta name="keywords"
          content="Password Generator, Online Password Generator, Random Password Generator, Secure Password Generator, Create Password, Generate Password, Strong password entropy" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->

	<script type="application/ld+json">
    {
    "@context" : "http://schema.org",
    "@type" : "SoftwareApplication",
    "name" : "Strong Random Password Generator Online with Entropy",
    "image" : "https://8gwifi.org/images/site/pass.png",
    "url" : "https://8gwifi.org/passwdgen.jsp",
    "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
    },
    "datePublished" : "2018-05-26",
    "applicationCategory" : [ "Password Generator", "Online Password Generator", "Random Password Generator", "Secure Password Generator", "Create Password", "Strong password entropy"],
    "downloadUrl" : "https://8gwifi.org/passwdgen.jsp",
    "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
    "requirements" : "Password Generator, Online Password Generator, Random Password Generator, Secure Password Generator, Create Password, Generate Password, Strong password entropy",
    "softwareVersion" : "v1.0"
    }
    </script>

<script type="text/javascript">
    "use strict";

    var CHARACTER_SETS = [
    [true, "Numbers", "0123456789"],
    [true, "Lowercase", "abcdefghijklmnopqrstuvwxyz"],
    [false, "Uppercase", "ABCDEFGHIJKLMNOPQRSTUVWXYZ"],
    [false, "ASCII symbols", "!\"#$%" + String.fromCharCode(38) + "'()*+,-./:;" + String.fromCharCode(60) + "=>?@[\\]^_`{|}~"],
    [false, "Space", " "],
    ];

    var passwordText = document.createTextNode("");
    var statisticsText = document.createTextNode("\u00A0");

    function init() {
    //document.getElementById("password").appendChild(passwordText);
    //document.getElementById("statistics").appendChild(statisticsText);
    var elements = document.createDocumentFragment();
    CHARACTER_SETS.forEach(function(entry, i) {
    var spanElem = document.createElement("span");
    var inputElem = document.createElement("input");
    inputElem.type = "checkbox";
    inputElem.checked = entry[0];
    inputElem.id = "charset-" + i;
    spanElem.appendChild(inputElem);
    var labelElem = document.createElement("label");
    labelElem.htmlFor = inputElem.id;
    labelElem.appendChild(document.createTextNode(" " + entry[1] + " "));
    var smallElem = document.createElement("small");
    smallElem.appendChild(document.createTextNode("(" + entry[2] + ")"));
    labelElem.appendChild(smallElem);
    spanElem.appendChild(labelElem);
    elements.appendChild(spanElem);
    elements.appendChild(document.createElement("br"));
    });
    var containerElem = document.getElementById("charset-checkboxes");
    containerElem.insertBefore(elements, containerElem.firstChild);
    }

    init();

    // The one and only function called from the HTML code
    function generate() {
    // Gather the character set
    var charsetStr = "";
    CHARACTER_SETS.forEach(function(entry, i) {
    if (document.getElementById("charset-" + i).checked)
    charsetStr += entry[2];
    });
    if (document.getElementById("custom").checked)
    charsetStr += document.getElementById("customchars").value;
    charsetStr = charsetStr.replace(/ /, "\u00A0");  // Replace space with non-breaking space

    // Convert to array and remove duplicate characters
    var charset = [];
    for (var i = 0; charsetStr.length > i; i++) {
    var c = charsetStr.charCodeAt(i);
    var s = null;
    if (0xD800 > c || c >= 0xE000)  // Regular UTF-16 character
    s = charsetStr.charAt(i);
    else if (c >= 0xD800 ? 0xDC00 > c : false) {  // High surrogate
    if (charsetStr.length > i + 1) {
    var d = charsetStr.charCodeAt(i + 1);
    if (d >= 0xDC00 ? 0xE000 > d : false) {
    // Valid character in supplementary plane
    s = charsetStr.substr(i, 2);
    i++;
    }
    // Else discard unpaired surrogate
    }
    } else if (d >= 0xDC00 ? 0xE000 > d : false)  // Low surrogate
    i++;  // Discard unpaired surrogate
    else
    throw "Assertion error";
    if (s != null ? charset.indexOf(s) == -1 : false)
    charset.push(s);
    }

    var password = "";
    var statistics = "";
    if (charset.length == 0)
    alert("Error: Character set is empty");
    else if (document.getElementById("by-entropy").checked ? charset.length == 1 : false)
    alert("Error: Need at least 2 distinct characters in set");
    else {
    var length;
    if (document.getElementById("by-length").checked)
    length = parseInt(document.getElementById("length").value, 10);
    else if (document.getElementById("by-entropy").checked)
    length = Math.ceil(parseFloat(document.getElementById("entropy").value) * Math.log(2) / Math.log(charset.length));
    else
    throw "Assertion error";

    if (0 > length)
    alert("Negative password length");
    else if (length > 10000)
    alert("Password length too large");
    else {
    for (var i = 0; length > i; i++)
    password += charset[randomInt(charset.length)];

    var entropy = Math.log(charset.length) * length / Math.log(2);
    var entropystr;
    if (70 > entropy)
    entropystr = entropy.toFixed(2);
    else if (200 > entropy)
    entropystr = entropy.toFixed(1);
    else
    entropystr = entropy.toFixed(0);
    statistics = "Length = " + length + " chars, \u00A0\u00A0Charset size = " + charset.length + " symbols, \u00A0\u00A0Entropy = " + entropystr + " bits";
    }
    }
    passwordText.data = password;
    statisticsText.data = statistics;
    document.getElementById("password").value=password
    document.getElementById("statistics").value=statistics


    //alert(document.getElementById("length").value)
    //alert(statistics)
    }

    // Returns a random integer in the range [0, n) using a variety of methods
    function randomInt(n) {
    var x = randomIntMathRandom(n);
    x = (x + randomIntBrowserCrypto(n)) % n;
    return x;
    }

    // Not secure or high quality, but always available
    function randomIntMathRandom(n) {
    var x = Math.floor(Math.random() * n);
    if (0 > x || x >= n)
    throw "Arithmetic exception";
    return x;
    }

    var cryptoObject = null;

    // Uses a secure, unpredictable random number generator if available; otherwise returns 0
    function randomIntBrowserCrypto(n) {
    if (cryptoObject == null)
    return 0;
    // Generate an unbiased sample
    var x = new Uint32Array(1);
    do cryptoObject.getRandomValues(x);
    while (x[0] - x[0] % n > 4294967296 - n);
    return x[0] % n;
    }

    function initCrypto() {
    var textNode = document.createTextNode("\u2717");
    document.getElementById("crypto-getrandomvalues-entropy").appendChild(textNode);

    if ("crypto" in window)
    cryptoObject = crypto;
    else if ("msCrypto" in window)
    cryptoObject = msCrypto;
    else
    return;

    if (!("getRandomValues" in cryptoObject) || !("Uint32Array" in window) || typeof Uint32Array != "function")
    cryptoObject = null;
    else
    textNode.data = "\u2713";
    }

    initCrypto();
    </script>

    </head>


<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Strong Random Password Generator </h1>

<p>Thanks to the Project Nayuki Main contributor which has created a Javascript function which generate a random Password with Entropy. This tool utilize the Project Nayuki Strong Random Password genertor algorith which is completely java script based </p>


<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>

<hr>


            <form method="get" onsubmit="generate(); return false;">


    <p  id="charset-checkboxes">
            <span><input type="checkbox" id="charset-0" />
            <label for="charset-0"> Numbers <small>(0123456789)</small></label></span><br />
            <span><input type="checkbox" checked="checked" id="charset-1" />
            <label for="charset-1"> Lowercase <small>(abcdefghijklmnopqrstuvwxyz)</small></label></span><br />
            <span><input type="checkbox" id="charset-2" />
            <label for="charset-2"> Uppercase <small>(ABCDEFGHIJKLMNOPQRSTUVWXYZ)</small></label></span><br />
            <span><input type="checkbox" id="charset-3" />
            <label for="charset-3"> ASCII symbols <small>(!"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~)</small></label></span><br /><span><input type="checkbox" id="charset-4" /><label for="charset-4"> Space <small>( )</small></label></span><br />
    <span><input type="checkbox" id="custom" /><label for="custom"> Custom:</label> <input type="text" id="customchars" value="" size="15" style="width:10em; font-size:80%; line-height:1.5" oninput="document.getElementById('custom').checked=true;" /></span>
            </p>

            <div  class="section"><div><table id="type">
            <tbody>
            <tr>
            <td><input type="radio" name="type" id="by-length" checked="checked" /> <label for="by-length">Length:</label></td>
    <td><input type="number" min="0" value="10" step="1" id="length" style="width:4" oninput="document.getElementById('by-length').checked=true;" /> characters</td>
            </tr>
            <tr>
            <td><input type="radio" name="type" id="by-entropy" />
            <label for="by-entropy">Entropy</label></td>
            <td><input type="number" class="form-control" min="0" value="128" step="any" id="entropy" style="width:4" oninput="document.getElementById('by-entropy').checked=true;" /> bits</td>
            </tr>
            </tbody>
            </table></div></div>

            <p>
            <input type="submit" class="btn btn-primary" value="Generate password"  />
    <input type="text" class="form-control" readonly="true" size="30" id="password" name="password" placeholder="your Password will appear here">
            <br/>
            Statistics <input type="text" class="form-control" id="statistics" readonly="true" size="100" name="statistics" placeholder="Statistics will appear here">
            </p>



            </form>


<div id="output"></div>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="footer_adsense.jsp"%>

<h2 class="mt-4" id="thersaalgorithm">Strong password charaterstic</h2>
<p><strong>A strong password</strong> is a random password. By "random". "Entropy" is the name of the mathematical concept by which this randomness can be expressed. Take care that "password entropy" is a property of the process which generated the password, and cannot be measured on the password itself</p>
<p><strong>Good passwords / passphrases:</strong></p>
<ul>
    <li>A strong password must be at least 8 characters long.</li>
    <li>It should not contain any of your personal information&mdash;specifically your real name, user name, or even your company name.</li>
    <li>It must be very unique from your previously used passwords.</li>
    <li>It should not contain any word spelled completely.</li>
    <li>It should contain characters from the four primary categories, including: uppercase letters, lowercase letters, numbers, and characters.</li>
    <li>should be 8 characters or longer, which forces you to use multiple words or extra symbols.</li>
    <li>should have upper case, lower case, symbols, and numbers; or at least three of those four groups.</li>
    <li>should not be a common word and should not be a common phrase.</li>
    <li>should not contain a date, a name, or other things that can be associated with you.</li>
    <li>should be created randomly or semi-randomly.</li>
    <li>should not be a suggestion when you type in the first few characters into Google.</li>
</ul>
<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>

