<!DOCTYPE html>
<html>
<head>
	<title>PBE Encryption Decryption tool Online</title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>

	<meta name="description"
		  content="PBE message encryption decryption Online, PBE file encryption decryption, jascrypt encyption pbe,java,php,pbe encryption decryption online, pbe file encyption,pbe file decryption, pbe java online, jascrypt encryption online, pbe decyption online, pbewithmd5anddes,pbewithmd5andrc2,pbewithsha1andrc2,pbewithsha1anddes,pbewithsha1andrc2_128,pbewithsha1andrc2_40,pbewithsha1andrc4_128,pbewithsha1andrc4_40,pbewithsha1anddesede,pbewithshaandidea-cbc,pbewithshaand128bitrc4,pbewithmd5andtripledes,pbewithshaand40bitrc4,pbewithmd5and128bitaes-cbc-openssl,pbewithmd5and192bitaes-cbc-openssl,pbewithmd5and256bitaes-cbc-openssl,pbewithsha256and128bitaes-cbc-bc,pbewithsha256and192bitaes-cbc-bc,pbewithsha256and256bitaes-cbc-bc,pbewithshaand128bitaes-cbc-bc,pbewithshaand128bitrc2-cbc,pbewithshaand192bitaes-cbc-bc,pbewithshaand2-keytripledes-cbc,pbewithshaand256bitaes-cbc-bc,pbewithshaand3-keytripledes-cbc,pbewithshaand40bitrc2-cbc,pbewithshaandtwofish-cbc "/>
	<meta name="keywords"
		  content="pbe,java,php,pbe encryption decryption online, pbe file encyption,pbe file decryption, pbe java online, jascrypt encryption online, pbe decyption online, pbewithmd5anddes,pbewithmd5andrc2,pbewithsha1andrc2,pbewithsha1anddes,pbewithsha1andrc2_128,pbewithsha1andrc2_40,pbewithsha1andrc4_128,pbewithsha1andrc4_40,pbewithsha1anddesede,pbewithshaandidea-cbc,pbewithshaand128bitrc4,pbewithmd5andtripledes,pbewithshaand40bitrc4,pbewithmd5and128bitaes-cbc-openssl,pbewithmd5and192bitaes-cbc-openssl,pbewithmd5and256bitaes-cbc-openssl,pbewithsha256and128bitaes-cbc-bc,pbewithsha256and192bitaes-cbc-bc,pbewithsha256and256bitaes-cbc-bc,pbewithshaand128bitaes-cbc-bc,pbewithshaand128bitrc2-cbc,pbewithshaand192bitaes-cbc-bc,pbewithshaand2-keytripledes-cbc,pbewithshaand256bitaes-cbc-bc,pbewithshaand3-keytripledes-cbc,pbewithshaand40bitrc2-cbc,pbewithshaandtwofish-cbc"/>

	<meta name="author" content="CRYPO" />
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

	<%@ include file="header-script.jsp"%>


	<%
		String[] validList =  { "PBEWITHHMACSHA1ANDAES_256", "PBEWITHHMACSHA224ANDAES_128",
				"PBEWITHHMACSHA224ANDAES_256", "PBEWITHHMACSHA256ANDAES_128", "PBEWITHHMACSHA256ANDAES_256",
				"PBEWITHHMACSHA384ANDAES_128", "PBEWITHHMACSHA384ANDAES_256", "PBEWITHHMACSHA512ANDAES_128",
				"PBEWITHHMACSHA512ANDAES_256", "PBEWITHMD5AND128BITAES-CBC-OPENSSL",
				"PBEWITHMD5AND192BITAES-CBC-OPENSSL", "PBEWITHMD5AND256BITAES-CBC-OPENSSL", "PBEWITHMD5ANDDES",
				"PBEWITHMD5ANDRC2", "PBEWITHMD5ANDTRIPLEDES", "PBEWITHSHA1ANDDES", "PBEWITHSHA1ANDDESEDE",
				"PBEWITHSHA1ANDRC2", "PBEWITHSHA1ANDRC2_128", "PBEWITHSHA1ANDRC2_40", "PBEWITHSHA1ANDRC4_128",
				"PBEWITHSHA1ANDRC4_40", "PBEWITHSHA256AND128BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC",
				"PBEWITHSHA256AND256BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC", "PBEWITHSHAAND128BITRC2-CBC",
				"PBEWITHSHAAND128BITRC4", "PBEWITHSHAAND192BITAES-CBC-BC", "PBEWITHSHAAND2-KEYTRIPLEDES-CBC",
				"PBEWITHSHAAND256BITAES-CBC-BC", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC", "PBEWITHSHAAND40BITRC2-CBC",
				"PBEWITHSHAAND40BITRC4", "PBEWITHSHAANDIDEA-CBC", "PBEWITHSHAANDTWOFISH-CBC" };
	%>


	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "PBE Encrypt/Decrypt Message",
  "image" : "https://8gwifi.org/images/site/pbe.png",
  "url" : "https://8gwifi.org/pbe.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-01-17",
  "applicationCategory" : [ "PBE ENcryption", "PBE Decryption" ,"PBEWITHHMACSHA1ANDAES_256", "PBEWITHHMACSHA224ANDAES_128",
				"PBEWITHHMACSHA224ANDAES_256", "PBEWITHHMACSHA256ANDAES_128", "PBEWITHHMACSHA256ANDAES_256",
				"PBEWITHHMACSHA384ANDAES_128", "PBEWITHHMACSHA384ANDAES_256", "PBEWITHHMACSHA512ANDAES_128",
				"PBEWITHHMACSHA512ANDAES_256", "PBEWITHMD5AND128BITAES-CBC-OPENSSL",
				"PBEWITHMD5AND192BITAES-CBC-OPENSSL", "PBEWITHMD5AND256BITAES-CBC-OPENSSL", "PBEWITHMD5ANDDES",
				"PBEWITHMD5ANDRC2", "PBEWITHMD5ANDTRIPLEDES", "PBEWITHSHA1ANDDES", "PBEWITHSHA1ANDDESEDE",
				"PBEWITHSHA1ANDRC2", "PBEWITHSHA1ANDRC2_128", "PBEWITHSHA1ANDRC2_40", "PBEWITHSHA1ANDRC4_128",
				"PBEWITHSHA1ANDRC4_40", "PBEWITHSHA256AND128BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC",
				"PBEWITHSHA256AND256BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC", "PBEWITHSHAAND128BITRC2-CBC",
				"PBEWITHSHAAND128BITRC4", "PBEWITHSHAAND192BITAES-CBC-BC", "PBEWITHSHAAND2-KEYTRIPLEDES-CBC",
				"PBEWITHSHAAND256BITAES-CBC-BC", "PBEWITHSHAAND3-KEYTRIPLEDES-CBC", "PBEWITHSHAAND40BITRC2-CBC",
				"PBEWITHSHAAND40BITRC4", "PBEWITHSHAANDIDEA-CBC", "PBEWITHSHAANDTWOFISH-CBC" ],
  "downloadUrl" : "https://8gwifi.org/pbe.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "PBE message encryption decryption Online, PBE file encryption decryption, jascrypt encyption pbe,java,php,pbe encryption decryption online, pbe file encyption,pbe file decryption, pbe java online, jascrypt encryption online, pbe decyption online, pbewithmd5anddes,pbewithmd5andrc2,pbewithsha1andrc2,pbewithsha1anddes,pbewithsha1andrc2_128,pbewithsha1andrc2_40,pbewithsha1andrc4_128,pbewithsha1andrc4_40,pbewithsha1anddesede,pbewithshaandidea-cbc,pbewithshaand128bitrc4,pbewithmd5andtripledes,pbewithshaand40bitrc4,pbewithmd5and128bitaes-cbc-openssl,pbewithmd5and192bitaes-cbc-openssl,pbewithmd5and256bitaes-cbc-openssl,pbewithsha256and128bitaes-cbc-bc,pbewithsha256and192bitaes-cbc-bc,pbewithsha256and256bitaes-cbc-bc,pbewithshaand128bitaes-cbc-bc,pbewithshaand128bitrc2-cbc,pbewithshaand192bitaes-cbc-bc,pbewithshaand2-keytripledes-cbc,pbewithshaand256bitaes-cbc-bc,pbewithshaand3-keytripledes-cbc,pbewithshaand40bitrc2-cbc,pbewithshaandtwofish-cbc ",
  "softwareVersion" : "v1.0"
}
</script>


	<script type="text/javascript">
		$(document).ready(function() {



			$('#cipherparameternew').change(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#plaintext').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#message').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#secretkey').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});


			$('#encrypt').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#decrypt').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#encryptparameter').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#decryptparameter').click(function(event) {
				$('#form').delay(200).submit()
			});


			$('#salt').keyup(function(event) {
				$('#form').delay(200).submit()
			});

			$('#rounds').keyup(function(event) {
				$('#form').delay(200).submit()
			});

			$('#password').keyup(function(event) {
				$('#form').delay(200).submit()
			});



			$('#form').submit(function(event) {
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "PBEFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});

		});
	</script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">PBE Encryption Decryption</h1>
<hr>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>



			<form id="form" method="POST">

				<b>Encrypt Message</b>
				<input class="form-control"  checked id="encryptparameter" type="radio" name="encryptdecryptparameter"
					   value="encrypt">

				<b>Decrypt Message</b>
				<input class="form-control"  id="decryptparameter" type="radio" name="encryptdecryptparameter"
					   value="decryprt">


				<input type="hidden" name="methodName" id="methodName"
					   value="PBEMESSAGE">


				<div class="form-group">
					<label for="password">Input Message</label>
					<textarea class="form-control" name="message" id="message" cols="10" rows="5"> </textarea>
				</div>


				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" name="password" class="form-control" id="password"  placeholder="8bits">
				</div>

				<div class="form-group">
					<label for="password">Rounds</label>
					<input type="text" name="rounds" class="form-control" id="rounds" value="1000" onkeypress="if ( isNaN(this.value + String.fromCharCode(event.keyCode) )) return false;" placeholder="1000">
				</div>


				<div class="form-group">
					<label for="cipherparameternew">PBE Ciphers</label>
				<select class="form-control" size="10" multiple name="cipherparameternew" id="cipherparameternew">
					<option selected value="PBEWITHHMACSHA1ANDAES_128">PBEWITHHMACSHA1ANDAES_128</option>
					<%
						for (int i = 0; i < validList.length; i++) {
							String param = validList[i];
					%>
					<option value="<%=param%>"><%=param%></option>
					<%}%>
				</select>
					</div>

			</form>

<hr>

<div id="output"></div>



<hr>

<a href="redirect-pbefile.jsp">Click Here for PBE file based ENcryption </a>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="footer_adsense.jsp"%>

<h2 class="mt-4" id="thepbealgo">PBE Encryption and Decryption</h2>
<p><strong>Password Based Encryption (PBE)</strong> is specified in e.g. RFC 2898 which specifies the "PKCS #5: Password-Based Cryptography Specification Version 2.0".</p>
<p><strong>How PBE Works?</strong></p>

<li>A user supplied password which is remembered by the user.</li>
<li>A long with that password text, a random number which is called salt is added and hashed.</li>
<li>Using this a AES or a DES encryption key is derived and encrypted.</li>
<li>The password text is shared between the two parties exchanging the encrypted content in a secure manner.</li>
<li>The receiver, uses the same password and salt and decrypts the content.</li>

<p><strong>PBKDF1 PBKDF1</strong> applies a hash function, which shall be MD2,MD5,SHA-1 to derive keys. The length of the derived key is bounded by the length of the hash function output, which is 16 octets for MD2 and MD5 and 20 octets for SHA-1. PBKDF1 is compatible with the key derivation process in PKCS #5</p>
<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>
