<!DOCTYPE html>
<html>
<head>
	<title>Online PGP Encryption Decryption tool using pgp public private keys </title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<meta name="description" content="pgp encryption, decryption tool, online free, simple PGP Online Encrypt and Decrypt. Tool for PGP Encryption and Decryption. PGP Key Generator Tool, pgp message format, openssl pgp generation, pgp interview question">
	<meta name="keywords"  content="pgp encryption, decryption tool, online free, simple PGP Online Encrypt and Decrypt. Tool for PGP Encryption and Decryption. PGP Key Generator Tool, pgp message format, openssl pgp generation, pgp interview question">
	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>

	<head>

		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
		<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online PGP Encryption Decryption tool using pgp public private keys",
  "image" : "https://8gwifi.org/images/site/pgp.png",
  "url" : "https://8gwifi.org/pgpencdec.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2018-10-23",
  "applicationCategory" : [ "pgp encryption decryption online", "online pgp key generator", "generate pgp message online", "simple PGP Online Encrypt and Decrypt.", "Tool for PGP Encryption and Decryption", "openssl pgp generation", "pgp decryption", "pgp keys encryption decryption online", "pgp message verification" ],
  "downloadUrl" : "https://8gwifi.org/pgpencdec.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
  "requirements" : "pgp encryption decryption online ,  online pgp key generator , generate pgp message online, simple PGP Online Encrypt and Decrypt , Tool for PGP Encryption and Decryption , openssl pgp generation ,  pgp decryption ,  pgp keys encryption decryption online , pgp message verification",
  "softwareVersion" : "v1.0"
}
</script>

	<script type="text/javascript">
		$(document).ready(function() {

			$('#encryptmsg').show();
			$('#descryptmsg').hide();
			$('#sendemail').hide();

			$('#encrypt').click(function (event)
			{
				//
				$('#encryptmsg').show();
				$('#descryptmsg').hide();

			});
			
			
			$('#sendemail').click(function(event) {

				var text = $('#output').find('textarea[name="comment"]').val();
				//alert(text)
				if ( text != null ) {
					$("#pgp_message").val(text);
				}
				
				if(text==undefined)
				{
					alert("Encrypt the message first ")
					return
				}
				
				var email=prompt("Please enter your email address");
				var validRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
				if(email.match(validRegex))
				{
					$("#methodName").val("PGP_SEND_ENCRYPTION_EMAIL");
					$("#email").val(email);
					$('#form').delay(200).submit()
					$("#methodName").val("PGP_ENCRYPTION_DECRYPTION");
				}
				else{
					alert("Invalid Email Address")
				}
			});
			
			

			$('#decrypt').click(function (event)
			{
				//
				$('#encryptmsg').hide();
				$('#descryptmsg').show();
				$('#sendemail').hide();

			});

			$('#decryptbutton').click(function(event) {
				$('#sendemail').hide();
				$('#form').delay(200).submit()
			});
			

			$('#p_cmsg').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#p_publicKey').keyup(function(event) {
				//
				// event.preventDefault();
				$('#form').delay(200).submit()
			});

			$('#form').submit(function (event)
			{
				//
				$('#output').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type: "POST",
					url: "PGPFunctionality", //this is my servlet
					// data: "lengthOfString=" +$('#lengthOfString').val()+"&trimignore="+$('#trimignore').val()+"&methodName="+$('#methodName').val(),
					data: $("#form").serialize(),
					success: function(msg){
						$('#output').empty();
						$('#output').append(msg);
						$('#sendemail').show();

					}
				});
			});
		});

	</script>
</head>

<%@ include file="body-script.jsp"%>
<h1 class="mt-4">PGP Encryption & Decryption</h1>
<hr>


<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>


<form id="form" class="form-horizontal" method="POST" enctype="application/x-www-form-urlencoded">
	<input type="hidden" name="methodName" id="methodName"
		   value="PGP_ENCRYPTION_DECRYPTION">

    <input type="hidden" name="j_csrf" value="<%=request.getSession().getId() %>" >
    <input type="hidden" id="email" name="email" value="">
    <input type="hidden" id="pgp_message" name="pgp_message" value="">
	<p><strong>Encrypt/Decrypt PGP Message</strong></p>

	<div class="radio">
		<label>
			<input checked id="encrypt" type="radio" name="encryptdecrypt" value="encrypt">
			Encrypt message
		</label>
	</div>

	<div class="radio">
		<label>
			<input id="decrypt" type="radio" name="encryptdecrypt" value="decrypt">
			Decrypt message
		</label>
	</div>


	<div id="descryptmsg">

		<b>PGP Message</b> <textarea class="form-control animated" rows="10" cols="50" id="p_pgpmessage" name="p_pgpmessage" placeholder="-----BEGIN PGP MESSAGE-----
Version: BCPG v1.58

hIwDmCS94uDDx9kBA/9hH8V38pyzUOvcBPa5Rcv38doT3zJ/tvhxI/5h+1tF5sPg
nmeQDs7D829eR9x6nMos395hbJZezx+iGn1tfdhBoy0FpH3KHTNY+0qLNu37qVwU
ogXF+tQ3umq/CUqQgpETHS/awvuNhvRfo240u+tmrXUZl18fDdAVg6BKpgMmH9Ju
AVPnVI+0DoCls0IKZSegwO5T0Cj/D/fJuT7VSxCHCtJ6aAS1F8TAfn98oiik3CzS
9oBh+KHqawk3supbiXPmpJdyV45oOfV4fsVPnP8zbtLtQNv6EBO+mEwday9Hq2xo
+sxxQx0poYZDI7sq4i8=
=v0g9
-----END PGP MESSAGE-----"></textarea>
		<b>PGP Private Key </b> <textarea class="form-control animated" rows="10" cols="50" id="p_privateKey" name="p_privateKey" placeholder="-----BEGIN PGP PRIVATE KEY BLOCK-----
Version: BCPG v1.58

lQH+BFojjHkBBACJghEFJ0kOeHnvpp5ADbI8r2ZtkLAtbBiARKZsiW4dsVrpbify
lUyFEqm5CzhKuAjiJcxtH4bq7lFgTNvgDWs6uY5MS62Jh1+AMANkOo73d8RPAdbl
Y6k9ExCsmbZgcHrBLMFMW/rzsFS3Vil6XMkl7SEIaClgFFcxu3ubhGsMlwARAQAB
/gQDApBPMSbTsvQjYNgi3vBAHHkJ5YurFXAPWeZ87jXJ/DdruVoK5cXqdgg4g5Sz
9ZBE2rkcJ7qL54I2zMEZaXmQeqANqfhRuJH2E8DlRW6wbt2jU5WorD/a/5iTcjGu
/AfBRIktji4LW/BcsKnXirDZK12IjxYjyCHv4AY3P/v6Osf91zdmg9C1S7vuwz5I
2hXqJBj7jhyZ2y/C6CP84Rnr7XyvqQxNV1BDIJH21z4er15axuY23pywA6I8Qqwm
I5vaSmJlBHwpQ22Fh5EkltMIHNqcpQ50HoNL/XKwXy1PvgyEA79462RvTY6Bj6JE
WPEHCFa9mvuubeXOO7D1S9pM3ygpuwQiR9F4EFCWU5m5xR1Wr2QlftiJI7Fhyg7M
ttkyjEW0AX6RbGgbhKnCOaiDO7CJpSULwwkMfOGAWYwrsxcJh8LqZVEUVrH//Ajo
kNPN+u9X0U/g4Vt5aKuEygFkF0QcLruOW/BUgpH4KFUWtAVhbmlzaIicBBABAgAG
BQJaI4x5AAoJEJgkveLgw8fZR3sD/1LbEpN5co+Rpx8qEx2TM/rFBaRZWp+2oKh3
+qVdj4HW/TjAlWrjMJfW4z2PR0h0IP2t4E0OajavbcYiNuBbKNkNwEel3FZNsEMU
uqayfYpj4tZ6V2qwsGZBIFi11i7kCx6MUVh3/aJVKnluz5MEJSdSvSG/OaQk78de
gze0MEL/
=5jHf
-----END PGP PRIVATE KEY BLOCK-----"></textarea>
		<br/>
		<b>Passphrase</b><input id="p_passpharse" class="form-control" type="password" name="p_passpharse"
								value="" placeholder="">
		<br/>
		<input type="button" class="btn btn-primary"  id="decryptbutton" name="decryptbutton" value="Decrypt PGP Message">
	</div>

	<div id="encryptmsg">
		<b>Clear Text Message </b> <textarea class="form-control animated" rows="5" cols="10" placeholder="Type Something Here..."  name="p_cmsg" id="p_cmsg"></textarea>
		<b>PGP Public Key </b><textarea rows="10" cols="50" placeholder="-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.58

mI0EWiOMeQEEAImCEQUnSQ54ee+mnkANsjyvZm2QsC1sGIBEpmyJbh2xWuluJ/KV
TIUSqbkLOEq4COIlzG0fhuruUWBM2+ANazq5jkxLrYmHX4AwA2Q6jvd3xE8B1uVj
qT0TEKyZtmBwesEswUxb+vOwVLdWKXpcySXtIQhoKWAUVzG7e5uEawyXABEBAAG0
BWFuaXNoiJwEEAECAAYFAlojjHkACgkQmCS94uDDx9lHewP/UtsSk3lyj5GnHyoT
HZMz+sUFpFlan7agqHf6pV2Pgdb9OMCVauMwl9bjPY9HSHQg/a3gTQ5qNq9txiI2
4Fso2Q3AR6XcVk2wQxS6prJ9imPi1npXarCwZkEgWLXWLuQLHoxRWHf9olUqeW7P
kwQlJ1K9Ib85pCTvx16DN7QwQv8=
=Qteg
-----END PGP PUBLIC KEY BLOCK-----"  name="p_publicKey" id="p_publicKey">-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.58

mI0EWiOMeQEEAImCEQUnSQ54ee+mnkANsjyvZm2QsC1sGIBEpmyJbh2xWuluJ/KV
TIUSqbkLOEq4COIlzG0fhuruUWBM2+ANazq5jkxLrYmHX4AwA2Q6jvd3xE8B1uVj
qT0TEKyZtmBwesEswUxb+vOwVLdWKXpcySXtIQhoKWAUVzG7e5uEawyXABEBAAG0
BWFuaXNoiJwEEAECAAYFAlojjHkACgkQmCS94uDDx9lHewP/UtsSk3lyj5GnHyoT
HZMz+sUFpFlan7agqHf6pV2Pgdb9OMCVauMwl9bjPY9HSHQg/a3gTQ5qNq9txiI2
4Fso2Q3AR6XcVk2wQxS6prJ9imPi1npXarCwZkEgWLXWLuQLHoxRWHf9olUqeW7P
kwQlJ1K9Ib85pCTvx16DN7QwQv8=
=Qteg
-----END PGP PUBLIC KEY BLOCK-----</textarea>
		<hr>
	</div>
	<div id="output"></div>
	</b>
<hr>
<div>
<input type="button" class="btn btn-primary"  id="sendemail" name="sendemail" value="Send Email">
</div>

</form>
<hr>

 <div class="card my-4">
     <h5 class="card-header">Other PGP Tools</h5>
     <ul>
         <li><a href="pgpencdec.jsp">PGP Encryption/Decryption  </a></li>
         <li><a href="pgpkeyfunction.jsp">PGP Key Generation  </a></li>
         <li><a href="PGPFunctionality?invalidate=yes">PGP Signature Verifier  </a></li>
         <li><a href="pgpdump.jsp">PGP KeyDumper</a></li>
         <li><a href="pgp-upload.jsp">PGP Send Encrypt files</a></li>
         <li><a href="pgp-file-decrypt.jsp">PGP Decrypt files</a></li>
     </ul>
 </div>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>
<hr>

	<h2 class="mt-4" id="thersaalgorithm"><a href="docs/gpg.jsp">Pretty Good Privacy</a></h2>

<p><strong>Pretty Good Privacy or PGP</strong> is a popular program used to encrypt and decrypt email over the Internet, as well as authenticate messages with digital signatures and encrypted stored files.</p>
<p><strong>PGP</strong> and similar software follow the <strong>OpenPGP</strong> standard (RFC 4880) for encrypting and decrypting data.</p>
<p>When we generate a public-private keypair in P<strong>GP, it gives us the option of selecting DSA or RSA</strong>, This tool generate RSA keys. RSA is an algorithm.PGP is originally a piece of software, now a standard protocol, usually known as OpenPGP.</p>
<p><strong>PGP Vs OpenPGP</strong><br />PGP is a proprietary encryption solution, and the rights to its software are owned by Symantec</p>

	<p> <a href="/docs/gpg.jsp"> Learn More about GPG here</a>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>