<!DOCTYPE html>
<html>
<head>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online Ping Ipv4/IpV6 Address Onlines",
  "image" : "https://github.com/anishnath/crypto-tool/blob/master/ping.png",
  "url" : "https://8gwifi.org/pingfunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2017-12-25",
  "applicationCategory" : [ "ping online", "ping6 online", "curl online", "curl ipv6 online", ""],
  "downloadUrl" : "https://8gwifi.org/pingfunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Online Ipv4/IPv6 Ping Trace Tool, check if a host or IP (IPv6) is reachable from the internet and know the IP address Location and geolocation",
  "softwareVersion" : "v1.0"
}
</script>
    <title>Online Ping Ipv4/IpV6 Address Online</title>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta name="description" content="Online Ipv4/IPv6 Ping Trace Tool, check if a host or IP (IPv6) is reachable from the internet and know the IP address Location and geolocation " />
<meta name="keywords" content="ping online,ping6 online,curl online,IP, IPv6, IPNG, online ping, ttl, test, check, packet, echo, lag, host, count, ttl, mtu,icmp,icmpv6,ping6,ip address, location, geolocation,IP Address Lookup, IP Locator, IP Address Locator, IP Location, IP Lookup" />
<%@ include file="include_css.jsp" %> 
<script type="text/javascript">
        $(document).ready(function() {
            $('#executeMethod').click(function (event)
            {
 			$('#form').delay(200).submit()
            });
                    
            $('#form').submit(function (event)
                    {
                    //	
                  $('#output').html('<img src="images/712.GIF"> loading...');
         			 event.preventDefault();
                        $.ajax({
                            type: "POST",
                            url: "NetworkFunctionality", //this is my servlet
                
                           data: $("#form").serialize(),
                            success: function(msg){    
                            		    $('#output').empty();
                                     $('#output').append(msg);
                                     
                            }
                        }); 
                    });
        });
   
    </script>
</head>
<body>
<div id="page">
<%@ include file="include.jsp" %> 
	<div id="loading" style="display: none;">
		<img src="images/712.GIF" alt="" />Loading!
	</div>
	<article id="contentWrapper" role="main">
			<section id="content">
	<form id="form" method="POST">
		<input type="hidden" name="methodName" id="methodName" value="NETWORKPINGCOMMAND">
		<input type="hidden" name="getClientIpAddr" id="methodName" value="true">
		<fieldset name="Ping v4/v6 Address Online ">
			<legend>
				<B>Online Ping IPv4/IPv6 Address </B>
			</legend>
			Give an Ipv4 or Ipv6 Address<input id="ipaddress" type="text" name="ipaddress" value="ipv6.google.com" size="60">
            <br>
            To Query Ipv6 your local interface must have Ipv6 Address
            <input type="button" id="executeMethod" name="ping"
				value="Click Ping" size="200"> <br>
		</fieldset>
		<div id="output"></div>
	</form>
                <br/>
                <br/>

                <br/>
                <br/>
                <p>Examples of IP addresses and their byte representations:</p>

                <%@ include file="footer.jsp"%>
		</section>
		</article>
		
	</div>
</body>
</html>