<!DOCTYPE html>
<html>
<head>
    <title>Online QRgenerator</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Generate qr code generator"/>
    <meta name="keywords" content="qr code generator, generare qr code javascript, what is QR code"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>
    <script src='https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js'></script>



    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online QR code generator",
  "image" : "https://8gwifi.org/images/site/qrcodegen.png",
  "url" : "https://8gwifi.org/qrcodegen.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-02-09",
  "applicationCategory" : [ "online qr generate" , "generate qr code online", "QR code online" , "generate QR code" ],
  "downloadUrl" : "https://8gwifi.org/qrcodegen.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Generate QR (Quick Response) code ",
  "softwareVersion" : "v1.0"
}
</script>






    <script type="text/javascript">
        $(document).ready(function() {

            $('#text').keyup(function (event)
            {
                makeCode();

            });

            $('#button').click(function (event)
            {
                makeCode();

            });

        });

    </script>
</head>
<%@ include file="body-script.jsp"%>


<h1 class="mt-4">QRCode Generator</h1>
<p>This tool will help use to generate the QR code . Did you QR means Quick Response Code first designed for the automotive industry in Japan.</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>


<div class="col-sm-10">
    <label for="text">Type you text and QR code will be genrated </label>
    <input id="text" type="text" placeholder="Type your text here" value="8gwifi.org"  class="form-control" >
</div>

<hr>

<div id="qrcode"></div>
<!-- partial -->

<script type="text/javascript">

    var qrcode = new QRCode("qrcode");
    qrcode.clear();

    function makeCode () {
        var elText = document.getElementById("text");

        if (!elText.value) {
            alert("Input a text To Generate the QR Code");
            elText.focus();
            return;
        }

        qrcode.makeCode(elText.value);
    }



    $("#text").
    on("blur", function () {
        makeCode();
    }).
    on("keydown", function (e) {
        if (e.keyCode == 13) {
            makeCode();
        }
    });


</script>


<div id="output"></div>

<hr>



<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>