<!DOCTYPE html>
<html>
<head>

	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
	<title>Online Subnet Calculator</title>
	<meta name="description" content="online Subnet calculator generate ip range from the given subnet mask, cidr calculator of the rfc defined networks" />
	<meta name="keywords" content="online ip subnet calculator, ip Subnet Calculator, subnet calculator, subnet mask, free, ip, subnet,cidr, subnetting, supernetting, network" />

	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

	<%@ include file="header-script.jsp"%>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online subnet Calculator",
  "image" : "https://8gwifi.org/images/site/subnet.png",
  "url" : "https://8gwifi.org/SubnetFunctions.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2017-09-25",
  "applicationCategory" : [ "online subnet calculator" , "cidr range calculator", "ip subnet calculator" ],
  "downloadUrl" : "https://8gwifi.org/SubnetFunctions.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "ip subnet calculate, generate ip address from given cidr range",
  "softwareVersion" : "v1.0"
}
</script>

	<script type="text/javascript">
		$(document).ready(function() {


			$('#ctrTitles').change(function() {
				pem = $(this).val();
				$("#pem").val(pem);
			});


			$('#submit').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#form').submit(function(event) {
				//
				$('#output1').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "SubnetFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output1').empty();
						$('#output').append(msg);

					}
				});
			});
		});
	</script>
</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">Subnet Calculator</h1>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>


<p>The number of available network and host addresses are derived from the number of bits used for subnet masking. <strong>CIDR notation</strong> is a compact representation of an IP address and its associated routing prefix.</p>

<form id="form" method="POST">
	<input type="hidden" name="methodName" id="methodName" value="SUBNETCOMMAND">
	<div class="form-group row">
		<label for="subnet" class="col-sm-2 col-form-label">Give Subnet (CIDR)</label>
		<div class="col-sm-10">
			<input type="text"  class="form-control" id="subnet" name="subnet" value="192.168.1.23/28">
		</div>
	</div>

	<div class="form-check form-check-inline">
		<input class="form-check-input" type="radio" name="encoding" id="encoding" value="Y">
		<label class="form-check-label" for="encoding">Include IP Address</label>
	</div>
	<div class="form-check form-check-inline">
		<input class="form-check-input" type="radio" checked name="encoding" id="encoding1" value="N">
		<label class="form-check-label"  for="encoding1">Exclude IP Address</label>
	</div>

	<div class="row" role="group">
		<input class="btn btn-primary" type="submit" value="Submit">
	</div>

</form>
<hr>

<div class="row">
	<textarea class="form-control" id="output" readonly rows="10"></textarea>
</div>

<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<p><strong>A broadcast address</strong> is a logical address at which all devices connected to a multiple-access communications network are enabled to receive datagrams. <br />A message sent to a broadcast address is typically received by all network-attached hosts, rather than by a specific host</p>
<p>For example A /24 network may be divided into the following subnets by increasing the subnet mask successively by one bit. This affects the total number of hosts that can be addressed in the /24 network</p>
<table class="table table-striped">
	<thead>
	<tr>
		<th>Prefix size</th>
		<th>Subnet mask</th>
		<th>Available<br />subnets</th>
		<th>Usable hosts<br />per subnet</th>
		<th>Total<br />usable hosts</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>/24</td>
		<td><code>255.255.255.0</code></td>
		<td>1</td>
		<td>254</td>
		<td>254</td>
	</tr>
	<tr>
		<td>/25</td>
		<td><code>255.255.255.128</code></td>
		<td>2</td>
		<td>126</td>
		<td>252</td>
	</tr>
	<tr>
		<td>/26</td>
		<td><code>255.255.255.192</code></td>
		<td>4</td>
		<td>62</td>
		<td>248</td>
	</tr>
	<tr>
		<td>/27</td>
		<td><code>255.255.255.224</code></td>
		<td>8</td>
		<td>30</td>
		<td>240</td>
	</tr>
	<tr>
		<td>/28</td>
		<td><code>255.255.255.240</code></td>
		<td>16</td>
		<td>14</td>
		<td>224</td>
	</tr>
	<tr>
		<td>/29</td>
		<td><code>255.255.255.248</code></td>
		<td>32</td>
		<td>6</td>
		<td>192</td>
	</tr>
	<tr>
		<td>/30</td>
		<td><code>255.255.255.252</code></td>
		<td>64</td>
		<td>2</td>
		<td>128</td>
	</tr>
	<tr>
		<td>/31</td>
		<td><code>255.255.255.254</code></td>
		<td>128</td>
		<td>2&nbsp;<sup>*</sup></td>
	</tr>
	</tbody>
</table>
<p>&nbsp;</p>

<p>The following special addresses and networks exist in IPv4:</p>
<table class="table table-striped">
	<tbody>
	<tr>
		<td>0.0.0.0</td>
		<td>the "ANY" address that is used by programs to speak to all network interfaces, it is never used directly. The whole network 0.*.*.* is reserved for special purposes (like DHCP).</td>
	</tr>
	<tr>
		<td>10.*.*.*<br />172.16.*.*&nbsp;-&nbsp;172.31.*.*<br />192.168.*.*</td>
		<td>RFC Definend private address</td>
	</tr>
	<tr>
		<td>127.0.0.1</td>
		<td>is the localhost address The entire 127.*.*.* network is reserved for (host-)local networking.</td>
	</tr>
	<tr>
		<td>169.254.*.*</td>
		<td>Link-Local addresses. These are automatically generated by some operating systems and (e.g. MacOS and Linux with Avahi installed) and are only usable for local communication in the LAN segment.</td>
	</tr>
	<tr>
		<td>198.18.*.*&nbsp;-&nbsp;198.19.*.*</td>
		<td>Network benchmark tests, this should never be used in production networks.</td>
	</tr>
	<tr>
		<td>198.51.100.*<br />203.0.113.*</td>
		<td>TEST-NET-2, Documentation and examples<br />TEST-NET-3, Documentation and examples</td>
	</tr>
	<tr>
		<td>224.*.*.*</td>
		<td>Multicasts (former Class D network) - e.g. there is no default gateway or broadcast for multicasting</td>
	</tr>
	<tr>
		<td>240.0.0.0/4</td>
		<td>Reserved (former Class E network)</td>
	</tr>
	<tr>
		<td>255.255.255.255</td>
		<td>Link Broadcast - this is sent to all hosts on the same network link, but does not cross routers</td>
	</tr>
	</tbody>
</table>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>