<!DOCTYPE html>
<html>
<head>
    <title>Online uuid/guid generator</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="Generate uuid, guid online"/>
    <meta name="keywords" content="uuid generator, generare uuid javascript, rfc compliant uuid Generator"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>



    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online uuid/guid generator",
  "image" : "https://8gwifi.org/images/site/uuid.png",
  "url" : "https://8gwifi.org/uuid.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-02-08",
  "applicationCategory" : [ "online uuid generate" , "generate uuid online", "uuid online" , "guid" ],
  "downloadUrl" : "https://8gwifi.org/uuid.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu",
  "requirements" : "Generate uuid, guid online",
  "softwareVersion" : "v1.0"
}
</script>



    <script type="text/javascript">

        function bytesToHexString(bytes)
        {
            if (!bytes)
                return null;

            bytes = new Uint8Array(bytes);
            var hexBytes = [];

            for (var i = 0; i < bytes.length; ++i) {
                var byteString = bytes[i].toString(16);
                if (byteString.length < 2)
                    byteString = "0" + byteString;
                hexBytes.push(byteString);
            }

            return hexBytes.join("");
        }

        function hexStringToUint8Array(hexString)
        {
            if (hexString.length % 2 != 0)
                throw "Invalid hexString";
            var arrayBuffer = new Uint8Array(hexString.length / 2);

            for (var i = 0; i < hexString.length; i += 2) {
                var byteValue = parseInt(hexString.substr(i, 2), 16);
                if (byteValue == NaN)
                    throw "Invalid hexString";
                arrayBuffer[i/2] = byteValue;
            }

            return arrayBuffer;
        }

        function uuidv4()
        {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

        function nonRFCuuidv4()
        {
            return 'xxxxxxxx-xxxx-xxxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

        function generateUUID() {
            // body...
            var uuid = document.getElementById("uuid").value;
            var rfc = document.getElementsByName('rfc');

            for(i = 0; i < rfc.length; i++)
            {
                if(rfc[i].checked)
                {
                    rfc = rfc[i].value
                }
            }

            if ((!rfc || 0 === rfc.length))
            {
                rfc='nonrfc'
            }


            var text='';
            for (i = 0; i < uuid; i++) {

                if('nonrfc' === rfc )
                {
                    text = text + nonRFCuuidv4() + "\n"
                }else{
                    text = text +  uuidv4() + "\n"
                }

            }
            var x = document.createElement("TEXTAREA");
            x.value = text
            x.rows=10
            x.readOnly=true
            x.className='form-control'
            $('#output').empty();
            $('#output').append(x);
        }


    </script>


    <script type="text/javascript">
        $(document).ready(function() {
            $('#uuid').keyup(function (event)
            {
                generateUUID()

            });

            $('#button').click(function (event)
            {
                generateUUID()

            });

        });

    </script>
</head>
<%@ include file="body-script.jsp"%>


<h1 class="mt-4">UUID Generator</h1>
<p>This tool will help you to generate Uniform Resource Name namespace for
    UUIDs (Universally Unique IDentifier), also known as GUIDs (Globally
    Unique IDentifier).  A UUID is 128 bits long, and requires no central
    registration process</p>
<hr>

<div id="loading" style="display: none;">
    <img src="images/712.GIF" alt="" />Loading!
</div>



<form id="form">



    <fieldset class="form-group">


        <div class="form-group">
            <input class="form-check-input" type="radio" name="rfc" id="rfc" checked value="rfc">
            <label class="form-check-label" for="exampleRadios1">
                RFC4122 version 4
            </label>
        </div>
        <div class="form-group">
            <input class="form-check-input" type="radio" name="rfc" id="rfc" value="nonrfc">
            <label class="form-check-label" for="exampleRadios2">
                Generic
            </label>
        </div>

        <div class="form-group">
            <label for="uuid">How Many UUID ?</label>
            <input type="text" name="uuid" class="form-control" id="uuid" value="10" onkeypress="if ( isNaN(this.value + String.fromCharCode(event.keyCode) )) return false;" placeholder="1000">
        </div>

        <div class="col-sm-10">
            <button type="button" id="button" class="btn btn-primary">Generate UUID</button>
        </div>



    </fieldset>


</form>

<div id="output"></div>

<hr>



<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>