<!DOCTYPE html>
<html>
<head>
    <title>online websocket test client</title>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
    <meta name="description" content="test your websocket server online"/>
    <meta name="keywords" content="websocket test client, online websocket server tester"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%@ include file="header-script.jsp"%>


    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {
            "@context" : "http://schema.org",
            "@type" : "SoftwareApplication",
            "name" : "Websocket Client test the websocket server",
            "image" : "https://8gwifi.org/images/site/websocket-client.png",
            "url" : "https://8gwifi.org/websocket-client.jsp",
            "author" : {
                "@type" : "Person",
                "name" : "Anish Nath"
            },
            "datePublished" : "2024-05-05",
            "applicationCategory" : [ "websocket client test" , "online websocket client test", "test websocket server online"],
            "downloadUrl" : "https://8gwifi.org/websocket-client.jsp",
            "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,AWS",
            "requirements" : "test websocket server online",
            "softwareVersion" : "v1.0"
        }
    </script>

    <script>
        let websocket;

        function connect() {
            let serverUrl = document.getElementById('serverUrl').value;
            if (serverUrl.startsWith('http://')) {
                serverUrl = serverUrl.replace('http://', 'ws://');
            } else if (serverUrl.startsWith('https://')) {
                serverUrl = serverUrl.replace('https://', 'wss://');
            } else if (!serverUrl.startsWith('ws://') && !serverUrl.startsWith('wss://')) {
                alert('Invalid URL. Please enter a URL that starts with "http://", "https://", "ws://", or "wss://".');
                return;
            }

            // Clear the messages container
            document.getElementById('messages').innerHTML = '';

            websocket = new WebSocket(serverUrl);

            websocket.onopen = function() {
                document.getElementById('status').innerText = 'Status: Connected';
                document.getElementById('status').classList.replace('alert-secondary', 'alert-success');
                document.getElementById('connectionControls').style.display = 'block';
            };

            websocket.onmessage = function(event) {
                const message = document.createElement('div');
                message.textContent = 'Received: ' + event.data;
                document.getElementById('messages').appendChild(message);
            };

            websocket.onclose = function() {
                document.getElementById('status').innerText = 'Status: Disconnected';
                document.getElementById('status').classList.replace('alert-success', 'alert-secondary');
                document.getElementById('connectionControls').style.display = 'none';
            };

            websocket.onerror = function(error) {
                console.error('WebSocket Error: ' + error);
                const message = document.createElement('div');
                // message.textContent = 'Error: ' + error;
                message.innerHTML = `<strong>Error:</strong> ${JSON.stringify(event, null, 2)}`;
                console.log(message)
                document.getElementById('messages').appendChild(message);
            };
        }

        function sendMessage() {
            const message = document.getElementById('messageInput').value;
            websocket.send(message);
            const sentMessage = document.createElement('div');
            sentMessage.textContent = 'Sent: ' + message;
            document.getElementById('messages').appendChild(sentMessage);
            document.getElementById('messageInput').value = '';
        }
    </script>

</head>
<%@ include file="body-script.jsp"%>

<h1 class="mt-4">WebSocket Test Client</h1>
<p>This tool will help you to test websocket server </p>
<hr>

<%@ include file="footer_adsense.jsp"%>

<div class="container">
    <div id="status" class="alert alert-secondary" role="alert">Status: Disconnected</div>
    <div class="input-group mb-3">
        <input type="text" id="serverUrl" value="wss://ws.postman-echo.com/raw" class="form-control" placeholder="wss://ws.postman-echo.com/raw">
        <div class="input-group-append">
            <button class="btn btn-primary" onclick="connect()">Connect</button>
        </div>
    </div>
    <div id="connectionControls" style="display:none;">
        <div class="input-group mb-3">
            <input type="text" id="messageInput" class="form-control" placeholder="Type your message here">
            <div class="input-group-append">
                <button class="btn btn-success" onclick="sendMessage()">Send</button>
            </div>
        </div>
    </div>
    <div id="messages" class="border rounded p-3"></div>
</div>

<hr>


<hr>

<div class="sharethis-inline-share-buttons"></div>

<%@ include file="thanks.jsp"%>

<%@ include file="footer_adsense.jsp"%>

<hr>
<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
    <div>
        <ul>
            <li><a href="aws.jsp">Ansible Generator(AWS)</a></li>
            <li><a href="dc1.jsp">Docker run to Docker Compose Conversion</a></li>
            <li><a href="dc2.jsp">Docker Compose to docker run Conversion</a></li>
            <li><a href="dc.jsp">Docker Compose Generator</a></li>
            <li><a href="kube1.jsp">Docker Compose to Kubernetes conversion</a></li>
            <li><a href="kube2.jsp">Kubernetes to Docker compose conversion</a></li>
            <li><a href="kube.jsp">Kubertes Spec Generate(Pods/svc)</a></li>
            <li><a href="jsonparser.jsp">JSON-2-YAML Convertor</a></li>
            <li><a href="yamlparser.jsp">YAML-2-JSON Convertor</a></li>
            <li><a href="qrcodegen.jsp">QR Code generate</a></li>
            <li><a href="hexdump.jsp">Online Hexdump Generate</a></li>
            <li><a href="diff.jsp">Compare text differences</a></li>
            <li><a href="UrlEncodeDecodeFunctions.jsp">URL Encoders/Decoders</a></li>
            <li><a href="HexToStringFunctions.jsp">Hex To String Conversion</a></li>
            <li><a href="HexToStringFunctions.jsp">String To Hex Conversion</a></li>
            <li><a href="base64Hex.jsp">Base64 To Hex (ViceVersa)</a></li>
            <li><a href="Base64Functions.jsp">Base64 Encode/Decode</a></li>
            <li><a href="base64image.jsp">Base64 Image Converter(data:image/png)</a></li>
            <li><a href="StringFunctions.jsp">Various String Functions</a></li>
        </ul>
    </div>
</div>

<hr>

<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>