<!DOCTYPE html>
<html>
<head>
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "SoftwareApplication",
  "name" : "Online yaml to json convertor",
  "image" : "https://8gwifi.org/images/site/xml2json.png",
  "url" : "https://8gwifi.org/xml2json.jsp",
  "author" : {
    "@type" : "Person",
    "name" : "Anish Nath"
  },
  "datePublished" : "2020-04-06",
  "applicationCategory" : [ "convert xml to json","convert xml to yaml" ,"xml convertor and parser parser"],
  "downloadUrl" : "https://8gwifi.org/xml2json.jsp",
  "operatingSystem" : "Linux,Unix,Windows,Redhat,RHEL,Fedora,Ubuntu,Android,iPhone",
  "requirements" : "xml to json,yaml convertor online",
  "softwareVersion" : "v1.0"
}
</script>
	<title>xml to json,yaml convertor online</title>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>

	<meta name="keywords" content="xml to json, xml to yaml, online xml to json, convert xml to json nad yaml, xml parser "/>
	<meta name="description" content="xml to json, xml to yaml, online xml to json, convert xml to json nad yaml, xml parser" />

	<meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<%@ include file="header-script.jsp"%>

	<script type="text/javascript">
		$(document).ready(function() {

			$('#encryptmsg').show();
			$('#descryptmsg').hide();

			$('#encrypt').click(function (event)
			{
				//
				$('#encryptmsg').show();
				$('#descryptmsg').hide();

			});

			$('#decrypt').click(function (event)
			{
				//
				$('#encryptmsg').hide();
				$('#descryptmsg').show();

			});

			$('#submit').click(function(event) {
				$('#form').delay(200).submit()
			});

			$('#form').submit(function(event) {
				//
				$('#output1').html('<img src="images/712.GIF"> loading...');
				event.preventDefault();
				$.ajax({
					type : "POST",
					url : "JSONFunctionality", //this is my servlet

					data : $("#form").serialize(),
					success : function(msg) {
						$('#output').empty();
						$('#output').append(msg);

					}
				});
			});
		});
	</script>
</head>

<%@ include file="body-script.jsp"%>

<h1 class="mt-4">XML to JSON/YAML Convertor</h1>
<p>Input XML data and get JSON/YAML output</p>

<div id="loading" style="display: none;">
	<img src="images/712.GIF" alt="" />Loading!
</div>

<hr>


			<form id="form" method="POST">
				<input type="hidden" name="methodName" id="methodName" value="xml_to_json">


				<div class="form-group row">
					<label for="input"  class="font-weight-bold col-sm-2 col-form-label">XML</label>
					<div class="col-sm-10">
						<textarea rows="10" cols="10" class="form-control" name="input" id="input"><samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_ONELOGIN103428909abec424fa58327f79474984" Version="2.0" IssueInstant="2014-11-13T11:39:34Z" ForceAuthn="false" IsPassive="false" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="http://example.com/acs">    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">        http://idp.example.com/metadata    </saml:Issuer>    <samlp:NameIDPolicy xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" SPNameQualifier="example.com" AllowCreate="true" ></samlp:NameIDPolicy>    <samlp:RequestedAuthnContext xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="exact">        <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">            urn:oasis:names:tc:SAML:2.0:ac:classes:Password        </saml:AuthnContextClassRef>    </samlp:RequestedAuthnContext></samlp:AuthnRequest></textarea>
					</div>
				</div>
					<input class="btn btn-primary" type="submit" id="submit" name="YAML2JSON">

			</form>
<div id="output"></div>

<h2 class="mt-4">Try Other Convertor</h2>
<div class="row">
	<div>
		<ul>
			<li><a href="jsonparser.jsp">JSON-2-YAML</a></li>
			<li><a href="yamlparser.jsp">YAML-2-JSON</a></li>
			<li><a href="xml2json.jsp">XML-2-JSON/YAML</a></li>
		</ul>
	</div>
</div>
<hr>

<div class="sharethis-inline-share-buttons"></div>
<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="footer_adsense.jsp"%>


<%@ include file="addcomments.jsp"%>

</div>

<%@ include file="body-close.jsp"%>

