<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="true" %>
<% String v = String.valueOf(System.currentTimeMillis()); %>
<!DOCTYPE html>
<html lang="en">
<head>
    <%--
        JEE Mains Practice — untimed practice page (Olympiad-style).
        Data: /math/iit/data/{q,s}/jee-practice-*.json generated by split_iit.py.
        Engine: /math/olympiad/js/practice-engine.js with custom statsKey/shareText.
    --%>
    <jsp:include page="../../modern/components/seo-tool-page.jsp">
        <jsp:param name="toolName" value="JEE Mains Practice Problems with Solutions — Free, Untimed, Online" />
        <jsp:param name="toolCategory" value="Math Tools" />
        <jsp:param name="toolDescription" value="Free JEE Mains math practice with detailed step-by-step solutions. Real past problems with MCQ and numerical types. Untimed practice, smart answer-matching for fractions, print-ready walkthroughs. No signup." />
        <jsp:param name="toolUrl" value="math/iit/practice.jsp" />
        <jsp:param name="breadcrumbCategoryUrl" value="math/" />
        <jsp:param name="toolKeywords" value="JEE Mains practice problems, JEE math practice, JEE problems with solutions, free JEE practice, JEE Mains questions with answers, JEE preparation, JEE Mains math solver, JEE numerical answer type, JEE MCQ practice, NEET math problems, JEE Advanced math, IIT JEE math practice, stepwise JEE solutions, JEE Mains previous year questions, JEE PYQ math, JEE Mains topic-wise practice" />
        <jsp:param name="toolImage" value="jee-practice-og.png" />
        <jsp:param name="hasSteps" value="true" />
        <jsp:param name="howToSteps" value="Pick a problem|Click Start or Next problem. A fresh random JEE Mains math problem loads with KaTeX-rendered formulas.,Try it yourself|For MCQ problems pick A/B/C/D. For numerical-type problems type the integer answer. Smart matching accepts fractions like 1/2 for \\frac{1}{2}.,Read the explanation|Click Reveal stepwise solution for the full numbered walkthrough. Solutions cover the technique step by step.,Print for offline study|Click Print to get a clean PDF with problem and walkthrough plus the 8gwifi.org/math/iit source line.,Track your progress|Session stats (attempted / correct / streak) save in your browser. Reset any time." />
        <jsp:param name="faq1q" value="What level are these JEE practice problems?" />
        <jsp:param name="faq1a" value="Real past JEE Mains math problems plus historical pool material — covers MCQ and numerical-answer types across algebra, calculus, coordinate geometry, vectors, probability, and other Mains topics. Difficulty mirrors actual papers." />
        <jsp:param name="faq2q" value="Is this timed like a real JEE mock?" />
        <jsp:param name="faq2a" value="This page is untimed practice — one problem at a time with full step-by-step solutions on demand. For timed shift-by-shift JEE Main 2025 mocks (with +4 / −1 official scoring), see the JEE Mains 2025 mock page." />
        <jsp:param name="faq3q" value="Can I check my numerical or fractional answer?" />
        <jsp:param name="faq3a" value="Yes. The Check button uses smart matching — type 1/2 to match \\frac{1}{2}, sqrt(5) to match \\sqrt{5}, decimals automatically compare against fractions. For MCQ pick the option directly." />
        <jsp:param name="faq4q" value="Can I print problems and solutions?" />
        <jsp:param name="faq4a" value="Yes. Click Print on any problem. The print view shows the question and full stepwise walkthrough at print-friendly typography with an 8gwifi.org/math/iit source line — useful as offline worksheets." />
        <jsp:param name="faq5q" value="Is this also useful for JEE Advanced or NEET?" />
        <jsp:param name="faq5a" value="The pool overlaps significantly with NEET math and the foundational topics for JEE Advanced. For pure JEE Advanced problems use this as a warm-up; the technique vocabulary transfers directly." />
        <jsp:param name="faq6q" value="Are my stats saved?" />
        <jsp:param name="faq6a" value="Yes — attempted / correct / streak / best-streak save in your browser's localStorage. Nothing is sent to a server. Click Reset to clear them any time." />
    </jsp:include>

    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "Free JEE Mains Math Practice",
      "url": "https://8gwifi.org/math/iit/practice.jsp",
      "applicationCategory": "EducationalApplication",
      "operatingSystem": "Any (browser)",
      "offers": { "@type": "Offer", "price": "0.00", "priceCurrency": "USD" },
      "isAccessibleForFree": true
    }
    </script>

    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/design-system.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/navigation.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/dark-mode.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/footer.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/ads.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/css/math-studio.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/amc/css/exam.css?v=<%=v%>">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/olympiad/css/practice.css?v=<%=v%>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">

    <%@ include file="../../modern/ads/ad-init.jsp" %>
</head>
<body class="ms-body">

<jsp:include page="../../modern/components/nav-header.jsp" />
<jsp:include page="/math/partials/matter-bg.jsp" />

<div class="ms-hero">
    <%@ include file="../../modern/ads/ad-hero-banner.jsp" %>
</div>

<main class="ms-main">
    <button type="button" id="msSidebarToggle" class="ms-sidebar-toggle" aria-label="Open math tools menu">
        &#9776; Math tools
    </button>

    <% request.setAttribute("activeService", "jee-practice"); %>
    <jsp:include page="/math/partials/sidebar.jsp" />

    <section class="ms-workspace">
        <header class="ms-title">
            <nav class="ms-crumbs">
                <a href="<%=request.getContextPath()%>/index.jsp">Home</a>
                <span>/</span>
                <a href="<%=request.getContextPath()%>/math/">Math</a>
                <span>/</span>
                <a href="<%=request.getContextPath()%>/math/iit/">IIT JEE</a>
                <span>/</span>
                <span aria-current="page">Practice</span>
            </nav>
            <h1>Free JEE Mains Practice Problems &mdash; Untimed, with Stepwise Solutions</h1>
            <p class="xm-hero-sub">
                Real past JEE Mains math problems with detailed step-by-step
                walkthroughs. Type your answer (smart matching for fractions,
                radicals, decimals) or reveal the full solution on demand.
                <strong>Untimed · single problem at a time · no signup.</strong>
            </p>
        </header>

        <div id="op-root"></div>

        <div class="ms-inline-ad">
            <%@ include file="../../modern/ads/ad-in-content-mid.jsp" %>
        </div>

        <%-- SEO body --%>
        <nav class="xm-toc" aria-label="On this page">
            <span class="xm-toc-label">On this page:</span>
            <a href="#about">About JEE practice</a>
            <a href="#how">How to use it</a>
            <a href="#mock-link">2025 Shift Mocks</a>
            <a href="#faq">FAQ</a>
        </nav>

        <section class="xm-seo-section" id="about">
            <h2>Free JEE Mains math practice — untimed, with step-by-step solutions</h2>
            <p>
                If you're preparing for <strong>JEE Mains</strong>, the
                highest-leverage activity is solving past problems and reading
                worked solutions written by experienced solvers. This page
                gives you that, free and untimed.
            </p>
            <p>
                Each session loads a fresh random problem with the math
                rendered in KaTeX. The pool covers all JEE Mains math
                topics — sequences and series, complex numbers, matrices,
                determinants, vectors, 3D geometry, conic sections, calculus
                (limits, derivatives, integrals), probability and statistics,
                differential equations, and more. Both MCQ and numerical
                answer types are included so you train both formats.
            </p>
        </section>

        <section class="xm-seo-section" id="how">
            <h2>How to use it</h2>
            <ol class="xm-info-list xm-info-list-ol">
                <li><strong>Try the problem cold.</strong> For MCQ pick A/B/C/D; for numerical type the integer answer.</li>
                <li><strong>Hit Check.</strong> Smart matching accepts <code>1/2</code> ↔ <code>\frac{1}{2}</code>, <code>sqrt(5)</code> ↔ <code>\sqrt{5}</code>, decimals auto-compare.</li>
                <li><strong>Reveal stepwise solution.</strong> Full numbered walkthrough — read the misses carefully.</li>
                <li><strong>Print for offline study.</strong> Click Print on any problem to save it as a PDF worksheet with branding.</li>
                <li><strong>Click Next problem</strong> for a fresh random — repeat. Stats save locally.</li>
            </ol>
        </section>

        <section class="xm-seo-section" id="mock-link">
            <h2>Want timed JEE Mains 2025 mocks?</h2>
            <p>
                This page is untimed practice. For a live timed mock test
                running an actual JEE Main 2025 paper (25 questions per
                shift with the official <strong>+4 / −1 / 0</strong>
                scoring rule), try the shift-wise mocks:
            </p>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/iit/">
                    <div class="xm-related-card-title">JEE Mains 2025 Mock Tests</div>
                    <div class="xm-related-card-desc">10 timed papers · 25 Qs each · official scoring · real questions.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/">
                    <div class="xm-related-card-title">AMC 10 / 12 Mock</div>
                    <div class="xm-related-card-desc">US contest emulator — 25 MCQ, 75 min, modern scoring.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/aime.jsp">
                    <div class="xm-related-card-title">AIME Mock</div>
                    <div class="xm-related-card-desc">15 free-response · 3 hr · integer 0–999.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/olympiad/">
                    <div class="xm-related-card-title">Olympiad Practice</div>
                    <div class="xm-related-card-desc">RMO, INMO, IMO problems with stepwise solutions.</div>
                </a>
            </div>
        </section>

        <section class="xm-seo-section" id="faq">
            <h2>Frequently asked questions</h2>
            <details class="xm-faq-item" open>
                <summary>What level are these JEE practice problems?</summary>
                <p>Real past JEE Mains math problems plus historical pool material — covers MCQ and numerical-answer types across algebra, calculus, coordinate geometry, vectors, probability, and other Mains topics. Difficulty mirrors actual papers.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Is this timed like a real JEE mock?</summary>
                <p>This page is untimed practice — one problem at a time with full step-by-step solutions on demand. For timed shift-by-shift <a href="<%=request.getContextPath()%>/math/iit/">JEE Main 2025 mocks</a> with +4/−1 scoring, see the JEE Mains 2025 hub.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Can I check my numerical or fractional answer?</summary>
                <p>Yes. Smart matching accepts <code>1/2</code> for <code>\frac{1}{2}</code>, <code>sqrt(5)</code> for <code>\sqrt{5}</code>, decimals automatically compare against fractions. For MCQ pick the option directly.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Can I print problems and solutions?</summary>
                <p>Yes. Click <strong>Print</strong>. The print view shows the question and full stepwise walkthrough at print-friendly typography with an <code>8gwifi.org/math/iit</code> source line — useful as offline worksheets.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Is this also useful for JEE Advanced or NEET?</summary>
                <p>The pool overlaps significantly with NEET math and the foundational topics for JEE Advanced. Technique vocabulary transfers — use this as a warm-up before deeper JEE Advanced material.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Are my stats saved?</summary>
                <p>Yes — attempted / correct / streak / best-streak save in your browser's localStorage. Nothing is sent to a server.</p>
            </details>
        </section>
    </section>

    <aside class="ms-rail" aria-label="Advertisements">
        <%@ include file="../../modern/ads/ad-ide-rail-top.jsp" %>
        <%@ include file="../../modern/ads/ad-ide-rail-bottom.jsp" %>
    </aside>
</main>

<%@ include file="../../modern/ads/ad-sticky-footer.jsp" %>
<%@ include file="../../modern/components/analytics.jsp" %>

<jsp:include page="/math/partials/math-libs.jsp" />

<%-- Reuse the Olympiad practice engine — same untimed flow, parameterized
     with a different statsKey + share text so JEE progress stays separate. --%>
<script src="<%=request.getContextPath()%>/math/olympiad/js/practice-engine.js?v=<%=v%>"></script>
<script>
    OlympiadEngine.init({
        rootId:    'op-root',
        dataBase:  '<%=request.getContextPath()%>/math/iit/data',
        bucket:    'jee-practice',
        title:     'JEE Mains Practice',
        statsKey:  'jee.stats',
        shareText: 'Free JEE Mains practice with step-by-step solutions — try it, via @anish2good'
    });
</script>

</body>
</html>
