<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" isELIgnored="true" %>
<% String v = String.valueOf(System.currentTimeMillis()); %>
<!DOCTYPE html>
<html lang="en">
<head>
    <%--
        AMC Live Mock-Test Emulator — 25 questions, 75 minutes, MCQ.
        Data: /math/amc/data/{q,s,meta.json} generated by split_amc.py.
        Engine: /math/amc/js/exam-engine.js (vanilla; no build).
    --%>
    <jsp:include page="../../modern/components/seo-tool-page.jsp">
        <jsp:param name="toolName" value="Free AMC 10/12 Mock Test — Live Timed Practice with Solutions" />
        <jsp:param name="toolCategory" value="Math Tools" />
        <jsp:param name="toolDescription" value="Free AMC 10/12 mock test: 25 real past problems, 75-min timer, official scoring (+6/+1.5/0), and step-by-step solutions. No signup, runs in your browser." />
        <jsp:param name="toolUrl" value="math/amc/" />
        <jsp:param name="breadcrumbCategoryUrl" value="math/" />
        <jsp:param name="toolKeywords" value="AMC mock test, AMC 10 practice, AMC 12 practice, AMC simulator, free AMC test, online AMC emulator, AMC timed practice, AMC past problems, AMC solutions, AMC training, AMC competition math" />
        <jsp:param name="toolImage" value="amc-emulator-og.png" />
        <jsp:param name="toolFeatures" value="25 randomly sampled past AMC problems per session,75-minute live countdown timer with warnings,Multiple-choice answer pads (A-E) with KaTeX-rendered math,Flag-for-review and question navigator (answered / flagged / blank),Auto-submit on time expiry; manual submit any time,Score report using modern AMC scoring (+6 correct, +1.5 unanswered),Step-by-step solutions revealed in review mode,Keyboard shortcuts (arrows + A-E)" />
        <jsp:param name="hasSteps" value="true" />
        <jsp:param name="teaches" value="AMC 10/12 problem patterns, time-pressured test strategy, MCQ elimination, competition math fundamentals" />
        <jsp:param name="educationalLevel" value="High School" />
        <jsp:param name="howToSteps" value="Start the mock|Click Start Test. The engine pulls 25 randomized real AMC problems from a 2994-problem pool.,Answer at your own pace|Click a choice or press A-E. Use arrow keys or the navigator pills to move between questions. Flag any you want to revisit.,Watch the clock|The 75-minute timer turns amber at five minutes and red in the final minute. Submit at any time or let time expire.,Review your score|See your total score on the modern AMC scoring system plus a question-by-question breakdown with full solutions." />
        <jsp:param name="faq1q" value="How is the AMC mock score computed?" />
        <jsp:param name="faq1a" value="Modern AMC scoring (used since 2002): each correct answer is +6 points, each wrong answer is 0, each unanswered question is +1.5. With 25 questions the max is 150. Leaving harder questions blank is sometimes strategically optimal — this is the trade-off the AMC scoring rule rewards." />
        <jsp:param name="faq2q" value="Where do the problems come from?" />
        <jsp:param name="faq2a" value="The pool is 2994 multiple-choice problems extracted from past AMC 10 and AMC 12 contests. Problems and solutions are taken from open archives. Each session samples 25 at random — taking the test again gives you a fresh set." />
        <jsp:param name="faq3q" value="Is this an exact replica of a real AMC contest?" />
        <jsp:param name="faq3a" value="The format mirrors a real AMC: 25 questions, 75 minutes, MCQ A-E, modern scoring. The questions are real past AMC problems but not bundled by year, so difficulty mix varies session to session. For a year-specific paper, see AoPS." />
        <jsp:param name="faq4q" value="Can I see solutions?" />
        <jsp:param name="faq4a" value="Yes — after you submit, every question expands in the review section to show your answer, the correct answer, and the full step-by-step solution (rendered with KaTeX)." />
        <jsp:param name="faq5q" value="Does this work offline?" />
        <jsp:param name="faq5a" value="Once loaded, the session runs entirely in your browser — no progress is sent to any server. KaTeX renders math locally. The only network hit on first load is fetching one ~260 KB JSON shard of questions." />
        <jsp:param name="faq6q" value="Is the AIME version separate?" />
        <jsp:param name="faq6a" value="Yes — AIME problems are free-response integers 0-999 with a 180-minute window and different scoring. The AIME mock test lives at /math/amc/aime.jsp." />
    </jsp:include>

    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "Free AMC 10/12 Live Mock Test",
      "url": "https://8gwifi.org/math/amc/",
      "applicationCategory": "EducationalApplication",
      "operatingSystem": "Any (browser)",
      "offers": { "@type": "Offer", "price": "0.00", "priceCurrency": "USD" },
      "isAccessibleForFree": true
    }
    </script>

    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/design-system.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/navigation.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/dark-mode.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/footer.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/modern/css/ads.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/css/math-studio.css">
    <link rel="stylesheet" href="<%=request.getContextPath()%>/math/amc/css/exam.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">

    <%@ include file="../../modern/ads/ad-init.jsp" %>
</head>
<body class="ms-body">

<jsp:include page="../../modern/components/nav-header.jsp" />
<jsp:include page="/math/partials/matter-bg.jsp" />

<div class="ms-hero">
    <%@ include file="../../modern/ads/ad-hero-banner.jsp" %>
</div>

<main class="ms-main">

    <button type="button" id="msSidebarToggle" class="ms-sidebar-toggle" aria-label="Open math tools menu">
        &#9776; Math tools
    </button>

    <% request.setAttribute("activeService", "amc"); %>
    <jsp:include page="/math/partials/sidebar.jsp" />

    <section class="ms-workspace">

        <header class="ms-title">
            <nav class="ms-crumbs">
                <a href="<%=request.getContextPath()%>/index.jsp">Home</a>
                <span>/</span>
                <a href="<%=request.getContextPath()%>/math/">Math</a>
                <span>/</span>
                <span aria-current="page">AMC Mock Test</span>
            </nav>
            <h1>Free AMC 10/12 Mock Test &mdash; Live, Timed, with Solutions</h1>
            <p class="xm-hero-sub">
                A timed AMC 10 / AMC 12 emulator with real past problems and
                official scoring. <strong>25 questions · 75 minutes · MCQ.</strong>
                Submit when you're done for a full breakdown and step-by-step
                solutions. No signup, runs entirely in your browser.
            </p>
            <div class="xm-hero-chips">
                <span class="xm-hero-chip">Real past AMC problems</span>
                <span class="xm-hero-chip">Official +6 / +1.5 / 0 scoring</span>
                <span class="xm-hero-chip">KaTeX math rendering</span>
                <span class="xm-hero-chip">Step-by-step solutions</span>
            </div>
        </header>

        <div id="xm-root"></div>

        <div class="ms-inline-ad">
            <%@ include file="../../modern/ads/ad-in-content-mid.jsp" %>
        </div>

        <%-- ─────────────────────────── SEO body ─────────────────────────── --%>

        <nav class="xm-toc" aria-label="On this page">
            <span class="xm-toc-label">On this page:</span>
            <a href="#about-amc">About the AMC</a>
            <a href="#amc-scoring">Scoring rules</a>
            <a href="#aime-qualification">AIME cutoffs</a>
            <a href="#how-to-use">How to use this mock</a>
            <a href="#topics">Topics covered</a>
            <a href="#amc-vs-aime">AMC vs AIME</a>
            <a href="#faq">FAQ</a>
        </nav>

        <section class="xm-seo-section" id="about-amc">
            <h2>About the AMC 10 and AMC 12</h2>
            <p>
                The <strong>American Mathematics Competitions</strong> (AMC) are the most
                widely written high-school math contests in the United States, hosted by
                the Mathematical Association of America (MAA). Two papers run each year:
                the <strong>AMC 10</strong> for students in grade 10 and under and the
                <strong>AMC 12</strong> for grade 12 and under. Both papers are
                <em>25 multiple-choice questions in 75 minutes</em>, no calculators.
            </p>
            <p>
                The AMC is the entry point to the United States olympiad ladder. Top
                scorers qualify for the
                <a href="<%=request.getContextPath()%>/math/amc/aime.jsp">AIME</a>
                (American Invitational Mathematics Examination); top AIME scorers
                advance to the USAMO and ultimately the International Mathematical
                Olympiad team. Even if you're not aiming for IMO, mock practice on
                real past papers is one of the highest-leverage activities for
                building speed, pattern recognition, and resilience under time
                pressure.
            </p>
        </section>

        <section class="xm-seo-section" id="amc-scoring">
            <h2>How AMC scoring works</h2>
            <p>
                Since 2002 the AMC has used a deliberately asymmetric scoring rule
                that rewards careful skipping over wild guessing:
            </p>
            <table class="xm-info-table">
                <thead>
                    <tr><th>Outcome</th><th>Points</th><th>Strategic implication</th></tr>
                </thead>
                <tbody>
                    <tr><td>Correct answer</td><td><strong>+6</strong></td><td>Maximize accuracy on questions you can solve cleanly.</td></tr>
                    <tr><td>Unanswered (blank)</td><td><strong>+1.5</strong></td><td>Leaving a hard question blank is worth ¼ of a correct one.</td></tr>
                    <tr><td>Wrong answer</td><td><strong>0</strong></td><td>Random guessing is neutral but worse than blanking when you can eliminate options.</td></tr>
                </tbody>
            </table>
            <p>
                The maximum score is <strong>150</strong>. A blank-strategy
                expected-value calculation: if you can eliminate one of five
                choices, guessing breaks even with leaving blank. Eliminate two
                and guessing is positive EV. Our mock implements this scoring
                rule exactly, so the timer and submit screen mirror a real AMC.
            </p>
        </section>

        <section class="xm-seo-section" id="aime-qualification">
            <h2>What score qualifies you for the AIME?</h2>
            <p>
                The MAA sets year-by-year cutoffs, typically targeting the top
                ~2.5% of AMC 10 scorers and ~5% of AMC 12 scorers. Recent ballpark
                figures:
            </p>
            <ul class="xm-info-list">
                <li><strong>AMC 10:</strong> usually a score of <em>105–120</em> qualifies (~70th–80th percentile of scorers).</li>
                <li><strong>AMC 12:</strong> usually a score of <em>85–100</em> qualifies (~80th–90th percentile).</li>
                <li>The exact cutoff is announced after both A and B papers are scored each year.</li>
            </ul>
            <p>
                If you're hitting these scores consistently in mock practice, you're
                in qualifying range. The next step is the
                <a href="<%=request.getContextPath()%>/math/amc/aime.jsp"><strong>AIME mock test</strong></a> —
                15 free-response problems in 3 hours where answers are integers from
                0 to 999.
            </p>
        </section>

        <section class="xm-seo-section" id="how-to-use">
            <h2>How to use this AMC mock test emulator</h2>
            <ol class="xm-info-list xm-info-list-ol">
                <li><strong>Click <em>Start Test</em></strong> — the engine pulls a fresh random set of 25 problems from a deep pool of real past AMC 10 and AMC 12 questions.</li>
                <li><strong>Pace yourself against the live timer.</strong> 75 minutes is roughly 3 minutes per problem; the timer turns amber at 5:00 and red in the final minute.</li>
                <li><strong>Flag and skip aggressively.</strong> Use the flag button on hard problems and come back; the question navigator lets you jump to any number in any order.</li>
                <li><strong>Submit when ready</strong> — or let the clock expire. You'll get an AMC-format score (out of 150), a correct / wrong / blank breakdown, and full step-by-step solutions for every question.</li>
                <li><strong>Review and retry.</strong> Click into any review row to see the detailed solution. Take another fresh test once the 5-minute cooldown ends — every set is randomly sampled.</li>
            </ol>
        </section>

        <section class="xm-seo-section" id="topics">
            <h2>Topics covered on the AMC</h2>
            <p>
                AMC problems blend four major strands of pre-college math. Strong
                AMC training touches all of them. We have free tools for each:
            </p>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/quadratic-solver.jsp">
                    <div class="xm-related-card-title">Algebra</div>
                    <div class="xm-related-card-desc">Quadratics, polynomial roots, function manipulation. Try the quadratic solver →</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/system-equations-solver.jsp">
                    <div class="xm-related-card-title">Systems &amp; linear algebra</div>
                    <div class="xm-related-card-desc">2–3 variable systems, matrix work, vector problems. Try the system solver →</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/trigonometric-function-calculator.jsp">
                    <div class="xm-related-card-title">Geometry &amp; trig</div>
                    <div class="xm-related-card-desc">Angle chasing, similar triangles, circles, trig identities. Try the trig tools →</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/probability-calculator.jsp">
                    <div class="xm-related-card-title">Combinatorics &amp; probability</div>
                    <div class="xm-related-card-desc">Counting, pigeonhole, casework, expected value. Try the probability tools →</div>
                </a>
            </div>
        </section>

        <section class="xm-seo-section" id="amc-vs-aime">
            <h2>AMC vs AIME — what's the difference?</h2>
            <table class="xm-info-table">
                <thead>
                    <tr><th>&nbsp;</th><th>AMC 10 / 12</th><th>AIME</th></tr>
                </thead>
                <tbody>
                    <tr><td>Format</td><td>Multiple choice (A–E)</td><td>Integer free-response (0–999)</td></tr>
                    <tr><td>Questions</td><td>25</td><td>15</td></tr>
                    <tr><td>Time</td><td>75 minutes</td><td>180 minutes (3 hours)</td></tr>
                    <tr><td>Scoring</td><td>+6 / +1.5 / 0 (max 150)</td><td>+1 each correct (max 15)</td></tr>
                    <tr><td>Difficulty</td><td>Pre-olympiad, ramps from easy to hard</td><td>Olympiad-prep, uniformly hard</td></tr>
                    <tr><td>Who takes it</td><td>Open to all high-schoolers</td><td>AMC qualifiers only</td></tr>
                </tbody>
            </table>
            <p style="margin-top:0.85rem;">
                Try the <a href="<%=request.getContextPath()%>/math/amc/aime.jsp"><strong>AIME mock test</strong></a>
                if you want to feel the jump in difficulty.
            </p>
        </section>

        <section class="xm-seo-section" id="faq">
            <h2>Frequently asked questions</h2>
            <details class="xm-faq-item" open>
                <summary>How is the AMC mock score computed?</summary>
                <p>Modern AMC scoring (used since 2002): each correct answer is +6 points, each wrong answer is 0, each unanswered question is +1.5. With 25 questions the max is 150. Leaving harder questions blank is sometimes strategically optimal — this is the trade-off the AMC scoring rule rewards.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Where do the problems come from?</summary>
                <p>The pool draws from real past AMC 10 and AMC 12 contests. Problems and solutions come from open archives. Each session samples a fresh random set — every retake gives you new problems.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Is this an exact replica of a real AMC contest?</summary>
                <p>The format mirrors a real AMC: 25 questions, 75 minutes, MCQ A–E, modern scoring. The questions are real past AMC problems but not bundled by year, so the difficulty mix varies session to session. For a specific year's paper, AoPS keeps the canonical archive.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Can I see solutions?</summary>
                <p>Yes — after you submit, every question expands in the review section to show your answer, the correct answer, and the full step-by-step solution (rendered with KaTeX).</p>
            </details>
            <details class="xm-faq-item">
                <summary>Why is there a 5-minute cooldown between tests?</summary>
                <p>The cooldown is there so you actually <em>review</em> the test you just took. Score reports and solutions matter more than raw volume — use the wait to study the misses, then come back fresh. The cooldown is per-exam, so AMC and AIME don't gate each other.</p>
            </details>
            <details class="xm-faq-item">
                <summary>Does this work offline / send my data anywhere?</summary>
                <p>Once loaded, the session runs entirely in your browser. KaTeX renders math locally. The only network hit on first load is fetching one JSON shard of questions plus the page's static assets. Your scores stay in your browser's localStorage.</p>
            </details>
        </section>

        <section class="xm-seo-section" id="more-tools">
            <h2>More free math tools</h2>
            <div class="xm-related-grid">
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/amc/aime.jsp">
                    <div class="xm-related-card-title">AIME mock test</div>
                    <div class="xm-related-card-desc">15 free-response problems · 3-hour timer · integer answers 0–999.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/worksheet.jsp">
                    <div class="xm-related-card-title">Practice worksheets</div>
                    <div class="xm-related-card-desc">Printable worksheets across algebra, geometry, calculus and more.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/dashboard.jsp">
                    <div class="xm-related-card-title">Math editor</div>
                    <div class="xm-related-card-desc">Write and render LaTeX live with KaTeX — useful for your own notes.</div>
                </a>
                <a class="xm-related-card" href="<%=request.getContextPath()%>/math/">
                    <div class="xm-related-card-title">All math tools</div>
                    <div class="xm-related-card-desc">Browse 48+ free calculators and solvers across math topics.</div>
                </a>
            </div>
        </section>

    </section>

    <aside class="ms-rail" aria-label="Advertisements">
        <%@ include file="../../modern/ads/ad-ide-rail-top.jsp" %>
        <%@ include file="../../modern/ads/ad-ide-rail-bottom.jsp" %>
    </aside>

</main>

<%@ include file="../../modern/ads/ad-sticky-footer.jsp" %>
<%@ include file="../../modern/components/analytics.jsp" %>

<jsp:include page="/math/partials/math-libs.jsp" />

<script src="<%=request.getContextPath()%>/math/amc/js/exam-engine.js"></script>
<script>
    ExamEngine.init({
        rootId:      'xm-root',
        dataBase:    '<%=request.getContextPath()%>/math/amc/data',
        bucket:      'amc-real',
        questions:   25,
        durationMin: 75,
        format:      'mcq',
        title:       'AMC 10/12 — Live Mock Test',
        subtitle:    '25 questions · 75 minutes · multiple choice (A–E)',
        scoring:     { correct: 6, wrong: 0, unanswered: 1.5, max: 150 }
    });
</script>

</body>
</html>
